import Map "mo:core/Map";
import Array "mo:core/Array";
import Iter "mo:core/Iter";
import Types "../types/elements";

module {
  public type Element = Types.Element;
  public type ElementMap = Map.Map<Text, Element>;

  // ── dataset helpers ────────────────────────────────────────────────────────
  func e(
    symbol : Text,
    name : Text,
    atomicNumber : Nat,
    atomicMass : Float,
    category : Text,
    group : Nat,
    period : Nat,
    block : Text,
    state : Text,
    density : Float,
    meltingPoint : Float,
    boilingPoint : Float,
    electronegativity : Float,
    ionizationEnergy : Float,
    atomicRadius : Float,
    electronConfiguration : Text,
    description : Text,
    uses : [Text],
    facts : [Text],
    colorHex : Text,
  ) : Element = {
    symbol; name; atomicNumber; atomicMass; category; group; period; block;
    state; density; meltingPoint; boilingPoint; electronegativity;
    ionizationEnergy; atomicRadius; electronConfiguration; description;
    uses; facts; colorHex;
  };

  // ── full 118-element dataset ───────────────────────────────────────────────
  func allElements() : [Element] { [
    e("H",  "Hydrogen",       1,   1.008,   "nonmetal",              1,  1, "s", "Gas",    0.00009, -259.16, -252.88, 2.20, 13.598, 53.0,  "1s1",                      "Hydrogen is the lightest and most abundant element in the universe. It makes up roughly 75% of all normal matter by mass. It is the primary fuel in stellar nuclear fusion.",                                                                 ["Rocket fuel","Petroleum refining","Fertiliser production","Fuel cells"],              ["Its isotope deuterium is used in nuclear fusion research","Stars convert hydrogen to helium via nuclear fusion","Liquid hydrogen is used as cryogenic propellant"],       "#38BDF8"),
    e("He", "Helium",         2,   4.0026,  "noble-gas",             18, 1, "s", "Gas",    0.00017, -272.20, -268.93, 0.00, 24.587, 31.0,  "1s2",                      "Helium is the second lightest and most common noble gas. It is colourless, odourless, and tasteless. It was first detected in the solar spectrum before being found on Earth.",                                                              ["Balloons","Cryogenics","Airships","MRI cooling"],                                     ["Second most abundant element in the universe","Only element that cannot be solidified at normal pressure","Discovered in the Sun before on Earth"],                       "#A78BFA"),
    e("Li", "Lithium",        3,   6.941,   "alkali-metal",          1,  2, "s", "Solid",  0.534,   180.54,  1342.0,  0.98, 5.392,  167.0, "1s2 2s1",                  "Lithium is the lightest metal and solid element. It is soft enough to cut with a knife and highly reactive. Lithium compounds are widely used in rechargeable batteries.",                                                                    ["Batteries","Psychiatric medication","Aerospace alloys","Ceramics"],                   ["Lightest solid element","Floats on water due to low density","Named after the Greek word for stone"],                                                                     "#F472B6"),
    e("Be", "Beryllium",      4,   9.0122,  "alkaline-earth-metal",  2,  2, "s", "Solid",  1.850,   1287.0,  2472.0,  1.57, 9.323,  112.0, "1s2 2s2",                  "Beryllium is a hard, grayish metal naturally found in minerals. It has an exceptional stiffness-to-weight ratio. Despite its usefulness, beryllium dust is highly toxic.",                                                                  ["Aerospace components","X-ray windows","Nuclear reactors","Copper alloys"],            ["Extremely stiff for its weight","Transparent to X-rays","Its dust is extremely toxic causing berylliosis"],                                                              "#34D399"),
    e("B",  "Boron",          5,   10.81,   "metalloid",             13, 2, "p", "Solid",  2.340,   2076.0,  3927.0,  2.04, 8.298,  87.0,  "1s2 2s2 2p1",              "Boron is a metalloid with properties between metals and nonmetals. It is an essential micronutrient for plants. High-purity boron is used as a semiconductor in electronics.",                                                               ["Glass and ceramics","Detergents","Semiconductors","Nuclear shielding"],               ["Essential nutrient for plant growth","Harder than most ceramics in certain allotropes","Used in Pyrex glass for heat resistance"],                                       "#FB923C"),
    e("C",  "Carbon",         6,   12.011,  "nonmetal",              14, 2, "p", "Solid",  2.260,   3652.0,  4827.0,  2.55, 11.260, 77.0,  "1s2 2s2 2p2",              "Carbon is the basis of all known life on Earth. It forms more compounds than any other element, thanks to its unique ability to form stable chains and rings. Diamond and graphite are its two best-known allotropes.",                    ["Steel production","Pencils (graphite)","Diamonds","Carbon fibre composites"],        ["Forms more compounds than any other element","Diamond is the hardest natural material","Graphene is stronger than steel yet incredibly light"],                         "#94A3B8"),
    e("N",  "Nitrogen",       7,   14.007,  "nonmetal",              15, 2, "p", "Gas",    0.00125, -210.0,  -195.79, 3.04, 14.534, 75.0,  "1s2 2s2 2p3",              "Nitrogen makes up about 78% of Earth's atmosphere by volume. It is relatively inert at room temperature due to the strong triple bond in N₂. Nitrogen compounds are essential for all living organisms.",                                  ["Fertilisers","Explosives","Cryogenics","Inert atmospheres"],                          ["Makes up 78% of Earth's atmosphere","Required for all known life forms","Liquid nitrogen boils at -196 °C, used for quick freezing"],                                  "#60A5FA"),
    e("O",  "Oxygen",         8,   15.999,  "nonmetal",              16, 2, "p", "Gas",    0.00143, -218.4,  -182.96, 3.44, 13.618, 73.0,  "1s2 2s2 2p4",              "Oxygen is the third most abundant element in the universe and essential for most life on Earth. It constitutes about 21% of the atmosphere and is needed for cellular respiration. It also forms oxides with nearly all elements.",          ["Steel and iron production","Welding","Medical oxygen","Water treatment"],             ["Essential for aerobic respiration","Makes up 21% of Earth's atmosphere","Most abundant element in Earth's crust by mass"],                                             "#F87171"),
    e("F",  "Fluorine",       9,   18.998,  "halogen",               17, 2, "p", "Gas",    0.00170, -219.6,  -188.12, 3.98, 17.423, 71.0,  "1s2 2s2 2p5",              "Fluorine is the most electronegative and reactive of all elements. It reacts with almost all organic and inorganic substances. Even noble gases like xenon can form compounds with fluorine.",                                                ["Non-stick coatings (PTFE)","Toothpaste","Refrigerants","Pharmaceuticals"],            ["Most electronegative element known","Reacts with almost every other element","Used to enrich uranium in nuclear fuel"],                                                  "#A3E635"),
    e("Ne", "Neon",           10,  20.180,  "noble-gas",             18, 2, "p", "Gas",    0.00090, -248.59, -246.05, 0.00, 21.565, 38.0,  "1s2 2s2 2p6",              "Neon is a noble gas that glows bright reddish-orange when electrically excited. It is the fifth most abundant element in the universe. Despite its prevalence in neon signs, neon is relatively rare on Earth.",                              ["Neon signs","Lasers","Cryogenic refrigerant","Vacuum tube indicators"],               ["Gives the characteristic red-orange colour in neon signs","Fifth most abundant element in the universe","Less reactive than any other element"],                        "#A78BFA"),
    e("Na", "Sodium",         11,  22.990,  "alkali-metal",          1,  3, "s", "Solid",  0.971,   97.72,   882.9,   0.93, 5.139,  190.0, "1s2 2s2 2p6 3s1",          "Sodium is a soft, silvery-white, highly reactive metal. It reacts vigorously with water to produce hydrogen gas. It is essential to human physiology and is commonly found as sodium chloride (table salt).",                            ["Table salt (NaCl)","Street lighting","Soap production","Food preservation"],         ["Explodes on contact with water","Burns with a characteristic yellow flame","Essential electrolyte in human biology"],                                                    "#F472B6"),
    e("Mg", "Magnesium",      12,  24.305,  "alkaline-earth-metal",  2,  3, "s", "Solid",  1.738,   650.0,   1090.0,  1.31, 7.646,  172.0, "1s2 2s2 2p6 3s2",          "Magnesium is a shiny, light, and fairly strong metal. It is the eighth most abundant element in Earth's crust. Magnesium is essential for chlorophyll, the molecule that drives photosynthesis in plants.",                            ["Lightweight alloys","Flares and pyrotechnics","Dietary supplements","Antacids"],     ["Burns with a brilliant white flame","Essential for plant photosynthesis","Lightest structural metal used in engineering"],                                              "#34D399"),
    e("Al", "Aluminium",      13,  26.982,  "post-transition-metal", 13, 3, "p", "Solid",  2.700,   660.32,  2519.0,  1.61, 5.986,  184.0, "1s2 2s2 2p6 3s2 3p1",      "Aluminium is the most abundant metal in Earth's crust and the third most abundant element overall. It forms a protective oxide layer that resists corrosion. It is lightweight yet strong, making it ideal for aerospace and packaging.",  ["Cans and packaging","Aerospace","Construction","Electrical wiring"],                  ["Most abundant metal in Earth's crust","Only 5% of energy needed to recycle compared to primary production","Resists corrosion through self-passivation"],               "#94A3B8"),
    e("Si", "Silicon",        14,  28.086,  "metalloid",             14, 3, "p", "Solid",  2.329,   1414.0,  3265.0,  1.90, 8.151,  210.0, "1s2 2s2 2p6 3s2 3p2",      "Silicon is the second most abundant element in Earth's crust after oxygen. It is the backbone of modern electronics, used in semiconductors and solar cells. Silicon dioxide forms quartz, sand, and glass.",                            ["Semiconductors and chips","Solar cells","Glass and ceramics","Silicones"],           ["Backbone of modern electronics","Second most abundant element in Earth's crust","Sand is mostly silicon dioxide"],                                                     "#FB923C"),
    e("P",  "Phosphorus",     15,  30.974,  "nonmetal",              15, 3, "p", "Solid",  1.820,   44.15,   280.5,   2.19, 10.487, 130.0, "1s2 2s2 2p6 3s2 3p3",      "Phosphorus is essential to all known life, playing a crucial role in DNA, RNA, and ATP. It exists in several allotropes including white, red, and black. White phosphorus is highly toxic and flammable.",                                ["Fertilisers","Detergents","Match production","DNA and RNA"],                         ["Essential component of DNA and ATP","White phosphorus glows in the dark","Discovered by an alchemist attempting to make gold from urine"],                            "#60A5FA"),
    e("S",  "Sulfur",         16,  32.06,   "nonmetal",              16, 3, "p", "Solid",  2.067,   115.21,  444.61,  2.58, 10.360, 187.0, "1s2 2s2 2p6 3s2 3p4",      "Sulfur is a bright yellow crystalline solid and one of the earliest known elements. It is essential for amino acids and proteins. Sulfuric acid, made from sulfur, is the most widely produced industrial chemical.",                    ["Sulphuric acid production","Rubber vulcanisation","Fertilisers","Fungicides"],       ["Sulphuric acid is the most produced industrial chemical","Burns with a distinctive blue flame","Mentioned in the Bible as brimstone"],                                 "#FACC15"),
    e("Cl", "Chlorine",       17,  35.45,   "halogen",               17, 3, "p", "Gas",    0.00321, -101.5,  -34.04,  3.16, 12.968, 99.0,  "1s2 2s2 2p6 3s2 3p5",      "Chlorine is a yellow-green toxic gas with a pungent odour. It is widely used in water purification and as a bleaching agent. Chlorine compounds play important roles in plastics and pharmaceuticals.",                                   ["Water purification","Bleach","PVC plastic","Pharmaceuticals"],                       ["Used as chemical warfare agent in World War I","Essential for many biological processes","Gives swimming pools their characteristic smell"],                           "#A3E635"),
    e("Ar", "Argon",          18,  39.948,  "noble-gas",             18, 3, "p", "Gas",    0.00178, -189.35, -185.85, 0.00, 15.760, 71.0,  "1s2 2s2 2p6 3s2 3p6",      "Argon is the third most abundant gas in Earth's atmosphere at about 0.93%. It is completely inert and colourless. Argon is used wherever an inert atmosphere is needed to prevent oxidation.",                                          ["Welding (inert shield)","Incandescent bulbs","Double-pane windows","Semiconductors"], ["Third most abundant atmospheric gas","Derives its name from the Greek word for lazy","Emits a blue-violet glow in electrical discharge"],                               "#A78BFA"),
    e("K",  "Potassium",      19,  39.098,  "alkali-metal",          1,  4, "s", "Solid",  0.862,   63.38,   759.0,   0.82, 4.341,  243.0, "1s2 2s2 2p6 3s2 3p6 4s1",  "Potassium is a soft, silvery-white metal that reacts violently with water. It is essential for plant growth and human muscle function. Potassium is the seventh most abundant element in Earth's crust.",                               ["Fertilisers","Gunpowder","Soap production","Medical drips"],                          ["Burns with a lilac-purple flame","Required for nerve impulse transmission","Named from the word potash"],                                                               "#F472B6"),
    e("Ca", "Calcium",        20,  40.078,  "alkaline-earth-metal",  2,  4, "s", "Solid",  1.550,   842.0,   1484.0,  1.00, 6.113,  231.0, "1s2 2s2 2p6 3s2 3p6 4s2",  "Calcium is the fifth most abundant element in Earth's crust and the most abundant metal in the human body. It is crucial for bone and teeth formation. Calcium compounds are used extensively in construction.",                       ["Concrete and cement","Bone health supplements","Steel production","Water treatment"], ["Most abundant metal in the human body","Milk is rich in calcium salts","Essential for muscle contraction and nerve function"],                                          "#34D399"),
    e("Sc", "Scandium",       21,  44.956,  "transition-metal",      3,  4, "d", "Solid",  2.985,   1541.0,  2836.0,  1.36, 6.561,  211.0, "1s2 2s2 2p6 3s2 3p6 3d1 4s2", "Scandium is a soft, silvery-white metallic element. It is relatively rare but widely distributed in the Earth's crust. Scandium-aluminium alloys are used in aerospace and high-performance sports equipment.",                    ["Aerospace alloys","Sports equipment","Metal halide lamps","MRI scanners"],           ["More abundant than silver or lead despite being considered rare","First rare-earth element discovered","Named after Scandinavia"],                                     "#94A3B8"),
    e("Ti", "Titanium",       22,  47.867,  "transition-metal",      4,  4, "d", "Solid",  4.507,   1668.0,  3287.0,  1.54, 6.828,  187.0, "1s2 2s2 2p6 3s2 3p6 3d2 4s2", "Titanium is a lustrous transition metal known for its high strength-to-weight ratio and excellent corrosion resistance. It is as strong as steel but 45% lighter. It is biocompatible, making it ideal for medical implants.",         ["Aerospace","Medical implants","Pigments (TiO2)","Bicycle frames"],                    ["As strong as steel but 45% lighter","Biocompatible for use in medical implants","Named after the Titans of Greek mythology"],                                          "#60A5FA"),
    e("V",  "Vanadium",       23,  50.942,  "transition-metal",      5,  4, "d", "Solid",  6.110,   1910.0,  3407.0,  1.63, 6.746,  179.0, "1s2 2s2 2p6 3s2 3p6 3d3 4s2", "Vanadium is a hard, silvery-grey metal with good structural strength. It is found in many different oxidation states, giving its compounds a variety of vivid colours. It is mainly used as a steel additive to improve hardness.",   ["Steel hardening","Vanadium flow batteries","Catalysts","Superconducting magnets"],   ["One of the few elements with five different oxidation states in aqueous solution","Named after the Norse goddess Vanadis (Freyja)","Used in some ultra-high-speed tools"], "#FB923C"),
    e("Cr", "Chromium",       24,  51.996,  "transition-metal",      6,  4, "d", "Solid",  7.190,   1907.0,  2671.0,  1.66, 6.767,  189.0, "1s2 2s2 2p6 3s2 3p6 3d5 4s1", "Chromium is a hard, shiny, steel-grey metal and the first element of the chromium group. It resists corrosion and tarnishing. The name 'chromium' comes from the Greek word for colour, chroma, because of the vivid colours of its compounds.", ["Stainless steel","Chrome plating","Pigments","Leather tanning"],                ["Gives rubies their red colour and emeralds their green","Key component of stainless steel","Name means colour in Greek"],                                               "#F87171"),
    e("Mn", "Manganese",      25,  54.938,  "transition-metal",      7,  4, "d", "Solid",  7.430,   1246.0,  2061.0,  1.55, 7.434,  197.0, "1s2 2s2 2p6 3s2 3p6 3d5 4s2", "Manganese is a silvery-grey metal similar in appearance to iron. It is essential to iron and steel production and is found in all living organisms. The human body uses manganese as a cofactor for many enzymes.",               ["Steel production","Dry cell batteries","Ceramics pigments","Fertilisers"],           ["Essential trace element in human nutrition","Known to ancient Greeks and Romans","Manganese nodules are found on the ocean floor"],                                     "#FACC15"),
    e("Fe", "Iron",           26,  55.845,  "transition-metal",      8,  4, "d", "Solid",  7.874,   1538.0,  2862.0,  1.83, 7.902,  196.0, "1s2 2s2 2p6 3s2 3p6 3d6 4s2", "Iron is the most common element on Earth by mass and has been used by humans for thousands of years. It is the key component of steel, the most important construction material. The core of the Earth is composed mainly of iron.",  ["Steel and construction","Haemoglobin in blood","Cast iron cookware","Magnets"],     ["Earth's core is mostly iron","Haemoglobin uses iron to carry oxygen in blood","Rusting is a natural electrochemical process"],                                          "#94A3B8"),
    e("Co", "Cobalt",         27,  58.933,  "transition-metal",      9,  4, "d", "Solid",  8.900,   1495.0,  2927.0,  1.88, 7.881,  196.0, "1s2 2s2 2p6 3s2 3p6 3d7 4s2", "Cobalt is a hard, lustrous, silver-grey metal. It is found naturally only in chemically combined form except in small metallic meteoritic forms. Cobalt-60 is an important radioactive isotope used in medical applications.",       ["Lithium-ion batteries","Blue pigments (cobalt blue)","Superalloys","Medical tracers"], ["Cobalt blue has been used since ancient times","Radioactive cobalt-60 is used in cancer treatment","Named from the German kobold meaning goblin"],                     "#60A5FA"),
    e("Ni", "Nickel",         28,  58.693,  "transition-metal",      10, 4, "d", "Solid",  8.908,   1455.0,  2913.0,  1.91, 7.640,  163.0, "1s2 2s2 2p6 3s2 3p6 3d8 4s2", "Nickel is a silvery-white lustrous metal with a slight golden tinge. It is the fourth most common element on Earth by mass and is mainly found in the Earth's mantle. Nickel is highly resistant to oxidation and corrosion.",      ["Stainless steel","Coins","Rechargeable batteries","Electroplating"],                 ["Named from Old German Nickel meaning goblin copper","Found in most meteorites","Earth's core contains substantial amounts of nickel"],                                  "#34D399"),
    e("Cu", "Copper",         29,  63.546,  "transition-metal",      11, 4, "d", "Solid",  8.960,   1085.0,  2562.0,  1.90, 7.726,  140.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s1", "Copper is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. It is one of the few metals that occurs in nature in a directly usable metallic form. Copper has been used by humans for over 10,000 years.", ["Electrical wiring","Plumbing","Coins","Antimicrobial surfaces"],              ["One of the first metals used by humans","Has natural antimicrobial properties","Turns green (verdigris) when exposed to air over time"],                               "#F97316"),
    e("Zn", "Zinc",           30,  65.38,   "transition-metal",      12, 4, "d", "Solid",  7.133,   419.53,  907.0,   1.65, 9.394,  139.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2", "Zinc is a bluish-white, lustrous, diamagnetic metal. It is essential for all forms of life and is the second most abundant trace metal in humans after iron. Zinc is mainly used in galvanising steel to prevent rust.",           ["Galvanising steel","Batteries","Brass alloys","Dietary supplement"],                 ["Essential trace element in over 300 enzymes","Galvanised iron uses a zinc coating to prevent rust","The Statue of Liberty is protected with zinc-based paints"],        "#A3E635"),
    e("Ga", "Gallium",        31,  69.723,  "post-transition-metal", 13, 4, "p", "Solid",  5.910,   29.76,   2229.0,  1.81, 5.999,  136.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1", "Gallium is a soft, silvery metal that melts just above room temperature. It expands upon freezing, unlike most metals. It is used in semiconductors and is combined with arsenic to make gallium arsenide, a key compound in LEDs.", ["LEDs and semiconductors","Solar cells","Thermometers","Medical imaging"],   ["Melts in the palm of your hand at 29.7 °C","Discovered via spectroscopy before it was isolated","Gallium arsenide is central to modern electronics"],                   "#FB923C"),
    e("Ge", "Germanium",      32,  72.630,  "metalloid",             14, 4, "p", "Solid",  5.323,   938.25,  2833.0,  2.01, 7.900,  125.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2", "Germanium is a hard, lustrous, grey-white metalloid that looks like silicon. It is used extensively in infrared optics and fibre optics. Mendeleev predicted its existence before it was discovered, calling it eka-silicon.",    ["Infrared optics","Semiconductors","Fibre optics","Solar cells"],                     ["Predicted by Mendeleev before it was discovered","Used in the first working transistor","Key to night-vision devices"],                                                 "#94A3B8"),
    e("As", "Arsenic",        33,  74.922,  "metalloid",             15, 4, "p", "Solid",  5.727,   817.0,   614.0,   2.18, 9.815,  114.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3", "Arsenic is a metalloid that occurs in many minerals. It is infamous as a poison but has legitimate medical uses. Arsenic compounds are used in wood preservatives and have historically been used as pesticides.",               ["Wood preservatives","Semiconductors","Pesticides (historical)","Cancer treatment"],  ["One of the oldest known poisons","Arsenic was used in Victorian-era green wallpaper pigments causing illness","Its name may come from the Greek word for male or potent"], "#F472B6"),
    e("Se", "Selenium",       34,  78.971,  "nonmetal",              16, 4, "p", "Solid",  4.809,   220.8,   685.0,   2.55, 9.752,  103.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4", "Selenium is a nonmetal with properties between sulfur and tellurium. It is an essential trace element for humans and many animals. Selenium is known for its photoconductive and semiconductive properties.",                     ["Photocopiers","Solar cells","Dietary supplements","Glass manufacturing"],            ["Essential trace element for human health","Photoconductive used in early photocopiers","Named from the Greek word for Moon"],                                          "#FACC15"),
    e("Br", "Bromine",        35,  79.904,  "halogen",               17, 4, "p", "Liquid", 3.100,   -7.2,    58.8,    2.96, 11.814, 114.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5", "Bromine is the only liquid nonmetallic element at room temperature and one of only two elements (with mercury) that are liquid at standard conditions. It has a sharp and unpleasant smell. It is used as a disinfectant and in fire retardants.", ["Flame retardants","Fumigants","Photography","Water purification"],         ["One of only two liquid elements at room temperature","Bromine vapour irritates eyes and throat","Name comes from the Greek for stench"],                               "#F87171"),
    e("Kr", "Krypton",        36,  83.798,  "noble-gas",             18, 4, "p", "Gas",    0.00373, -157.36, -153.22, 0.00, 14.000, 88.0,  "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6", "Krypton is a noble gas that occurs naturally in small amounts in the atmosphere. It emits a bright whitish glow when excited electrically. Krypton fluoride is a powerful ultraviolet laser medium.",                             ["Krypton flashlamps","Laser technology","Lighting","Optical coatings"],               ["Despite its name from Superman, krypton is a real element","Emits brilliant white light in discharge tubes","Was the standard for the definition of the metre"],        "#A78BFA"),
    e("Rb", "Rubidium",       37,  85.468,  "alkali-metal",          1,  5, "s", "Solid",  1.532,   39.31,   688.0,   0.82, 4.177,  265.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1", "Rubidium is a very soft, silvery-white metal in the alkali metal group. It ignites spontaneously in air and reacts violently with water. It is used in atomic clocks and as a getter in vacuum tubes.",              ["Atomic clocks","Research","Fireworks (purple)","Photoelectric cells"],               ["Burns with a deep red flame","Stored under oil to prevent reaction with air","Used to define precise time in atomic clocks"],                                            "#F472B6"),
    e("Sr", "Strontium",      38,  87.62,   "alkaline-earth-metal",  2,  5, "s", "Solid",  2.640,   777.0,   1377.0,  0.95, 5.695,  219.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2", "Strontium is a soft silvery-yellow metallic element that is highly reactive. It burns with a crimson-red flame, making it useful in fireworks and flares. Radioactive strontium-90 is a major product of nuclear fallout.",     ["Fireworks and flares","CRT televisions","Ferrite magnets","Tracer bullets"],         ["Burns with a brilliant crimson flame","Strontium-90 from nuclear tests found in milk during Cold War","Named after Strontian, a village in Scotland"],                "#34D399"),
    e("Y",  "Yttrium",        39,  88.906,  "transition-metal",      3,  5, "d", "Solid",  4.469,   1526.0,  3336.0,  1.22, 6.217,  212.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2", "Yttrium is a silvery-metallic transition metal. It is commonly categorised with the rare earth elements. Yttrium compounds are used in superconductors and as red phosphors in colour television screens.",        ["Red phosphor in TVs","Superconductors","LED lights","Camera lenses"],                ["One of four elements named after the village of Ytterby in Sweden","Used in superconducting ceramics","Its compounds fluoresce red under UV light"],                    "#60A5FA"),
    e("Zr", "Zirconium",      40,  91.224,  "transition-metal",      4,  5, "d", "Solid",  6.511,   1855.0,  4409.0,  1.33, 6.634,  206.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2", "Zirconium is a lustrous, greyish-white, soft, ductile, malleable metal that is solid at room temperature. It is highly resistant to corrosion and is biocompatible. Its primary use is in nuclear reactors.",             ["Nuclear reactor cladding","Surgical instruments","Cubic zirconia jewellery","Ceramics"], ["Highly resistant to neutron bombardment in reactors","Cubic zirconia mimics diamonds","Extremely resistant to corrosion"],                                         "#94A3B8"),
    e("Nb", "Niobium",        41,  92.906,  "transition-metal",      5,  5, "d", "Solid",  8.570,   2477.0,  4744.0,  1.60, 6.759,  198.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1", "Niobium is a light grey crystalline transition metal. It is used mostly in alloys, the largest application being in special high-strength steel. Niobium is a superconductor at low temperatures.",                    ["High-strength steel alloys","Superconducting magnets","Jet engines","Coins"],        ["Superconducting at -264 °C","Used in MRI superconducting magnets","Was originally called Columbium in the USA until 1950"],                                            "#FB923C"),
    e("Mo", "Molybdenum",     42,  95.96,   "transition-metal",      6,  5, "d", "Solid",  10.220,  2623.0,  4639.0,  2.16, 7.092,  190.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1", "Molybdenum is a silvery metal with the sixth-highest melting point of any element. It is used primarily as an alloying agent in steel and cast iron. It is an essential trace element in virtually all forms of life.",    ["High-strength steels","Lubricants","Catalysts","Fertilisers"],                       ["Has one of the highest melting points of all elements","Essential micronutrient for plants and animals","Enzymes using molybdenum are in all organisms"],                "#FACC15"),
    e("Tc", "Technetium",     43,  98.0,    "transition-metal",      7,  5, "d", "Solid",  11.500,  2157.0,  4265.0,  1.90, 7.280,  183.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2", "Technetium was the first synthetically produced element and has no stable isotopes. It is produced in nuclear reactors as a fission product of uranium. Its gamma-ray emitting isotope Tc-99m is widely used in nuclear medicine.",  ["Nuclear medicine imaging","Anti-corrosion agent","Research"],               ["First artificially created element","All isotopes are radioactive","Tc-99m is the most used medical radioisotope in the world"],                                      "#F87171"),
    e("Ru", "Ruthenium",      44,  101.07,  "transition-metal",      8,  5, "d", "Solid",  12.370,  2334.0,  4150.0,  2.20, 7.360,  178.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s1", "Ruthenium is a rare transition metal belonging to the platinum group. It is a hard, white metal that is resistant to acid. It is used as an electrical contact material and to harden platinum and palladium alloys.",       ["Electrical contacts","Platinum and palladium hardening","Catalysis","Solar cells"],  ["One of the platinum group metals","Can be alloyed with titanium to improve corrosion resistance","Named after Ruthenia, the Latin name for Russia"],                     "#A78BFA"),
    e("Rh", "Rhodium",        45,  102.91,  "transition-metal",      9,  5, "d", "Solid",  12.410,  1964.0,  3695.0,  2.28, 7.459,  173.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s1", "Rhodium is a rare, silvery-white, hard corrosion-resistant metal. It is one of the rarest and most valuable precious metals. Rhodium is primarily used in three-way catalytic converters in cars to reduce exhaust emissions.",   ["Catalytic converters","Jewellery plating","Chemical catalysis","Optical instruments"], ["Among the rarest and most expensive metals on Earth","Reflects up to 80% of light","Named from the Greek rhodon meaning rose"],                                       "#34D399"),
    e("Pd", "Palladium",      46,  106.42,  "transition-metal",      10, 5, "d", "Solid",  12.023,  1555.0,  2963.0,  2.20, 8.337,  169.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10",  "Palladium is a rare, lustrous, silvery-white metal discovered in 1803. It has the lowest melting point of the platinum group metals. Palladium can absorb up to 900 times its own volume of hydrogen gas.",                        ["Catalytic converters","Electronics","Jewellery","Hydrogen storage"],                 ["Can absorb 900x its own volume in hydrogen","Named after the asteroid Pallas","Used in the famous room-temperature fusion experiment (though disputed)"],              "#60A5FA"),
    e("Ag", "Silver",         47,  107.87,  "transition-metal",      11, 5, "d", "Solid",  10.490,  961.78,  2162.0,  1.93, 7.576,  165.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1", "Silver is a lustrous, white, precious metal. It has the highest electrical conductivity and highest thermal conductivity of any element. Silver has been used as currency and jewellery for thousands of years.",          ["Jewellery and coins","Electronics","Antimicrobial agents","Solar panels"],            ["Best electrical and thermal conductor of all metals","Has natural antimicrobial properties","Used in mirrors due to high reflectivity"],                              "#94A3B8"),
    e("Cd", "Cadmium",        48,  112.41,  "transition-metal",      12, 5, "d", "Solid",  8.650,   321.07,  767.0,   1.69, 8.994,  161.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2", "Cadmium is a soft, bluish-white metal that is chemically similar to zinc and mercury. It is toxic to humans and is a significant environmental pollutant. It is used in nickel-cadmium batteries and as a pigment.",           ["Rechargeable batteries","Pigments","Nuclear reactor control rods","Plating"],       ["Highly toxic causing itai-itai disease","Cadmium-yellow is a vivid pigment used by artists","Used to absorb neutrons in nuclear reactors"],                             "#FB923C"),
    e("In", "Indium",         49,  114.82,  "post-transition-metal", 13, 5, "p", "Solid",  7.310,   156.6,   2072.0,  1.78, 5.786,  156.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1", "Indium is a very soft, silvery-white post-transition metal with a bright lustre. It is used primarily in the production of transparent conductive coatings for LCD screens. Indium is so soft it can be scratched with a fingernail.", ["LCD touchscreens (ITO)","Solders","Thin-film coatings","Bearings"],       ["Emits a high-pitched squeal when bent (tin cry)","Main use is in flat panel displays","Named after the indigo colour of its spectral lines"],                         "#F472B6"),
    e("Sn", "Tin",            50,  118.71,  "post-transition-metal", 14, 5, "p", "Solid",  7.265,   231.93,  2602.0,  1.96, 7.344,  145.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2", "Tin is a silvery metal that exists in two major allotropes. It resists corrosion and was one of the first metals smelted and used by ancient civilisations. Combined with copper it forms bronze, one of the most important early alloys.", ["Tin cans and plating","Bronze alloy","Solder","Glass manufacturing"],    ["Emits a creaking sound called tin cry when bent","Bronze Age named for the copper-tin alloy","Below 13.2 °C it transforms from white to grey tin"],                    "#94A3B8"),
    e("Sb", "Antimony",       51,  121.76,  "metalloid",             15, 5, "p", "Solid",  6.685,   630.63,  1587.0,  2.05, 8.608,  133.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p3", "Antimony is a lustrous grey metalloid. It has been known since ancient times and was used as a cosmetic kohl. Modern uses include flame retardants, lead storage batteries, and semiconductors.",                              ["Flame retardants","Lead batteries","Semiconductors","Ammunition"],                  ["Used as black kohl eyeliner in ancient Egypt","Expands when solidifying making it ideal for type metal","Symbol Sb from Latin Stibium"],                               "#A3E635"),
    e("Te", "Tellurium",      52,  127.60,  "metalloid",             16, 5, "p", "Solid",  6.232,   449.51,  988.0,   2.10, 9.010,  123.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p4", "Tellurium is a brittle, mildly toxic metalloid. It is chemically related to selenium and sulfur. Tellurium is used in CdTe solar cells, which are among the cheapest and most efficient thin-film solar cells.",               ["Solar cells","Thermoelectric devices","Phase-change memory","Steel alloying"],       ["Second rarest stable element in Earth's crust","Named from the Latin tellus meaning earth","Tellurium breath is its most distinctive sign of exposure"],              "#FACC15"),
    e("I",  "Iodine",         53,  126.90,  "halogen",               17, 5, "p", "Solid",  4.933,   113.7,   184.3,   2.66, 10.451, 198.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p5", "Iodine is a dark-grey crystalline solid at room temperature but sublimes to a violet gas. It is essential for the production of thyroid hormones. Iodine deficiency is one of the most common preventable causes of intellectual disability worldwide.", ["Antiseptics","Thyroid medication","Photography","Iodised salt"],        ["Sublimes directly from solid to gas when heated","Essential for thyroid function","Deficiency is a leading cause of preventable mental retardation"],                  "#A78BFA"),
    e("Xe", "Xenon",          54,  131.29,  "noble-gas",             18, 5, "p", "Gas",    0.00590, -111.75, -108.12, 2.60, 12.130, 108.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6", "Xenon is a dense colourless, odourless noble gas. It was the first noble gas to form a chemical compound. Xenon is used in flash lamps and ion thrusters for spacecraft.",                                                  ["Flash lamps","Ion propulsion in spacecraft","Anaesthesia","Medical imaging"],        ["First noble gas found to form true chemical compounds","Used in ion propulsion engines for deep space probes","Name comes from the Greek xenos meaning stranger"],      "#F87171"),
    e("Cs", "Caesium",        55,  132.91,  "alkali-metal",          1,  6, "s", "Solid",  1.873,   28.44,   671.0,   0.79, 3.894,  298.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s1", "Caesium is a soft, gold-coloured alkali metal. It is the most electropositive stable element and reacts explosively with water. Caesium atomic clocks define the international unit of time, the second.",            ["Atomic clocks","Drilling fluids","Scintillation detectors","Photoelectric cells"],  ["Defines the SI second via atomic transitions","Most reactive alkali metal","Has a beautiful golden-bronze lustre"],                                                     "#F472B6"),
    e("Ba", "Barium",         56,  137.33,  "alkaline-earth-metal",  2,  6, "s", "Solid",  3.510,   727.0,   1897.0,  0.89, 5.212,  253.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s2", "Barium is a soft silvery-white metal. Its compounds emit a green colour in flames, making it useful in fireworks and flares. Barium sulphate is used as a contrast agent in medical X-ray imaging of the gastrointestinal tract.", ["Fireworks (green)","Medical contrast agent","Oil drilling","Pigments"],     ["Burns with a bright green flame","Barium meal used for GI X-rays","Highly reactive with water producing hydrogen gas"],                                                "#34D399"),
    e("La", "Lanthanum",      57,  138.91,  "lanthanide",            3,  6, "f", "Solid",  6.145,   920.0,   3464.0,  1.10, 5.577,  187.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 5d1 6s2", "Lanthanum is a soft, ductile, silvery-white metal. It tarnishes rapidly in air. Lanthanum is used in high-refractive-index glass, flint for lighters, and hydrogen storage.",                                     ["Optical glass","Nickel-metal hydride batteries","Catalysts","Flints"],              ["Tarnishes rapidly in air and water","Used in optical glass for camera lenses","Named from the Greek lanthanein meaning to lie hidden"],                               "#60A5FA"),
    e("Ce", "Cerium",         58,  140.12,  "lanthanide",            3,  6, "f", "Solid",  6.770,   798.0,   3443.0,  1.12, 5.539,  181.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f1 5d1 6s2", "Cerium is the most abundant of the rare earth elements. It is a soft, ductile, silvery-white metal. It is used in catalytic converters, flints, and as a polishing powder for glass.",                      ["Catalytic converters","Lighter flints","Glass polishing","UV filters"],             ["Most abundant rare earth element","Used as flints in cigarette lighters","Named after the dwarf planet Ceres"],                                                         "#94A3B8"),
    e("Pr", "Praseodymium",   59,  140.91,  "lanthanide",            3,  6, "f", "Solid",  6.773,   931.0,   3520.0,  1.13, 5.473,  182.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f3 6s2",   "Praseodymium is a soft, silvery, malleable, and ductile metal valued for its magnetic properties. It creates strong permanent magnets when alloyed with other metals. Praseodymium is also used as a glass colourant.",   ["Neodymium magnets","Protective goggles for glassmakers","Colourant for glass","Aircraft engines"], ["Name means green twin in Greek","Creates brilliant yellow-green glass","Used in goggles to protect glassblowers' eyes"],                                        "#FB923C"),
    e("Nd", "Neodymium",      60,  144.24,  "lanthanide",            3,  6, "f", "Solid",  7.007,   1021.0,  3074.0,  1.14, 5.525,  181.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f4 6s2",   "Neodymium is a soft silvery metal that tarnishes in air. It forms the strongest permanent magnets known. Neodymium magnets are vital in electric motors, wind turbines, and MRI machines.",                             ["Strongest permanent magnets","Wind turbines","Electric vehicles","Lasers"],         ["Neodymium magnets are the strongest permanent magnets known","Used in all electric motors and generators","Name means new twin in Greek"],                            "#F87171"),
    e("Pm", "Promethium",     61,  145.0,   "lanthanide",            3,  6, "f", "Solid",  7.260,   1042.0,  3000.0,  1.13, 5.582,  183.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f5 6s2",   "Promethium is a rare radioactive lanthanide. It does not occur naturally in significant quantities. It is synthesised in nuclear reactors and is used in atomic batteries and as a radiation source.",               ["Nuclear batteries","Luminous paint (historical)","X-ray sources","Research"],       ["Only radioactive rare earth element with no stable isotopes","Named after Prometheus who stole fire from the gods","Virtually no naturally occurring promethium on Earth"], "#A78BFA"),
    e("Sm", "Samarium",       62,  150.36,  "lanthanide",            3,  6, "f", "Solid",  7.520,   1074.0,  1794.0,  1.17, 5.644,  185.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f6 6s2",   "Samarium is a hard silvery metal that slowly oxidises in air. It is used mainly for samarium-cobalt permanent magnets, which are used in applications requiring strong magnets that resist demagnetisation.",          ["Permanent magnets (SmCo)","Cancer treatment","Infrared absorbing glass","Neutron capture"], ["Samarium-cobalt magnets work at higher temperatures than neodymium magnets","Used in targeted alpha therapy for cancer","Named after the mineral samarskite"], "#34D399"),
    e("Eu", "Europium",       63,  151.96,  "lanthanide",            3,  6, "f", "Solid",  5.243,   822.0,   1527.0,  1.20, 5.670,  199.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f7 6s2",   "Europium is the most reactive of the rare earth elements. It is a silvery metal that quickly oxidises in air. Europium compounds fluoresce brilliantly under UV light, making them useful in banknote security features.",   ["Euro banknote security features","LED phosphors","TV screens","Lasers"],    ["Most reactive of the rare earth elements","Makes the red colour in TV screens","EU banknotes contain europium fluorescent compounds as counterfeiting prevention"],  "#60A5FA"),
    e("Gd", "Gadolinium",     64,  157.25,  "lanthanide",            3,  6, "f", "Solid",  7.895,   1313.0,  3273.0,  1.20, 6.150,  196.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f7 5d1 6s2", "Gadolinium is a silvery-white, malleable, and ductile rare earth metal. It is strongly magnetic at low temperatures. Gadolinium chelates are widely used as contrast agents in MRI scans.",                        ["MRI contrast agents","Nuclear reactor shielding","Magneto-caloric refrigeration","Phosphors"], ["Used in MRI contrast dye injected into patients","Exhibits a magnetocaloric effect used in magnetic refrigeration","Named after Finnish chemist Johan Gadolin"],  "#94A3B8"),
    e("Tb", "Terbium",        65,  158.93,  "lanthanide",            3,  6, "f", "Solid",  8.229,   1356.0,  3230.0,  1.20, 5.864,  177.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f9 6s2",   "Terbium is a silvery-white rare earth metal that is malleable, ductile, and soft. Its compounds emit a bright green luminescence. It is used in phosphors for fluorescent lamps and as a dopant in solid state devices.",   ["Green phosphors in displays","Actuators (Terfenol-D)","Fuel cells","Lasers"],      ["Emits brilliant green fluorescence","Used in magneto-strictive alloy Terfenol-D for sonar","One of four elements named after Ytterby, Sweden"],                     "#FB923C"),
    e("Dy", "Dysprosium",     66,  162.50,  "lanthanide",            3,  6, "f", "Solid",  8.550,   1412.0,  2567.0,  1.22, 5.939,  178.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f10 6s2",  "Dysprosium is a rare earth element with a metallic silver lustre. It has the highest magnetic strength of all elements. Small amounts are added to neodymium magnets to preserve their magnetic properties at high temperatures.", ["High-performance magnets","Nuclear control rods","Data storage","Lighting"],    ["Highest magnetic moment of any element","Essential additive for electric vehicle motors","Name comes from Greek dysprositos meaning hard to get at"],              "#F472B6"),
    e("Ho", "Holmium",        67,  164.93,  "lanthanide",            3,  6, "f", "Solid",  8.795,   1474.0,  2700.0,  1.23, 6.022,  176.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f11 6s2",  "Holmium is a relatively soft and malleable silvery-white metal. It has the highest magnetic permeability of any element. It is used in the strongest artificially generated magnetic fields and as a laser medium.",     ["Magnetic pole pieces","Holmium lasers in medicine","Nuclear control rods","Magnets"], ["Has the highest magnetic permeability of any element","Named after Holmia, the Latin name for Stockholm","Used in ultra-high-field magnets"],                       "#34D399"),
    e("Er", "Erbium",         68,  167.26,  "lanthanide",            3,  6, "f", "Solid",  9.066,   1529.0,  2868.0,  1.24, 6.108,  176.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f12 6s2",  "Erbium is a silvery-white solid metal when artificially isolated. Its ions are green-coloured in solution. Erbium is used as an amplifier in fibre-optic communication cables and as a pink colorant in glass and porcelain.", ["Fibre-optic amplifiers","Laser medical applications","Pink glass coloring","Metallurgy"], ["Critical for long-distance fibre optic communication","Imparts a pink colour to glass","One of four elements named after Ytterby, Sweden"],                       "#60A5FA"),
    e("Tm", "Thulium",        69,  168.93,  "lanthanide",            3,  6, "f", "Solid",  9.321,   1545.0,  1950.0,  1.25, 6.184,  190.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f13 6s2",  "Thulium is the least abundant of the naturally occurring lanthanides and is a bright, silvery-grey metal. Thulium-170 is used in portable X-ray devices that require no electricity. It is the second rarest rare earth.",    ["Portable X-ray machines","Lasers","Radiation detection","High-temperature superconductors"], ["Second rarest naturally occurring lanthanide","Named after Thule, an ancient name for northern lands","Used in portable X-ray devices powered by its own radiation"], "#94A3B8"),
    e("Yb", "Ytterbium",      70,  173.04,  "lanthanide",            3,  6, "f", "Solid",  6.965,   824.0,   1196.0,  1.10, 6.254,  222.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 6s2",  "Ytterbium is a silvery, lustrous, malleable rare earth metal that reacts with water and dissolves in acids. It is used in stainless steel alloys and as an optical fibre amplifier. Ytterbium atomic clocks are among the most precise.", ["Optical fibre amplifiers","Atomic clocks","Stainless steel","Research lasers"], ["One of four elements named after Ytterby, Sweden","Used in the most precise atomic clocks","Reacts slowly with air, forming a stable oxide layer"],                "#FB923C"),
    e("Lu", "Lutetium",       71,  174.97,  "lanthanide",            3,  6, "d", "Solid",  9.840,   1663.0,  3402.0,  1.27, 5.426,  175.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d1 6s2", "Lutetium is the last member of the lanthanide series. It is a silvery white metal, the hardest and densest of the lanthanides. It is used in the treatment of neuroendocrine tumours via targeted radionuclide therapy.",    ["Cancer therapy (Lu-177)","Catalysis","Dating meteorites","PET scan detectors"], ["Hardest and densest of the lanthanides","Used in targeted radionuclide cancer therapy","Named after Lutetia, the Latin name for Paris"],                               "#F87171"),
    e("Hf", "Hafnium",        72,  178.49,  "transition-metal",      4,  6, "d", "Solid",  13.310,  2233.0,  4603.0,  1.30, 6.825,  208.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d2 6s2", "Hafnium is a lustrous, silvery-grey metal that closely resembles zirconium. It is used in nuclear reactor control rods because it efficiently absorbs neutrons. Hafnium is also used in superalloys for jet engine components.", ["Nuclear control rods","Superalloys for jet engines","Microchip gate electrodes","Plasma welding"], ["So similar to zirconium that separating them is extremely difficult","Last stable element to be discovered (1923)","Named after Hafnia, the Latin name for Copenhagen"], "#A78BFA"),
    e("Ta", "Tantalum",       73,  180.95,  "transition-metal",      5,  6, "d", "Solid",  16.650,  3017.0,  5458.0,  1.50, 7.549,  200.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d3 6s2", "Tantalum is a rare, hard, blue-grey lustrous transition metal that is highly corrosion-resistant. It is used in the production of capacitors found in virtually all modern electronic devices. It is also biocompatible and is used in surgical implants.", ["Capacitors in electronics","Surgical implants","Cutting tools","Chemical equipment"], ["Capacitors in your phone likely contain tantalum","Has one of the highest melting points of any metal","Mining tantalum has been linked to conflict mineral issues"], "#34D399"),
    e("W",  "Tungsten",       74,  183.84,  "transition-metal",      6,  6, "d", "Solid",  19.250,  3422.0,  5555.0,  2.36, 7.864,  193.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d4 6s2", "Tungsten has the highest melting point of all known elements and the highest boiling point. It is also the most tensile of all metals. Its high melting point makes it ideal for light bulb filaments and cutting tools.",         ["Light bulb filaments","Drill bits and cutting tools","X-ray tubes","Ballast weights"], ["Highest melting point of all elements (3422 °C)","Named wolfram in German, hence symbol W","Used as counterweight in Formula 1 cars"],                             "#60A5FA"),
    e("Re", "Rhenium",        75,  186.21,  "transition-metal",      7,  6, "d", "Solid",  21.020,  3186.0,  5596.0,  1.90, 7.833,  188.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d5 6s2", "Rhenium is a silvery-white heavy transition metal with one of the highest melting points and highest densities of all elements. It is used in high-temperature superalloys for jet engine turbine blades. It is one of the rarest elements in Earth's crust.", ["Jet engine turbine blades","Catalysis","Thermocouples","Electrical contacts"], ["One of the rarest elements in Earth's crust","Has the second highest melting point after tungsten","Named after the Rhine river"],                                    "#94A3B8"),
    e("Os", "Osmium",         76,  190.23,  "transition-metal",      8,  6, "d", "Solid",  22.590,  3033.0,  5012.0,  2.20, 8.438,  185.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d6 6s2", "Osmium is the densest naturally occurring element. It is a hard, brittle, bluish-white transition metal. Osmium tetroxide has a distinctive and penetrating smell and is used as a staining agent in microscopy.",            ["Pen nibs (historical)","Electrical contacts","Fingerprint detection","Microscopy staining"], ["Densest naturally occurring element","Osmium tetroxide has an extremely toxic and penetrating odour","Named from the Greek osme meaning smell"], "#FB923C"),
    e("Ir", "Iridium",        77,  192.22,  "transition-metal",      9,  6, "d", "Solid",  22.560,  2446.0,  4428.0,  2.20, 8.967,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d7 6s2", "Iridium is a very hard, brittle, silvery-white transition metal. It is the second densest element and the most corrosion-resistant metal known. A high concentration of iridium in the geological record at the K-Pg boundary is evidence for the asteroid impact that wiped out the dinosaurs.", ["Spark plug electrodes","Catalysis","Crucibles","Compass bearings"], ["Most corrosion-resistant metal known","High concentration at the K-Pg boundary is evidence of dinosaur-killing asteroid","Second densest natural element"], "#F87171"),
    e("Pt", "Platinum",       78,  195.08,  "transition-metal",      10, 6, "d", "Solid",  21.450,  1768.3,  3825.0,  2.28, 8.959,  177.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d9 6s1", "Platinum is a dense, malleable, ductile precious metal. It is extremely resistant to corrosion and tarnishing. Platinum is used in catalytic converters, jewellery, and as a catalyst in chemical reactions.",                   ["Catalytic converters","Jewellery","Cancer drugs (cisplatin)","Fuel cells"],          ["Does not tarnish or corrode in air","The platinum kilogram standard was used to define a kilogram until 2019","Name comes from the Spanish platina meaning little silver"], "#A78BFA"),
    e("Au", "Gold",           79,  196.97,  "transition-metal",      11, 6, "d", "Solid",  19.300,  1064.18, 2856.0,  2.54, 9.226,  174.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s1", "Gold is a bright, slightly reddish-yellow, dense, soft, malleable, and ductile metal. It is one of the least reactive chemical elements. It has been used as money and jewellery throughout human history.",                ["Jewellery","Electronics","Currency reserves","Medical applications"],               ["Does not tarnish or corrode","Used as currency for thousands of years","All gold on Earth came from ancient asteroid impacts"],                                        "#FBBF24"),
    e("Hg", "Mercury",        80,  200.59,  "transition-metal",      12, 6, "d", "Liquid", 13.534,  -38.83,  356.73,  2.00, 10.438, 171.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2", "Mercury is the only metallic element that is liquid at standard conditions. It is a heavy, silvery metal known since antiquity. Mercury and its compounds are highly toxic, affecting the nervous system.",                ["Thermometers (historical)","Fluorescent lights","Gold extraction","Dental amalgam (historical)"], ["Only metallic element that is liquid at room temperature","The expression mad as a hatter came from hat-makers who used mercury","Formerly called quicksilver"], "#94A3B8"),
    e("Tl", "Thallium",       81,  204.38,  "post-transition-metal", 13, 6, "p", "Solid",  11.850,  304.0,   1473.0,  1.62, 6.108,  156.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p1", "Thallium is a soft grey post-transition metal. It is highly toxic and was historically used as rat poison and insecticide. Thallium compounds are used in optoelectronics and some types of infrared optical systems.",      ["Infrared detectors","Cardiac imaging","Rodenticides (historical)","Semiconductors"], ["Extremely toxic, once used as rat poison","Thallium poisoning was a favourite of mystery writers","Name comes from the Greek thallos meaning green shoot"], "#F472B6"),
    e("Pb", "Lead",           82,  207.20,  "post-transition-metal", 14, 6, "p", "Solid",  11.340,  327.46,  1749.0,  2.33, 7.417,  202.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p2", "Lead is a heavy metal that is denser than most common materials. It is soft and malleable and has a relatively low melting point. Lead was one of the first metals to be smelted and has been used since antiquity.",         ["Lead-acid batteries","Radiation shielding","Bullets and shot","Historical plumbing"], ["Romans used lead pipes for plumbing; chronic poisoning may have contributed to Rome's decline","Dense enough to block X-rays and gamma rays","Most stable heavy element"], "#94A3B8"),
    e("Bi", "Bismuth",        83,  208.98,  "post-transition-metal", 15, 6, "p", "Solid",  9.807,   271.5,   1564.0,  2.02, 7.289,  207.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p3", "Bismuth is a brittle metal with a silvery-white colour when freshly produced. It forms beautiful hopper-shaped crystals with an iridescent oxide surface. Bismuth has the lowest thermal conductivity of all metals except mercury.",   ["Pharmaceuticals (Pepto-Bismol)","Cosmetics","Fire detectors","Alloys"],       ["Forms beautiful staircase-shaped iridescent crystals","Main ingredient in some stomach medicines","Has the lowest toxicity of all heavy metals"],                      "#A3E635"),
    e("Po", "Polonium",       84,  209.0,   "post-transition-metal", 16, 6, "p", "Solid",  9.320,   254.0,   962.0,   2.00, 8.417,  197.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p4", "Polonium is a radioactive element discovered by Marie Curie. It is highly toxic and radioactive with no stable isotopes. Polonium-210, a powerful alpha emitter, was infamously used in the poisoning of Alexander Litvinenko.",   ["Static eliminators","Research triggers in nuclear weapons","Anti-static brushes"],  ["Discovered by Marie Curie and named after her homeland Poland","All isotopes are radioactive","Used in the assassination of Alexander Litvinenko in 2006"],           "#F87171"),
    e("At", "Astatine",       85,  210.0,   "halogen",               17, 6, "p", "Solid",  7.000,   302.0,   337.0,   2.20, 9.317,  202.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p5", "Astatine is the rarest naturally occurring element in the Earth's crust. It is a highly radioactive metalloid or halogen. Its isotope At-211 is being investigated for use in targeted alpha therapy for cancer treatment.",    ["Cancer research (targeted alpha therapy)","Research only"],                          ["Rarest naturally occurring element on Earth","Less than 28 grams exists in Earth's crust at any time","Named from the Greek astatos meaning unstable"],              "#FACC15"),
    e("Rn", "Radon",          86,  222.0,   "noble-gas",             18, 6, "p", "Gas",    0.00973, -71.0,   -61.7,   2.20, 10.748, 220.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6", "Radon is a radioactive noble gas produced by the decay of radium. It is colourless, odourless, and tasteless but highly dangerous. Radon is the second leading cause of lung cancer after smoking.",                          ["Medical therapy (historical)","Research"],                                           ["Second leading cause of lung cancer","Arises naturally from uranium decay in rocks","Can accumulate to dangerous levels in buildings"],                              "#A78BFA"),
    e("Fr", "Francium",       87,  223.0,   "alkali-metal",          1,  7, "s", "Solid",  1.870,   27.0,    677.0,   0.70, 3.940,  348.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 7s1", "Francium is an extremely radioactive metal and one of the rarest naturally occurring elements. It was the last element to be discovered in nature. Due to its instability, very little research has been possible.",            ["Research only"],                                                                    ["Most unstable of the naturally occurring elements","Named after France","At most 30 grams exists in Earth's crust at any time"],                                       "#F472B6"),
    e("Ra", "Radium",         88,  226.0,   "alkaline-earth-metal",  2,  7, "s", "Solid",  5.500,   700.0,   1737.0,  0.90, 5.279,  283.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 7s2", "Radium is a highly radioactive element discovered by Marie and Pierre Curie. It produces radon gas through radioactive decay. Radium was historically used in luminous paints but abandoned due to its health hazards.",       ["Historical luminous paint","Cancer therapy (historical)","Research"],               ["Discovered by Marie and Pierre Curie in 1898","Radium girls painted watch dials with radium paint suffering radiation poisoning","Name comes from the Latin radius meaning ray"], "#34D399"),
    e("Ac", "Actinium",       89,  227.0,   "actinide",              3,  7, "f", "Solid",  10.070,  1050.0,  3200.0,  1.10, 5.170,  215.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 6d1 7s2", "Actinium is a radioactive silvery-white metal that glows blue in the dark due to its intense radioactivity. It is the first of the actinide series. Actinium-225 is being investigated as a therapeutic agent for cancer treatment.", ["Cancer therapy research","Neutron sources","Research"],                  ["Glows a pale blue in the dark due to radioactivity","First element of the actinide series","Its radioactive decay provides heat in radioisotope thermoelectric generators"], "#60A5FA"),
    e("Th", "Thorium",        90,  232.04,  "actinide",              3,  7, "f", "Solid",  11.720,  1750.0,  4788.0,  1.30, 6.307,  206.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 6d2 7s2", "Thorium is a weakly radioactive, bright, silvery metal. It is three times more abundant in Earth's crust than uranium. Thorium is being investigated as a safer alternative nuclear fuel to uranium.",                          ["Nuclear fuel research","Gas lamp mantles","High-temperature alloys","Catalysts"],   ["Three times more abundant than uranium","Used in gas lantern mantles giving their bright white light","Named after the Norse god Thor"],                               "#94A3B8"),
    e("Pa", "Protactinium",   91,  231.04,  "actinide",              3,  7, "f", "Solid",  15.370,  1568.0,  4000.0,  1.50, 5.890,  200.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f2 6d1 7s2", "Protactinium is a dense, silvery, radioactive actinide metal. It is one of the rarest and most expensive naturally occurring elements. It decays to form actinium and has no significant commercial uses.",                 ["Research only","Geochronology"],                                                    ["One of the rarest and most expensive naturally occurring elements","One gram costs about $280,000","Name means before actinium since it decays into actinium"],          "#FB923C"),
    e("U",  "Uranium",        92,  238.03,  "actinide",              3,  7, "f", "Solid",  19.050,  1132.2,  4131.0,  1.38, 6.194,  196.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f3 6d1 7s2", "Uranium is a silvery-white metal that is weakly radioactive. It was the first element used in nuclear fission reactions. Its fission provides energy in nuclear power plants which supply about 10% of the world's electricity.",  ["Nuclear power","Nuclear weapons (historical)","Dating rocks (U-Pb method)","Ballast weights"], ["Powers about 10% of the world's electricity through nuclear fission","Uranium-235 and -238 have a half-life of billions of years","Named after the planet Uranus"], "#F87171"),
    e("Np", "Neptunium",      93,  237.0,   "actinide",              3,  7, "f", "Solid",  20.450,  644.0,   4000.0,  1.36, 6.266,  190.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f4 6d1 7s2", "Neptunium is a radioactive actinide metal. It was the first transuranic element to be synthesised, produced in a nuclear reactor in 1940. Neptunium is primarily used as a precursor for producing plutonium.",             ["Neutron detection","Precursor to plutonium production","Research"],               ["First transuranic element ever produced","Made in nuclear reactors not nature","Named after the planet Neptune following uranium being named after Uranus"],         "#A78BFA"),
    e("Pu", "Plutonium",      94,  244.0,   "actinide",              3,  7, "f", "Solid",  19.816,  639.4,   3228.0,  1.28, 6.060,  187.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f6 7s2",   "Plutonium is a radioactive actinide metal. It is fissile and is used as fuel in nuclear reactors and nuclear weapons. It has six allotropes and its physical and chemical properties are quite complex.",                        ["Nuclear weapons","Nuclear power (MOX fuel)","Pacemaker batteries","Space probes RTGs"], ["Named after the dwarf planet Pluto following neptunium from Neptune","The most complex element — six allotropes with dramatically different densities","Used to power Voyager spacecraft"], "#34D399"),
    e("Am", "Americium",      95,  243.0,   "actinide",              3,  7, "f", "Solid",  13.670,  1176.0,  2607.0,  1.30, 5.991,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f7 7s2",  "Americium is a synthetic radioactive actinide metal. It is produced in nuclear reactors from uranium and plutonium. Most people unknowingly have americium in their homes — it is the ionisation source in smoke detectors.",  ["Smoke detectors (Am-241)","Industrial gauges","Research","Neutron sources"],        ["The ionising source in most smoke detectors","Named after the Americas where it was first synthesised","One of the few radioactive elements with a common household use"], "#60A5FA"),
    e("Cm", "Curium",         96,  247.0,   "actinide",              3,  7, "f", "Solid",  13.510,  1345.0,  3110.0,  1.30, 5.991,  169.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f7 6d1 7s2", "Curium is a hard, dense, silvery metal with a bright lustre. It is intensely radioactive and is produced in nuclear reactors. It is used as a power source for Mars rovers and other space probes.",                    ["Space probe power sources (RTG)","Alpha particle X-ray spectrometers","Research"],  ["Used to power the Mars Science Laboratory instruments","Named after Marie and Pierre Curie","Glows red in the dark due to its own radioactivity"],                    "#94A3B8"),
    e("Bk", "Berkelium",      97,  247.0,   "actinide",              3,  7, "f", "Solid",  14.780,  986.0,   2627.0,  1.30, 6.230,  170.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f9 7s2",  "Berkelium is a radioactive transuranic actinide metal. It has no practical applications outside of scientific research. Berkelium is used as a target material to produce heavier actinides like tennessine.",              ["Scientific research","Production of heavier elements"],                             ["Named after Berkeley, California where it was first synthesised","Only microgram quantities have ever been produced","Used as target to produce tennessine (element 117)"], "#FB923C"),
    e("Cf", "Californium",    98,  251.0,   "actinide",              3,  7, "f", "Solid",  15.100,  900.0,   1472.0,  1.30, 6.300,  186.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f10 7s2", "Californium is a radioactive actinide metal. Cf-252 is an intense neutron source used in nuclear reactor startup, cancer treatment, and gold and silver prospecting. It is one of the few elements that has significant commercial uses.",  ["Neutron startup sources in reactors","Cancer treatment","Detecting gold and silver deposits","Portable neutron generators"], ["Named after California and the University of California","One gram of Cf-252 can produce as many neutrons as a small reactor","Used in rapid analysis of complex geological samples"], "#F87171"),
    e("Es", "Einsteinium",    99,  252.0,   "actinide",              3,  7, "f", "Solid",  8.840,   860.0,   996.0,   1.30, 6.420,  186.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f11 7s2", "Einsteinium is a synthetic transuranic element produced in nuclear reactors. It was first identified in 1952 after the detonation of the first hydrogen bomb. Only nanogram quantities have ever been produced.",            ["Scientific research only"],                                                         ["Named in honour of Albert Einstein","First discovered in the fallout of the Ivy Mike hydrogen bomb test in 1952","Only nanogram quantities have ever been produced"],  "#A78BFA"),
    e("Fm", "Fermium",        100, 257.0,   "actinide",              3,  7, "f", "Solid",  8.690,   1527.0,  0.0,     1.30, 6.500,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f12 7s2", "Fermium is a synthetic transuranic element that was discovered in 1952 in the debris from the first hydrogen bomb explosion. Only picogram quantities have ever been produced. It has no commercial uses.",               ["Scientific research only"],                                                         ["Named in honour of Enrico Fermi, father of the nuclear age","Also discovered in Ivy Mike thermonuclear test debris","Too short-lived to observe its solid properties"],  "#34D399"),
    e("Md", "Mendelevium",    101, 258.0,   "actinide",              3,  7, "f", "Solid",  8.690,   827.0,   0.0,     1.30, 6.580,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f13 7s2", "Mendelevium is a synthetic transuranic element. It was the first element produced one atom at a time. All its known isotopes are radioactive with relatively short half-lives.",                                              ["Scientific research only"],                                                         ["Named in honour of Dmitri Mendeleev, creator of the periodic table","First element to be produced one-atom-at-a-time","Has the rarest and most expensive production of any element"], "#60A5FA"),
    e("No", "Nobelium",       102, 259.0,   "actinide",              3,  7, "f", "Solid",  8.690,   827.0,   0.0,     1.30, 6.650,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 7s2", "Nobelium is a synthetic transuranic element that is highly radioactive. It was first confirmed in 1966. Its most stable isotope has a half-life of about 58 minutes.",                                                       ["Scientific research only"],                                                         ["Named in honour of Alfred Nobel, inventor of dynamite and founder of the Nobel Prizes","Most stable isotope has a half-life of only 58 minutes","Only small amounts have ever been produced"], "#94A3B8"),
    e("Lr", "Lawrencium",     103, 262.0,   "actinide",              3,  7, "d", "Solid",  14.400,  1627.0,  0.0,     1.30, 4.900,  161.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 7s2 7p1", "Lawrencium is a synthetic transuranic element and the last of the actinides. It was first synthesised in 1961. All known isotopes are radioactive and it has no practical applications.",                            ["Scientific research only"],                                                         ["Named in honour of Ernest Lawrence, inventor of the cyclotron","Last element in the actinide series","Very few atoms have ever been produced"],                          "#FB923C"),
    e("Rf", "Rutherfordium",  104, 267.0,   "transition-metal",      4,  7, "d", "Solid",  23.200,  2100.0,  5500.0,  0.00, 6.010,  157.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d2 7s2", "Rutherfordium is a synthetic transactinide element. It was first observed in 1964. As a superheavy element, only a few atoms of rutherfordium have ever been produced.", ["Scientific research only"],                                                         ["Named after Ernest Rutherford, discoverer of the atomic nucleus","One of the transactinide elements beyond lawrencium","Has a half-life of only about 1.3 hours for its most stable isotope"], "#F87171"),
    e("Db", "Dubnium",        105, 268.0,   "transition-metal",      5,  7, "d", "Solid",  29.300,  0.0,     0.0,     0.00, 6.800,  149.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d3 7s2", "Dubnium is a highly radioactive synthetic element. It was first produced in 1968 independently by scientists in the USA and USSR. Its most stable isotope has a half-life of about 28 hours.",               ["Scientific research only"],                                                         ["Named after Dubna, Russia, where a competing team first synthesised it","Subject of a fierce Cold War naming dispute between US and Soviet teams","Only a few atoms have ever been observed"], "#A78BFA"),
    e("Sg", "Seaborgium",     106, 271.0,   "transition-metal",      6,  7, "d", "Solid",  35.000,  0.0,     0.0,     0.00, 7.800,  143.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d4 7s2", "Seaborgium is a synthetic element first synthesised in 1974. It is named after Glenn T. Seaborg, the only person to have an element named after them while still alive. Its most stable isotope has a half-life of about 14 minutes.", ["Scientific research only"],                                                    ["Named after Glenn Seaborg while he was still alive — unprecedented","Seaborg co-discovered ten transuranic elements","Only minute quantities have ever been produced"],  "#34D399"),
    e("Bh", "Bohrium",        107, 272.0,   "transition-metal",      7,  7, "d", "Solid",  37.100,  0.0,     0.0,     0.00, 7.700,  141.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d5 7s2", "Bohrium is a synthetic transactinide element with no known uses outside of research. It was first produced in 1981. Only a few atoms of bohrium have ever been produced and studied.",             ["Scientific research only"],                                                         ["Named in honour of Niels Bohr, who developed the Bohr model of the atom","First produced in Darmstadt, Germany in 1981","Bohrium-270 has a relatively long half-life of 61 seconds"], "#60A5FA"),
    e("Hs", "Hassium",        108, 270.0,   "transition-metal",      8,  7, "d", "Solid",  40.700,  0.0,     0.0,     0.00, 7.600,  134.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d6 7s2", "Hassium is a synthetic transactinide element. It is extremely radioactive and only a few atoms have ever been produced. It was first synthesised in 1984.",                               ["Scientific research only"],                                                         ["Named after Hesse, the German state where it was synthesised","One of the most radioactive elements","Believed to behave like osmium based on periodic table trends"],  "#94A3B8"),
    e("Mt", "Meitnerium",     109, 278.0,   "transition-metal",      9,  7, "d", "Solid",  37.400,  0.0,     0.0,     0.00, 0.000,  129.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d7 7s2", "Meitnerium is a synthetic transactinide element first synthesised in 1982. It has no known uses outside of basic scientific research. Only a few atoms have ever been produced.",               ["Scientific research only"],                                                         ["Named in honour of Lise Meitner, co-discoverer of nuclear fission","One of only a few elements named after a woman","Properties are largely unknown due to rarity"],      "#FB923C"),
    e("Ds", "Darmstadtium",   110, 281.0,   "transition-metal",      10, 7, "d", "Solid",  34.800,  0.0,     0.0,     0.00, 0.000,  128.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d8 7s2", "Darmstadtium is a synthetic transactinide element first produced in 1994. It is extremely unstable with a very short half-life. All of its known isotopes are radioactive.",                          ["Scientific research only"],                                                         ["Named after Darmstadt, Germany, where it was first created","Half-life of its most stable isotope is about 12.7 seconds","Properties predicted to be similar to platinum"], "#F472B6"),
    e("Rg", "Roentgenium",    111, 282.0,   "transition-metal",      11, 7, "d", "Solid",  28.700,  0.0,     0.0,     0.00, 0.000,  121.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d9 7s2", "Roentgenium is a synthetic transactinide element first produced in 1994. It is extremely radioactive with no known practical applications. It is named after Wilhelm Röntgen, who discovered X-rays.",                    ["Scientific research only"],                                                         ["Named after Wilhelm Röntgen, discoverer of X-rays","First created in Darmstadt, Germany","Only a few atoms have ever been produced"],                                  "#34D399"),
    e("Cn", "Copernicium",    112, 285.0,   "transition-metal",      12, 7, "d", "Gas",    14.000,  0.0,     357.0,   0.00, 0.000,  122.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2", "Copernicium is a synthetic transactinide element. Unlike other elements in its column, theoretical calculations predict it may be a gas at room temperature. It was first produced in 1996.",               ["Scientific research only"],                                                         ["Named after astronomer Nicolaus Copernicus","May be the first element in group 12 that is a gas at room temperature","Predicted to behave more like a noble gas than a metal"], "#60A5FA"),
    e("Nh", "Nihonium",       113, 286.0,   "post-transition-metal", 13, 7, "p", "Solid",  16.000,  700.0,   1430.0,  0.00, 0.000,  170.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p1", "Nihonium is a synthetic transactinide element first produced in 2003 at RIKEN in Japan. It is the first element discovered in Asia. It is named after Japan (Nihon in Japanese).",         ["Scientific research only"],                                                         ["First element to be discovered in Asia","Named after Japan in Japanese (Nihon)","Only a few atoms have been observed"],                                                  "#94A3B8"),
    e("Fl", "Flerovium",      114, 289.0,   "post-transition-metal", 14, 7, "p", "Solid",  14.000,  340.0,   420.0,   0.00, 0.000,  180.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p2", "Flerovium is a radioactive synthetic element. It is predicted to have properties similar to noble gases due to relativistic effects. It was first produced in 1998 by bombardment of plutonium with calcium ions.", ["Scientific research only"],                                                        ["Named after Flerov Laboratory of Nuclear Reactions in Dubna, Russia","May behave more like a noble gas than a metal","Among the rarest elements ever created"],          "#FB923C"),
    e("Mc", "Moscovium",      115, 290.0,   "post-transition-metal", 15, 7, "p", "Solid",  13.500,  700.0,   1400.0,  0.00, 0.000,  187.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p3", "Moscovium is a synthetic superheavy element first produced in 2003. It is extremely unstable with a half-life measured in milliseconds. It is named after the Moscow Oblast, Russia.",              ["Scientific research only"],                                                         ["Named after Moscow Oblast, Russia, where it was jointly discovered","Has a half-life of only about 220 milliseconds","Decays rapidly into nihonium"],                     "#F87171"),
    e("Lv", "Livermorium",    116, 293.0,   "post-transition-metal", 16, 7, "p", "Solid",  12.900,  708.5,   1085.0,  0.00, 0.000,  183.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p4", "Livermorium is a synthetic superheavy element first produced in 2000 by a collaboration of American and Russian scientists. It is highly unstable. It is named after Lawrence Livermore National Laboratory.",           ["Scientific research only"],                                                         ["Named after Lawrence Livermore National Laboratory in California","Has a half-life of about 60 milliseconds","Among the heaviest elements ever synthesised"],             "#A78BFA"),
    e("Ts", "Tennessine",     117, 294.0,   "halogen",               17, 7, "p", "Solid",  7.170,   723.0,   1400.0,  0.00, 0.000,  138.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p5", "Tennessine is a synthetic superheavy element first produced in 2010. It is the second heaviest element ever synthesised. It is named after Tennessee, USA, home to several nuclear research facilities.", ["Scientific research only"],                                                        ["Named after the US state of Tennessee","Second heaviest element ever synthesised","May be a metalloid rather than a halogen based on theoretical calculations"],          "#A3E635"),
    e("Og", "Oganesson",      118, 294.0,   "noble-gas",             18, 7, "p", "Gas",    5.000,   52.0,    177.0,   0.00, 0.000,  152.0, "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 4f14 5d10 6s2 6p6 5f14 6d10 7s2 7p6", "Oganesson is the heaviest element currently known and the last element on the periodic table. Despite being in the noble gas group, relativistic calculations suggest it may be a solid. It was first produced in 2002.", ["Scientific research only"],                                                         ["Heaviest element on the periodic table","Named after nuclear physicist Yuri Oganessian, who is still alive","Despite being in the noble gas group, it is predicted to be a solid"], "#A78BFA"),
  ] };

  // ── public API ─────────────────────────────────────────────────────────────
  public func init() : ElementMap {
    Map.empty<Text, Element>()
  };

  func seedIfEmpty(elements : ElementMap) {
    if (elements.isEmpty()) {
      for (el in allElements().values()) {
        elements.add(el.symbol, el);
      };
    };
  };

  public func getAll(elements : ElementMap) : [Element] {
    seedIfEmpty(elements);
    let iter = elements.values();
    iter.toArray()
  };

  public func getBySymbol(elements : ElementMap, symbol : Text) : ?Element {
    seedIfEmpty(elements);
    elements.get(symbol.toUpper())
  };

  public func search(elements : ElementMap, searchTerm : Text) : [Element] {
    seedIfEmpty(elements);
    if (searchTerm == "") return [];
    let lower = searchTerm.toLower();
    let allArr = elements.values().toArray();
    allArr.filter<Element>(func(el) {
      let nameMatch = el.name.toLower().startsWith(#text lower);
      let symbolMatch = el.symbol.toLower() == lower;
      let numMatch = el.atomicNumber.toText() == searchTerm;
      nameMatch or symbolMatch or numMatch
    })
  };
};
