import Types "../types/quiz";

module {
  public type QuizQuestion = Types.QuizQuestion;

  func q(id:Text, questionType:Text, question:Text, options:[Text], correctAnswer:Text, explanation:Text, difficulty:Text, topic:Text) : QuizQuestion =
    { id; questionType; question; options; correctAnswer; explanation; difficulty; topic };

  func allQuestions() : [QuizQuestion] { [
    // ── Element Identification ─────────────────────────────────────────────
    q("ei-01","identify-element","Which element has the symbol 'Au'?",["Silver","Gold","Aluminium","Argon"],"Gold","Au from Latin Aurum = gold.","easy","element-identification"),
    q("ei-02","identify-element","What is the symbol for Sodium?",["So","Sd","Na","N"],"Na","Na from Latin Natrium.","easy","element-identification"),
    q("ei-03","identify-element","Which element has atomic number 1?",["Helium","Hydrogen","Carbon","Oxygen"],"Hydrogen","Hydrogen is element 1.","easy","element-identification"),
    q("ei-04","identify-element","What element has symbol 'Fe'?",["Fluorine","Fermium","Iron","Francium"],"Iron","Fe from Latin Ferrum.","easy","element-identification"),
    q("ei-05","identify-element","Which noble gas has atomic number 2?",["Neon","Argon","Helium","Krypton"],"Helium","Helium (He) is element 2.","easy","element-identification"),
    q("ei-06","identify-element","Chemical symbol for Mercury?",["Mr","Me","Hg","Mc"],"Hg","Hg from Hydrargyrum (liquid silver).","medium","element-identification"),
    q("ei-07","identify-element","Which element has symbol 'W'?",["Tin","Tungsten","Thallium","Tellurium"],"Tungsten","W from German Wolfram.","medium","element-identification"),
    q("ei-08","identify-element","Which non-metallic element is liquid at room temperature?",["Phosphorus","Bromine","Gallium","Caesium"],"Bromine","Bromine is the only non-metallic liquid at room temperature.","medium","element-identification"),
    q("ei-09","identify-element","Element making up ~78% of Earth's atmosphere?",["Oxygen","Argon","Nitrogen","CO2"],"Nitrogen","N2 is ~78% of atmosphere.","easy","element-identification"),
    q("ei-10","identify-element","Most electronegative element?",["Oxygen","Chlorine","Fluorine","Nitrogen"],"Fluorine","F has electronegativity 3.98 (Pauling).","medium","element-identification"),
    q("ei-11","identify-element","Element with highest melting point?",["Iron","Tungsten","Platinum","Osmium"],"Tungsten","W melts at 3422°C.","hard","element-identification"),
    q("ei-12","identify-element","Which element has symbol 'Pb'?",["Phosphorus","Platinum","Lead","Polonium"],"Lead","Pb from Latin Plumbum.","easy","element-identification"),
    q("ei-13","identify-element","Only non-metal conducting electricity?",["Sulfur","Phosphorus","Graphite","Silicon"],"Graphite","Graphite has delocalised electrons.","medium","element-identification"),
    // ── State of Matter ─────────────────────────────────────────────────────
    q("sm-01","identify-element","Which is a gas at room temperature?",["Bromine","Mercury","Chlorine","Gallium"],"Chlorine","Cl2 boils at -34°C.","easy","state-of-matter"),
    q("sm-02","identify-element","Boiling point of water at standard pressure?",["90°C","95°C","100°C","105°C"],"100°C","Water boils at 100°C/373K.","easy","state-of-matter"),
    q("sm-03","identify-element","Metal melting just above room temperature at ~29.7°C?",["Mercury","Gallium","Caesium","Tin"],"Gallium","Ga melts at 29.76°C.","medium","state-of-matter"),
    q("sm-04","identify-element","Solid at room temperature among these?",["Radon","Krypton","Iodine","Xenon"],"Iodine","I2 melts at 113.7°C.","easy","state-of-matter"),
    // ── Periodic Trends ─────────────────────────────────────────────────────
    q("pt-01","property-match","Across a period (L→R), atomic radius?",["Increases","Decreases","Same","First increases then decreases"],"Decreases","Nuclear charge increases, pulling electrons closer.","medium","periodic-trends"),
    q("pt-02","property-match","Down a group, ionisation energy?",["Increases","Decreases","Same","Alternates"],"Decreases","Outer electrons further and more shielded.","medium","periodic-trends"),
    q("pt-03","property-match","Highest first ionisation energy?",["Hydrogen","Helium","Fluorine","Neon"],"Helium","He electrons very close, no shielding.","hard","periodic-trends"),
    q("pt-04","property-match","Down Group 1, reactivity?",["Decreases","Increases","Same","Unpredictable"],"Increases","Outer electron easier to lose.","medium","periodic-trends"),
    q("pt-05","property-match","Largest atomic radius in period 2?",["Carbon","Neon","Lithium","Fluorine"],"Lithium","Li has fewest protons in period 2.","medium","periodic-trends"),
    q("pt-06","property-match","Down Group 17, halogen reactivity?",["Increases","Decreases","Same","Doubles"],"Decreases","Harder to attract electrons further from nucleus.","medium","periodic-trends"),
    q("pt-07","property-match","What increases down a group for metals?",["IE","Electronegativity","Atomic radius","Melting point"],"Atomic radius","New electron shells added.","easy","periodic-trends"),
    // ── Reaction Prediction ─────────────────────────────────────────────────
    q("rp-01","predict-reaction","Products of sodium + water?",["Na2O+H2O","NaOH+H2","NaCl+O2","Na2CO3+H2"],"NaOH+H2","2Na+2H2O→2NaOH+H2.","easy","reaction-prediction"),
    q("rp-02","predict-reaction","Gas produced when metal reacts with acid?",["Oxygen","Hydrogen","CO2","Nitrogen"],"Hydrogen","Metals above H displace H2 from acid.","easy","reaction-prediction"),
    q("rp-03","predict-reaction","Acid + base produces?",["Oxide+water","Salt+water","Gas+water","Acid+base"],"Salt+water","Neutralisation: Acid+Base→Salt+Water.","easy","reaction-prediction"),
    q("rp-04","predict-reaction","Which metal reacts with cold water?",["Copper","Iron","Calcium","Gold"],"Calcium","Ca+2H2O→Ca(OH)2+H2.","medium","reaction-prediction"),
    q("rp-05","predict-reaction","Iron placed in CuSO4 solution?",["No reaction","Fe dissolves, Cu deposits","Cu dissolves, Fe deposits","Both dissolve"],"Fe dissolves, Cu deposits","Fe+CuSO4→FeSO4+Cu; Fe more reactive.","medium","reaction-prediction"),
    q("rp-06","predict-reaction","CH4+2O2→CO2+2H2O is what type?",["Decomposition","Synthesis","Combustion","Displacement"],"Combustion","Hydrocarbon burning in O2.","easy","reaction-prediction"),
    q("rp-07","predict-reaction","CaCO3 heated strongly?",["Melts","Decomposes to CaO+CO2","Combines with O2","Reacts with water"],"Decomposes to CaO+CO2","Thermal decomposition of limestone.","medium","reaction-prediction"),
    q("rp-08","predict-reaction","Can copper displace iron from FeSO4?",["Yes, Cu more reactive","No, Fe more reactive","Yes at high temp","No, neither reacts"],"No, Fe more reactive","Fe above Cu in reactivity series.","medium","reaction-prediction"),
    q("rp-09","predict-reaction","Gas when carbonate reacts with acid?",["Hydrogen","Oxygen","CO2","SO2"],"CO2","Acid+Carbonate→Salt+Water+CO2.","easy","reaction-prediction"),
    // ── Property Match ──────────────────────────────────────────────────────
    q("pm-01","property-match","Best conductor of electricity?",["Copper","Gold","Silver","Aluminium"],"Silver","Ag has highest electrical conductivity.","medium","property-match"),
    q("pm-02","property-match","Hardest natural substance?",["Quartz","Diamond","Ruby","Sapphire"],"Diamond","Diamond rates 10 on Mohs scale.","easy","property-match"),
    q("pm-03","property-match","Nuclear reactor control rod material?",["Uranium","Lead","Boron or Hafnium","Iron"],"Boron or Hafnium","B and Hf absorb neutrons well.","hard","property-match"),
    q("pm-04","property-match","Rubies red, emeralds green due to?",["Iron","Chromium","Nickel","Cobalt"],"Chromium","Cr impurities cause both colours.","hard","property-match"),
    q("pm-05","property-match","Most abundant element in human body by mass?",["Carbon","Hydrogen","Nitrogen","Oxygen"],"Oxygen","O is ~65% of body mass.","medium","property-match"),
    q("pm-06","property-match","Catalytic converter metals?",["Pt and Rh","Au and Ag","Ni and Fe","Cu and Zn"],"Pt and Rh","Pt group metals convert exhaust gases.","medium","property-match"),
    // ── True/False ──────────────────────────────────────────────────────────
    q("tf-01","true-false","Al is the most abundant metal in Earth's crust.",["True","False"],"True","Al ~8% of Earth's crust.","easy","true-false"),
    q("tf-02","true-false","Noble gases commonly form chemical compounds.",["True","False"],"False","Noble gases have full outer shells; very unreactive.","easy","true-false"),
    q("tf-03","true-false","Hydrogen is the most abundant element in the universe.",["True","False"],"True","H ~75% of all normal matter.","easy","true-false"),
    q("tf-04","true-false","All metals are solid at room temperature.",["True","False"],"False","Mercury is liquid at room temp.","medium","true-false"),
    q("tf-05","true-false","Isotopes have same protons, different neutrons.",["True","False"],"True","Same atomic number, different mass number.","medium","true-false"),
    q("tf-06","true-false","Gold does not react with any acid.",["True","False"],"False","Au dissolves in aqua regia.","medium","true-false"),
    q("tf-07","true-false","Diamond and graphite are both forms of carbon.",["True","False"],"True","Both are allotropes of C.","easy","true-false"),
    q("tf-08","true-false","Periodic table arranged by increasing atomic mass.",["True","False"],"False","Arranged by atomic number.","medium","true-false"),

    // ── NEW MCQ: Periodic Table ──────────────────────────────────────────────
    q("mcq-01","mcq","How many elements are in the modern periodic table?",["108","112","118","120"],"118","118 elements have been confirmed and named.","easy","periodic-table"),
    q("mcq-02","mcq","Elements in the same group have the same number of?",["Neutrons","Protons","Valence electrons","Electron shells"],"Valence electrons","Group number = valence electrons (main group).","easy","periodic-table"),
    q("mcq-03","mcq","Which block contains the transition metals?",["s-block","p-block","d-block","f-block"],"d-block","d-block: groups 3–12.","easy","periodic-table"),
    q("mcq-04","mcq","Period number indicates?",["Group","Valence electrons","Number of electron shells","Atomic mass"],"Number of electron shells","Period = number of occupied electron shells.","easy","periodic-table"),
    q("mcq-05","mcq","Group 18 elements are called?",["Halogens","Alkali metals","Noble gases","Alkaline earth metals"],"Noble gases","Group 18 = He, Ne, Ar, Kr, Xe, Rn.","easy","periodic-table"),
    q("mcq-06","mcq","Lanthanides and actinides belong to which block?",["s","p","d","f"],"f","f-block: lanthanides (4f) and actinides (5f).","medium","periodic-table"),
    q("mcq-07","mcq","Which element is in period 3, group 1?",["Li","Na","K","Rb"],"Na","Na is period 3, group 1 alkali metal.","easy","periodic-table"),
    q("mcq-08","mcq","Which group contains alkaline earth metals?",["1","2","17","18"],"2","Group 2: Be, Mg, Ca, Sr, Ba, Ra.","easy","periodic-table"),
    q("mcq-09","mcq","Atomic number of Chlorine?",["15","16","17","18"],"17","Cl has 17 protons.","easy","periodic-table"),
    q("mcq-10","mcq","Which period contains elements Na through Ar?",["2","3","4","5"],"3","Na(11) to Ar(18) are in period 3.","easy","periodic-table"),

    // ── NEW MCQ: Atomic Structure ────────────────────────────────────────────
    q("mcq-11","mcq","Who proposed the nuclear model of the atom?",["Thomson","Bohr","Rutherford","Dalton"],"Rutherford","Rutherford's gold-foil experiment (1911).","easy","atomic-structure"),
    q("mcq-12","mcq","Maximum electrons in the n=2 shell?",["2","8","18","32"],"8","2n² = 2×4 = 8.","easy","atomic-structure"),
    q("mcq-13","mcq","Subshell with 5 orbitals?",["s","p","d","f"],"d","d has 5 orbitals (ml = -2 to +2).","medium","atomic-structure"),
    q("mcq-14","mcq","Electron configuration of Na (Z=11)?",["2,8,1","2,9","2,8,2","1,8,2"],"2,8,1","K=2, L=8, M=1.","easy","atomic-structure"),
    q("mcq-15","mcq","Which quantum number describes orbital shape?",["n","l","ml","ms"],"l","Azimuthal quantum number l.","medium","atomic-structure"),
    q("mcq-16","mcq","Pauli Exclusion Principle states?",["Electrons fill lowest energy first","No two e- have same 4 QNs","Half-fill before pairing","Orbitals of same energy are equivalent"],"No two e- have same 4 QNs","Each electron unique set of n,l,ml,ms.","medium","atomic-structure"),
    q("mcq-17","mcq","Hund's rule states electrons in degenerate orbitals?",["Pair before occupying new","Occupy singly before pairing","Fill highest energy first","Ignore spin"],"Occupy singly before pairing","Maximum spin multiplicity (Hund's rule).","medium","atomic-structure"),
    q("mcq-18","mcq","The Bohr model works best for?",["All atoms","Multi-electron atoms","Hydrogen atom","Molecules"],"Hydrogen atom","Bohr's quantised orbits work for H-like species.","medium","atomic-structure"),
    q("mcq-19","mcq","Mass number = ?",["Protons only","Neutrons only","Protons + Neutrons","Protons + Electrons"],"Protons + Neutrons","A = Z + N.","easy","atomic-structure"),
    q("mcq-20","mcq","Which particle has negligible mass?",["Proton","Neutron","Electron","Nucleus"],"Electron","Electron mass ~1/1836 of proton.","easy","atomic-structure"),

    // ── NEW MCQ: Chemical Bonding ────────────────────────────────────────────
    q("mcq-21","mcq","NaCl is an example of?",["Covalent bond","Ionic bond","Metallic bond","Hydrogen bond"],"Ionic bond","Na+ and Cl- electrostatic attraction.","easy","bonding"),
    q("mcq-22","mcq","Bond formed by sharing electrons?",["Ionic","Covalent","Metallic","Van der Waals"],"Covalent","Shared electron pairs form covalent bonds.","easy","bonding"),
    q("mcq-23","mcq","VSEPR shape of H2O?",["Linear","Bent","Trigonal planar","Tetrahedral"],"Bent","2 bonding pairs + 2 lone pairs → bent.","medium","bonding"),
    q("mcq-24","mcq","VSEPR shape of CO2?",["Bent","Linear","Trigonal","Tetrahedral"],"Linear","2 double bonds, no lone pairs → linear.","easy","bonding"),
    q("mcq-25","mcq","Bond angle in CH4?",["90°","109.5°","120°","180°"],"109.5°","Tetrahedral geometry.","easy","bonding"),
    q("mcq-26","mcq","Hybridisation of carbon in ethene (C2H4)?",["sp","sp2","sp3","sp3d"],"sp2","Double bond: sp2, one p orbital for π.","medium","bonding"),
    q("mcq-27","mcq","Hybridisation of carbon in ethyne (C2H2)?",["sp","sp2","sp3","sp3d"],"sp","Triple bond: sp hybridised.","medium","bonding"),
    q("mcq-28","mcq","Strongest intermolecular force?",["London dispersion","Dipole-dipole","Hydrogen bond","Ion-dipole"],"Hydrogen bond","H-bond ~5–40 kJ/mol, strongest IMF.","medium","bonding"),
    q("mcq-29","mcq","Which molecule has a dipole moment of zero?",["HCl","H2O","CO2","NH3"],"CO2","Linear, equal and opposite dipoles cancel.","medium","bonding"),
    q("mcq-30","mcq","Bond order in N2?",["1","2","3","0"],"3","N≡N triple bond; bond order = 3.","medium","bonding"),

    // ── NEW MCQ: Thermochemistry ─────────────────────────────────────────────
    q("mcq-31","mcq","ΔH for exothermic reaction is?",["Positive","Negative","Zero","Unpredictable"],"Negative","System releases heat → ΔH < 0.","easy","thermochemistry"),
    q("mcq-32","mcq","Standard enthalpy of formation of a pure element is?",["100 kJ/mol","Undefined","-100 kJ/mol","0 kJ/mol"],"0 kJ/mol","Reference state: ΔHf° = 0 for elements.","easy","thermochemistry"),
    q("mcq-33","mcq","Hess's Law states?",["ΔH depends on path","ΔH independent of path","Only for exothermic","Only for gases"],"ΔH independent of path","Enthalpy is a state function.","medium","thermochemistry"),
    q("mcq-34","mcq","Bond enthalpy is the energy to?",["Form a bond","Break a bond","Transfer electrons","Remove a proton"],"Break a bond","Bond dissociation energy = energy to break bond.","easy","thermochemistry"),
    q("mcq-35","mcq","Entropy (S) measures?",["Enthalpy","Disorder/randomness","Gibbs energy","Heat capacity"],"Disorder/randomness","S measures degree of disorder.","easy","thermochemistry"),
    q("mcq-36","mcq","Gibbs free energy ΔG = ?",["ΔH - TΔS","ΔH + TΔS","ΔS - TΔH","TΔH - ΔS"],"ΔH - TΔS","ΔG = ΔH - TΔS (Gibbs equation).","medium","thermochemistry"),
    q("mcq-37","mcq","Spontaneous reaction requires?",["ΔG > 0","ΔG < 0","ΔG = 0","ΔH < 0 only"],"ΔG < 0","Negative ΔG = spontaneous.","medium","thermochemistry"),
    q("mcq-38","mcq","At equilibrium, ΔG = ?",["Positive","Negative","Zero","Undefined"],"Zero","At equilibrium, ΔG = 0.","medium","thermochemistry"),
    q("mcq-39","mcq","Lattice enthalpy is energy to?",["Form ionic solid from gaseous ions","Break covalent bonds","Vaporise a liquid","Dissolve a solid"],"Form ionic solid from gaseous ions","ΔHL = energy releasing ions → lattice.","medium","thermochemistry"),
    q("mcq-40","mcq","Combustion of carbon: C + O2 → CO2, ΔH = -394 kJ. This is?",["Endothermic","Exothermic","Neutral","Activation"],"Exothermic","ΔH negative → exothermic.","easy","thermochemistry"),

    // ── NEW MCQ: Organic Basics ──────────────────────────────────────────────
    q("mcq-41","mcq","General formula of alkanes?",["CnH2n","CnH2n+2","CnH2n-2","CnHn"],"CnH2n+2","Alkanes: saturated, CnH2n+2.","easy","organic"),
    q("mcq-42","mcq","Functional group of alcohols?",["-COOH","-OH","-CHO","-NH2"],"−OH","Hydroxyl group -OH in alcohols.","easy","organic"),
    q("mcq-43","mcq","IUPAC name for CH3CH2OH?",["Methanol","Ethanol","Propanol","Butanol"],"Ethanol","2-carbon chain with -OH = ethanol.","easy","organic"),
    q("mcq-44","mcq","Which reaction converts alkene to alkane?",["Oxidation","Hydrogenation","Halogenation","Cracking"],"Hydrogenation","CnH2n + H2 → CnH2n+2 (Ni catalyst).","easy","organic"),
    q("mcq-45","mcq","Benzene molecular formula?",["C6H12","C6H6","C6H10","C6H8"],"C6H6","Benzene ring: 6C 6H.","easy","organic"),
    q("mcq-46","mcq","Carboxylic acids contain?",["−OH","−CHO","−COOH","−CO−"],"−COOH","−COOH = carboxyl group.","easy","organic"),
    q("mcq-47","mcq","Isomers have the same?",["Physical properties","Molecular formula","Structural formula","Boiling point"],"Molecular formula","Isomers: same formula, different structure.","medium","organic"),
    q("mcq-48","mcq","Type of isomerism in but-1-ene and but-2-ene?",["Optical","Geometric","Chain","Positional"],"Positional","Double bond at different position.","medium","organic"),
    q("mcq-49","mcq","SN2 reaction involves?",["Carbocation intermediate","One-step bimolecular mechanism","Free radical","Two-step mechanism"],"One-step bimolecular mechanism","SN2: backside attack, inversion, rate=k[R][Nu].","hard","organic"),
    q("mcq-50","mcq","Which is a primary alcohol?",["(CH3)3COH","(CH3)2CHOH","CH3CH2OH","CH2=CHOH"],"CH3CH2OH","Ethanol: OH on primary carbon.","medium","organic"),

    // ── NEW MCQ: Electrochemistry ─────────────────────────────────────────────
    q("mcq-51","mcq","In a galvanic cell, oxidation occurs at?",["Cathode","Anode","Electrolyte","Salt bridge"],"Anode","Anode = oxidation (OIL RIG).","easy","electrochemistry"),
    q("mcq-52","mcq","Standard hydrogen electrode potential?",["1V","0.5V","0V","-1V"],"0V","SHE reference: E°= 0.00 V.","easy","electrochemistry"),
    q("mcq-53","mcq","Faraday's constant ≈ ?",["9.65×104 C/mol","9.65×103 C/mol","6.02×1023","1.6×10-19 C"],"9.65×104 C/mol","F = 96500 C/mol.","medium","electrochemistry"),
    q("mcq-54","mcq","EMF of cell = ?",["E°cathode - E°anode","E°anode - E°cathode","E°cathode + E°anode","E°cathode × E°anode"],"E°cathode - E°anode","E°cell = E°cathode - E°anode.","medium","electrochemistry"),
    q("mcq-55","mcq","Nernst equation used for?",["Standard conditions only","Non-standard conditions","Solids only","Gases only"],"Non-standard conditions","Nernst: E = E° - (RT/nF)lnQ.","medium","electrochemistry"),
    q("mcq-56","mcq","Electrolysis of dilute H2SO4: gas at cathode?",["O2","H2","SO2","H2SO4"],"H2","2H+ + 2e- → H2 at cathode.","easy","electrochemistry"),
    q("mcq-57","mcq","In electrolysis, the negative electrode is called?",["Anode","Cation","Cathode","Electrolyte"],"Cathode","Cathode = negative in electrolytic cell.","easy","electrochemistry"),
    q("mcq-58","mcq","Specific conductance unit?",["S","Ω","S/m","S·m2/mol"],"S/m","κ (kappa) in S/m or S/cm.","medium","electrochemistry"),
    q("mcq-59","mcq","Daniel cell uses which electrolyte?",["H2SO4","NaCl","ZnSO4 and CuSO4","HCl"],"ZnSO4 and CuSO4","Zn|ZnSO4||CuSO4|Cu.","medium","electrochemistry"),
    q("mcq-60","mcq","Oxidation state of Mn in KMnO4?",["+2","+4","+7","+6"],"Oxidation state +7","K(+1) + Mn + 4O(-2) = 0 → Mn = +7.","medium","electrochemistry"),

    // ── NEW MCQ: Mole Concept ────────────────────────────────────────────────
    q("mcq-61","mcq","1 mole contains how many entities?",["6.022×1022","6.022×1023","6.022×1024","6.022×1020"],"6.022×1023","Avogadro's number NA = 6.022×10²³.","easy","mole-concept"),
    q("mcq-62","mcq","Molar mass of H2O?",["16 g/mol","18 g/mol","20 g/mol","17 g/mol"],"18 g/mol","2×1 + 16 = 18 g/mol.","easy","mole-concept"),
    q("mcq-63","mcq","Moles of 44g CO2? (M=44)",["0.5","1","2","44"],"1","n = m/M = 44/44 = 1 mol.","easy","mole-concept"),
    q("mcq-64","mcq","Volume of 1 mol ideal gas at STP (0°C, 1 atm)?",["11.2 L","22.4 L","44.8 L","2.24 L"],"22.4 L","Molar volume at STP = 22.4 L.","easy","mole-concept"),
    q("mcq-65","mcq","Empirical formula: simplest whole-number ratio?",["Molecular formula","Empirical formula","Structural formula","Condensed formula"],"Empirical formula","Empirical = simplest ratio.","easy","mole-concept"),
    q("mcq-66","mcq","Limiting reagent is the one that?",["Is in excess","Gets fully consumed first","Has highest molar mass","Is added last"],"Gets fully consumed first","Limiting reagent determines product amount.","easy","mole-concept"),
    q("mcq-67","mcq","Molarity (M) = ?",["moles/L solution","moles/kg solvent","g/L","g/mol"],"moles/L solution","Molarity = mol solute / L solution.","easy","mole-concept"),
    q("mcq-68","mcq","Molality (m) = ?",["mol/L","mol/kg solvent","g/mL","mol/mol"],"mol/kg solvent","Molality = mol solute / kg solvent.","medium","mole-concept"),
    q("mcq-69","mcq","Percentage yield = ?",["actual/theoretical×100","theoretical/actual×100","mole ratio×100","mass/moles×100"],"actual/theoretical×100","% yield = (actual÷theoretical)×100.","easy","mole-concept"),
    q("mcq-70","mcq","Normality = ?",["mol/L","equiv/L","g/L","mol/kg"],"equiv/L","N = gram equivalents / L.","medium","mole-concept"),

    // ── NEW MCQ: Chemical Equilibrium ────────────────────────────────────────
    q("mcq-71","mcq","At equilibrium, reaction rates are?",["Forward > reverse","Reverse > forward","Both zero","Forward = reverse"],"Forward = reverse","Dynamic equilibrium: equal rates.","easy","equilibrium"),
    q("mcq-72","mcq","Le Chatelier's Principle: if pressure increases on N2+3H2⇌2NH3, equilibrium shifts?",["Left","Right","No shift","Depends on T"],"Right","Fewer moles gas (2) on right → shifts right.","medium","equilibrium"),
    q("mcq-73","mcq","Kc expression for aA+bB⇌cC+dD?",["[C]c[D]d/[A]a[B]b","[A]a[B]b/[C]c[D]d","[C][D]/[A][B]","Products × Reactants"],"[C]c[D]d/[A]a[B]b","Kc = products/reactants raised to stoich powers.","medium","equilibrium"),
    q("mcq-74","mcq","Large Kc value means?",["Mostly reactants","Mostly products","Slow reaction","No equilibrium"],"Mostly products","Kc >>1: equilibrium favours products.","medium","equilibrium"),
    q("mcq-75","mcq","Addition of catalyst to equilibrium reaction?",["Shifts right","Shifts left","No shift in position","Increases Kc"],"No shift in position","Catalyst speeds both directions equally.","medium","equilibrium"),

    // ── NEW MCQ: Acids, Bases & pH ────────────────────────────────────────────
    q("mcq-76","mcq","pH of pure water at 25°C?",["0","7","14","10"],"7","[H+] = [OH-] = 10-7 M → pH = 7.","easy","acids-bases"),
    q("mcq-77","mcq","Brønsted-Lowry acid is?",["Proton donor","Proton acceptor","Electron donor","Electron acceptor"],"Proton donor","BL acid donates H+.","easy","acids-bases"),
    q("mcq-78","mcq","Lewis base is?",["Proton donor","Proton acceptor","Electron pair donor","Electron pair acceptor"],"Electron pair donor","Lewis base donates electron pair.","medium","acids-bases"),
    q("mcq-79","mcq","Buffer resists change in?",["Temperature","Pressure","pH","Concentration"],"pH","Buffer = weak acid/conjugate base pair.","easy","acids-bases"),
    q("mcq-80","mcq","Henderson-Hasselbalch: pH = ?",["pKa + log([A-]/[HA])","pKa - log([A-]/[HA])","pKw + pKa","Ka/[HA]"],"pKa + log([A-]/[HA])","pH = pKa + log([A-]/[HA]).","hard","acids-bases"),

    // ── NEW MCQ: Gases ────────────────────────────────────────────────────────
    q("mcq-81","mcq","Ideal gas law: PV = ?",["nRT","nR/T","RT/n","PnT"],"nRT","PV = nRT.","easy","gases"),
    q("mcq-82","mcq","At constant T and n, P×V = constant is?",["Charles' law","Avogadro's law","Boyle's law","Gay-Lussac's"],"Boyle's law","Boyle: PV = const at constant T.","easy","gases"),
    q("mcq-83","mcq","At constant P, V/T = constant is?",["Boyle's","Charles'","Avogadro's","Dalton's"],"Charles'","Charles: V/T = constant at constant P.","easy","gases"),
    q("mcq-84","mcq","Dalton's law: total pressure = ?",["Product of partial pressures","Sum of partial pressures","Average of pressures","Highest partial pressure"],"Sum of partial pressures","Ptotal = ΣPi.","easy","gases"),
    q("mcq-85","mcq","Real gases deviate from ideal at?",["Low P, high T","High P, low T","STP","Low concentration"],"High P, low T","At high P / low T intermolecular forces matter.","medium","gases"),

    // ── NEW MCQ: Solutions & Colligative ────────────────────────────────────
    q("mcq-86","mcq","Colligative properties depend on?",["Nature of solute","Concentration of particles","Solute mass","Solvent type"],"Concentration of particles","Colligative: depends only on # of particles.","medium","solutions"),
    q("mcq-87","mcq","Osmotic pressure π = ?",["MRT","nRT/V","CRT","All correct"],"All correct","π = MRT = nRT/V = CRT.","medium","solutions"),
    q("mcq-88","mcq","Boiling point elevation ΔTb = ?",["Kb×m","Kf×m","Kb/m","Kf/m"],"Kb×m","ΔTb = Kb × m (molality).","medium","solutions"),
    q("mcq-89","mcq","Freezing point depression is used to determine?",["Density","Molar mass","Colour","Boiling point"],"Molar mass","ΔTf = Kf×m used to find M.","medium","solutions"),
    q("mcq-90","mcq","Henry's law: solubility of gas ∝ ?",["Temperature","Partial pressure","Volume","Mole fraction"],"Partial pressure","C = kH × P (Henry's law).","medium","solutions"),

    // ── NEW MCQ: Chemical Kinetics ──────────────────────────────────────────
    q("mcq-91","mcq","Rate of reaction is defined as?",["Mass per time","Change in conc per time","Moles per volume","Pressure per temp"],"Change in conc per time","Rate = Δ[conc]/Δt.","easy","kinetics"),
    q("mcq-92","mcq","Arrhenius equation: k = ?",["Ae^(Ea/RT)","Ae^(-Ea/RT)","A/Ea","RT/Ea"],"Ae^(-Ea/RT)","k = A×e^(-Ea/RT).","medium","kinetics"),
    q("mcq-93","mcq","Activation energy is?",["Energy released","Minimum energy for reaction","Maximum PE","Bond energy sum"],"Minimum energy for reaction","Ea = minimum kinetic energy to react.","easy","kinetics"),
    q("mcq-94","mcq","First-order reaction: half-life depends on?",["Initial concentration","Rate constant only","Temperature only","Volume"],"Rate constant only","t½ = 0.693/k for first order.","hard","kinetics"),
    q("mcq-95","mcq","Order of reaction is determined by?",["Stoichiometry","Experiment","Mechanism only","Molar mass"],"Experiment","Rate order must be found experimentally.","medium","kinetics"),

    // ── NEW MCQ: Redox & Electrochemistry extra ─────────────────────────────
    q("mcq-96","mcq","Oxidation means?",["Gain of electrons","Loss of electrons","Gain of protons","Loss of protons"],"Loss of electrons","OIL: Oxidation Is Loss.","easy","redox"),
    q("mcq-97","mcq","In KMnO4 (acidic), MnO4- reduced to?",["Mn2+","MnO2","Mn","MnO4-"],"Mn2+","MnO4- + 8H+ + 5e- → Mn2+ + 4H2O.","hard","redox"),
    q("mcq-98","mcq","Oxidising agent in a reaction?",["Gets oxidised","Gets reduced","Loses electrons","Donates proton"],"Gets reduced","Oxidising agent accepts electrons (gets reduced).","medium","redox"),
    q("mcq-99","mcq","Electrochemical series: highest reduction potential?",["Li+/Li","F2/F-","Na+/Na","Al3+/Al"],"F2/F-","F2 is the strongest oxidising agent.","hard","redox"),
    q("mcq-100","mcq","Rusting of iron requires?",["O2 only","H2O only","O2 and H2O","CO2"],"O2 and H2O","Rust = Fe2O3·xH2O; needs O2 and moisture.","easy","redox"),

    // ── NEW MCQ: Organic extra (101-120) ─────────────────────────────────────
    q("mcq-101","mcq","Markovnikov's rule: in HX addition to unsymmetric alkene, H adds to?",["More substituted C","Less substituted C","Both equally","Carbon with lone pair"],"Less substituted C","H goes to C with more H already (Markovnikov).","hard","organic"),
    q("mcq-102","mcq","Nucleophile attacks?",["Electron-rich centre","Electron-poor centre","Radical","Neutral species"],"Electron-poor centre","Nu attacks δ+ carbon.","medium","organic"),
    q("mcq-103","mcq","Ester formed from?",["Alcohol + acid","Alcohol + base","Acid + base","Amine + acid"],"Alcohol + acid","R-COOH + R'-OH ⇌ R-COOR' + H2O.","easy","organic"),
    q("mcq-104","mcq","Saponification is hydrolysis of ester by?",["Acid","Base (NaOH)","Water","Enzyme"],"Base (NaOH)","Base hydrolysis of ester → soap.","medium","organic"),
    q("mcq-105","mcq","Which reagent converts benzene to nitrobenzene?",["H2SO4 only","HNO3 + H2SO4","HCl","NaOH"],"HNO3 + H2SO4","Mixed acid nitration.","medium","organic"),
    q("mcq-106","mcq","Grignard reagent is?",["R-MgX","R-Li","R-AlCl2","R-ZnX"],"R-MgX","RMgX = Grignard (organomagnesium halide).","medium","organic"),
    q("mcq-107","mcq","Lucas test distinguishes?",["Primary/secondary/tertiary alcohols","Alkene/alkyne","Acid/base","Amine types"],"Primary/secondary/tertiary alcohols","ZnCl2/HCl: 3°>2°>1° reactivity.","hard","organic"),
    q("mcq-108","mcq","Aldehyde vs ketone: aldehyde has?",["CO between two R groups","-CHO terminal group","No carbonyl","Two -OH groups"],"−CHO terminal group","Aldehyde: R-CHO.","easy","organic"),
    q("mcq-109","mcq","Tollens' reagent detects?",["Ketones","Aldehydes","Alkenes","Acids"],"Aldehydes","Silver mirror test for -CHO groups.","medium","organic"),
    q("mcq-110","mcq","IUPAC name of CH3COOH?",["Methanoic acid","Propanoic acid","Ethanoic acid","Butanoic acid"],"Ethanoic acid","2-carbon carboxylic acid.","easy","organic"),
    q("mcq-111","mcq","Which is an aromatic compound?",["Cyclohexane","Benzene","Cyclopentane","Butane"],"Benzene","Benzene: conjugated ring, 4n+2 π electrons (Hückel).","easy","organic"),
    q("mcq-112","mcq","Dehydration of alcohol gives?",["Alkane","Alkene","Alkyne","Ether always"],"Alkene","Conc H2SO4, 170°C → alkene (elimination).","medium","organic"),
    q("mcq-113","mcq","Electrophile attacks?",["Electron-rich site","Electron-poor site","Radical","Sigma bond"],"Electron-rich site","E+ attacks π bonds / lone pairs.","medium","organic"),
    q("mcq-114","mcq","E2 elimination is?",["Unimolecular","Bimolecular","Trimolecular","Radical"],"Bimolecular","Rate = k[substrate][base].","hard","organic"),
    q("mcq-115","mcq","Optical isomers are non-superimposable?",["Structural isomers","Mirror images","Position isomers","Chain isomers"],"Mirror images","Enantiomers = non-superimposable mirror images.","hard","organic"),
    q("mcq-116","mcq","Chiral centre has?",["4 identical groups","4 different groups","3 groups","Double bond"],"4 different groups","Sp3 carbon with 4 distinct substituents.","medium","organic"),
    q("mcq-117","mcq","Free radical halogenation of alkane requires?",["UV light","Acid catalyst","Base","High pressure"],"UV light","Cl2/hν or Br2/hν initiates radical chain.","medium","organic"),
    q("mcq-118","mcq","Product of ozonolysis of RCH=CHR'?",["Alkane","Two carbonyl compounds","Alcohol","Diene"],"Two carbonyl compounds","Ozonolysis cleaves double bond → aldehydes/ketones.","hard","organic"),
    q("mcq-119","mcq","Amines are?",["Acids","Bases","Neutral","Depends on type"],"Bases","Amines donate lone pair → basic.","easy","organic"),
    q("mcq-120","mcq","SN1 rate depends on?",["Nucleophile conc","Substrate and nucleophile","Substrate only","Leaving group only"],"Substrate only","SN1: rate = k[substrate], carbocation intermediate.","hard","organic"),

    // ── NEW Assertion-Reason (40 questions) ─────────────────────────────────
    q("ar-01","assertion_reason","Assertion (A): Noble gases are chemically inert.\nReason (R): They have completely filled outermost shells.",
      ["Both A and R true, R explains A","Both true, R doesn't explain A","A true, R false","A false, R true"],
      "Both A and R true, R explains A","Full valence shell → no tendency to react; R correctly explains A.","easy","periodic-table"),
    q("ar-02","assertion_reason","A: Ionic compounds have high melting points.\nR: They have strong electrostatic forces between ions.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Strong ionic lattice requires much energy to break.","easy","bonding"),
    q("ar-03","assertion_reason","A: H2O has a bent shape.\nR: The central O atom has 2 lone pairs.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Lone pairs repel, compressing bond angle to 104.5°.","medium","bonding"),
    q("ar-04","assertion_reason","A: Graphite conducts electricity.\nR: Graphite has delocalised π electrons.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Delocalised electrons free to move → conduction.","medium","element-identification"),
    q("ar-05","assertion_reason","A: Electronegativity increases across a period.\nR: Nuclear charge increases across a period.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Greater nuclear charge attracts bonding electrons more.","medium","periodic-trends"),
    q("ar-06","assertion_reason","A: Rate of reaction increases with temperature.\nR: More molecules have energy ≥ Ea at higher T.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Maxwell-Boltzmann: higher T shifts distribution to higher energies.","medium","kinetics"),
    q("ar-07","assertion_reason","A: All spontaneous reactions are exothermic.\nR: Spontaneity is determined by ΔG only.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R true","Endothermic reactions can be spontaneous if ΔS is large; ΔG = ΔH - TΔS.","hard","thermochemistry"),
    q("ar-08","assertion_reason","A: Boiling point of HF > HCl.\nR: HF forms stronger hydrogen bonds than HCl.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","F's high electronegativity makes strong H-bonds in HF.","medium","bonding"),
    q("ar-09","assertion_reason","A: Adding catalyst doesn't change equilibrium position.\nR: Catalyst equally lowers Ea for forward and reverse.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Both rates increase equally; Kc unchanged.","medium","equilibrium"),
    q("ar-10","assertion_reason","A: Atomic radius decreases across a period.\nR: Number of electron shells increases across a period.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A true R false","Shells don't increase across a period; radius decreases due to nuclear charge.","hard","periodic-trends"),
    q("ar-11","assertion_reason","A: CO2 is a non-polar molecule.\nR: The C=O bonds cancel due to linear geometry.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Linear geometry: equal and opposite dipoles sum to zero.","medium","bonding"),
    q("ar-12","assertion_reason","A: First ionisation energy of Mg > Na.\nR: Mg has greater nuclear charge than Na.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","More protons pull outer electrons more tightly.","medium","periodic-trends"),
    q("ar-13","assertion_reason","A: Rusting of iron is an electrochemical process.\nR: Rusting requires both O2 and H2O.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R doesn't explain A","Both statements true but R is a condition, not the reason for electrochemical nature.","hard","redox"),
    q("ar-14","assertion_reason","A: Phenol is more acidic than ethanol.\nR: Phenoxide ion is stabilised by resonance.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Resonance delocalises negative charge in C6H5O-.","hard","organic"),
    q("ar-15","assertion_reason","A: Solubility of gases increases with pressure.\nR: Henry's law states C = kH × P.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Higher pressure → more gas dissolves.","medium","solutions"),
    q("ar-16","assertion_reason","A: Diamond is an electrical insulator.\nR: All electrons in diamond are in covalent bonds.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","No free electrons in diamond lattice.","medium","bonding"),
    q("ar-17","assertion_reason","A: SN2 reactions give inversion of configuration.\nR: Backside attack in SN2.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Nu attacks from opposite side → Walden inversion.","hard","organic"),
    q("ar-18","assertion_reason","A: Melting point increases down Group 1.\nR: Metallic bonding strengthens down Group 1.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R false","Melting point decreases down Group 1; metallic bonding weakens.","hard","periodic-trends"),
    q("ar-19","assertion_reason","A: Buffer solutions resist pH change.\nR: Buffers contain a weak acid and its conjugate base.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Conjugate pair neutralises added acid or base.","medium","acids-bases"),
    q("ar-20","assertion_reason","A: Entropy increases when ice melts.\nR: Liquid water has more disorder than ice.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","More random arrangement of molecules in liquid.","easy","thermochemistry"),
    q("ar-21","assertion_reason","A: Zinc displaces hydrogen from dilute HCl.\nR: Zinc is above hydrogen in reactivity series.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","More reactive metal displaces less reactive.","easy","reaction-prediction"),
    q("ar-22","assertion_reason","A: Alkenes undergo addition reactions readily.\nR: Alkenes contain a reactive π bond.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","π electrons are available and easily attacked by electrophiles.","medium","organic"),
    q("ar-23","assertion_reason","A: Higher temperature favours endothermic reaction (Le Chatelier).\nR: Heat can be considered a reactant in endothermic reactions.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Adding 'heat' as reactant shifts equilibrium right.","medium","equilibrium"),
    q("ar-24","assertion_reason","A: sp2 hybridised carbon is trigonal planar.\nR: sp2 has 3 hybrid orbitals at 120°.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","3 sp2 orbitals coplanar at 120°.","medium","bonding"),
    q("ar-25","assertion_reason","A: Second ionisation energy is always greater than first.\nR: Removing an electron from a cation is harder.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Remaining electrons more strongly held after first removal.","medium","atomic-structure"),
    q("ar-26","assertion_reason","A: Cathode is positive in electrolytic cell.\nR: Positive electrode attracts anions.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R true","In electrolytic cell cathode is NEGATIVE; R describes anode. A is false.","hard","electrochemistry"),
    q("ar-27","assertion_reason","A: Rate constant k increases with temperature.\nR: Ea does not change with temperature.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R doesn't explain A","k increases (Arrhenius) but Ea is constant; R doesn't explain A.","hard","kinetics"),
    q("ar-28","assertion_reason","A: Colligative properties depend on solute identity.\nR: Colligative properties depend on number of solute particles.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R true","Colligative properties depend on particle count, NOT identity.","medium","solutions"),
    q("ar-29","assertion_reason","A: Benzene undergoes electrophilic substitution.\nR: Benzene ring electrons are delocalised and attack electrophiles.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Aromaticity maintained by substitution, not addition.","hard","organic"),
    q("ar-30","assertion_reason","A: Van der Waals forces increase with molecular mass.\nR: Larger molecules have more electrons, stronger dispersion.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","More electrons → larger temporary dipoles → stronger London forces.","medium","bonding"),
    q("ar-31","assertion_reason","A: Oxidation state of O in H2O2 is -1.\nR: H is +1 and total must be 0 in H2O2.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","2(+1) + 2x = 0 → x = -1.","medium","redox"),
    q("ar-32","assertion_reason","A: Weak acids partially dissociate in water.\nR: Ka of weak acid << 1.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Small Ka means equilibrium favours undissociated acid.","medium","acids-bases"),
    q("ar-33","assertion_reason","A: Real gases behave ideally at low pressure and high temperature.\nR: At low P, molecules far apart; at high T, kinetic energy dominates.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Intermolecular forces negligible when molecules far apart.","hard","gases"),
    q("ar-34","assertion_reason","A: Addition of inert gas at constant volume doesn't shift equilibrium.\nR: Partial pressures of reactants and products unchanged.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Kp unchanged; mole fractions change but partial P unchanged.","hard","equilibrium"),
    q("ar-35","assertion_reason","A: Tertiary amines have higher boiling point than primary.\nR: Tertiary amines can't form intermolecular H-bonds.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R true","Tertiary amines have LOWER bp; R is correct (no N-H for H-bonding).","hard","organic"),
    q("ar-36","assertion_reason","A: Enthalpy of neutralisation of strong acid-strong base is ~57 kJ/mol.\nR: Reaction is H+ + OH- → H2O always.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Net ionic equation same for all strong acid-base pairs.","medium","thermochemistry"),
    q("ar-37","assertion_reason","A: Osmosis occurs from high to low solute concentration.\nR: Solvent moves from low to high solute concentration across semi-permeable membrane.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "A false R true","Solvent moves from DILUTE (low solute) to CONCENTRATED (high solute); A incorrectly describes this.","hard","solutions"),
    q("ar-38","assertion_reason","A: Zinc acts as anode in Daniel cell.\nR: Zinc is more reactive than copper.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","More reactive Zn oxidises; Zn→Zn2++2e- at anode.","medium","electrochemistry"),
    q("ar-39","assertion_reason","A: Heavier noble gases (Xe, Kr) can form compounds.\nR: Their valence electrons are less tightly held.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Larger atoms: electrons further, easier to involve in bonding.","hard","periodic-table"),
    q("ar-40","assertion_reason","A: Isotopes of same element have same chemical properties.\nR: Chemical properties depend on electron configuration.",
      ["Both true, R explains A","Both true, R doesn't explain A","A true R false","A false R true"],
      "Both true, R explains A","Same electrons → same chemistry; mass differences are minor.","medium","atomic-structure"),

    // ── NEW Numerical (40 questions) ─────────────────────────────────────────
    q("num-01","numerical","Moles in 36g of H2O (M=18)?",["1 mol","2 mol","3 mol","0.5 mol"],"2 mol","n = 36/18 = 2 mol.","easy","mole-concept"),
    q("num-02","numerical","Volume of 0.5 mol ideal gas at STP?",["22.4 L","11.2 L","44.8 L","5.6 L"],"11.2 L","V = 0.5 × 22.4 = 11.2 L.","easy","mole-concept"),
    q("num-03","numerical","Molarity of 4g NaOH (M=40) in 500 mL?",["0.1 M","0.2 M","0.4 M","1 M"],"0.2 M","n=4/40=0.1 mol; M=0.1/0.5=0.2 M.","easy","mole-concept"),
    q("num-04","numerical","pH of 0.01 M HCl?",["1","2","3","4"],"2","pH = -log[H+] = -log(0.01) = 2.","easy","acids-bases"),
    q("num-05","numerical","pH of 0.001 M HCl?",["1","2","3","4"],"3","pH = -log(10-3) = 3.","easy","acids-bases"),
    q("num-06","numerical","[H+] when pH = 5?",["10-3","10-4","10-5","10-6"],"10-5","[H+] = 10^-pH = 10-5 M.","easy","acids-bases"),
    q("num-07","numerical","ΔTf = Kf × m. If Kf(water)=1.86, m=0.5, ΔTf = ?",["0.93°C","1.86°C","3.72°C","0.46°C"],"0.93°C","ΔTf = 1.86 × 0.5 = 0.93°C.","medium","solutions"),
    q("num-08","numerical","EMF: E°cell = E°cathode - E°anode. If E°Cu=+0.34V, E°Zn=-0.76V, E°cell?",["1.10 V","0.42 V","-0.42 V","0.76 V"],"1.10 V","E°cell = 0.34 - (-0.76) = 1.10 V.","medium","electrochemistry"),
    q("num-09","numerical","Half-life of first-order reaction if k=0.0693 s-1?",["10 s","0.693 s","100 s","1 s"],"10 s","t½ = 0.693/k = 0.693/0.0693 = 10 s.","medium","kinetics"),
    q("num-10","numerical","Charge to deposit 1 mol Cu2+ (F=96500 C/mol)?",["48250 C","96500 C","193000 C","289500 C"],"193000 C","Cu2+ + 2e- → Cu; Q = 2×96500 = 193000 C.","hard","electrochemistry"),
    q("num-11","numerical","Atoms in 2 mol He?",["6.022×1023","1.204×1024","3.011×1023","2.408×1024"],"1.204×1024","2 × 6.022×10²³ = 1.204×10²⁴.","easy","mole-concept"),
    q("num-12","numerical","Mass of 3 mol CO2 (M=44)?",["44g","88g","132g","176g"],"132g","m = 3 × 44 = 132 g.","easy","mole-concept"),
    q("num-13","numerical","Rate law: rate=k[A][B]. [A] doubles, rate change?",["×1","×2","×4","×8"],"×2","Rate doubles when [A] doubles (first order in A).","medium","kinetics"),
    q("num-14","numerical","Rate law: rate=k[A]2. [A] triples, rate change?",["×3","×6","×9","×27"],"×9","Rate = k(3[A])² = 9k[A]².","medium","kinetics"),
    q("num-15","numerical","Osmotic pressure of 0.1M glucose at 27°C (R=0.0821)?",["2.46 atm","0.246 atm","24.6 atm","0.0246 atm"],"2.46 atm","π = MRT = 0.1 × 0.0821 × 300 = 2.46 atm.","hard","solutions"),
    q("num-16","numerical","ΔG = ΔH - TΔS. ΔH=-100 kJ, T=300K, ΔS=0.2 kJ/K, ΔG?",["−40 kJ","−160 kJ","40 kJ","160 kJ"],"−160 kJ","ΔG = -100 - 300×0.2 = -100 - 60 = -160 kJ.","hard","thermochemistry"),
    q("num-17","numerical","% yield: theoretical 10g, actual 8g?",["80%","75%","70%","90%"],"80%","% yield = 8/10 × 100 = 80%.","easy","mole-concept"),
    q("num-18","numerical","Molar mass: 0.5 mol weighs 23g?",["23 g/mol","46 g/mol","11.5 g/mol","92 g/mol"],"46 g/mol","M = 23/0.5 = 46 g/mol.","easy","mole-concept"),
    q("num-19","numerical","Number of molecules in 2g H2 (M=2)?",["6.022×1023","1.204×1024","3.011×1022","6.022×1022"],"6.022×1023","n=1 mol → 6.022×10²³ molecules.","medium","mole-concept"),
    q("num-20","numerical","Concentration after dilution: 100mL of 2M → 200mL, new M?",["4 M","2 M","1 M","0.5 M"],"1 M","M1V1=M2V2 → 2×100=M2×200 → M2=1M.","easy","solutions"),
    q("num-21","numerical","pH of pure water at 25°C?",["6","7","8","14"],"7","Kw=10-14, [H+]=[OH-]=10-7, pH=7.","easy","acids-bases"),
    q("num-22","numerical","pOH of 0.1M NaOH?",["1","7","13","14"],"1","[OH-]=0.1=10-1, pOH=1.","easy","acids-bases"),
    q("num-23","numerical","pH + pOH at 25°C = ?",["7","10","14","0"],"14","pH + pOH = pKw = 14 at 25°C.","easy","acids-bases"),
    q("num-24","numerical","Boiling point elevation ΔTb=Kb×m. Kb(water)=0.52, m=2 mol/kg, ΔTb?",["0.52°C","1.04°C","2.08°C","0.26°C"],"1.04°C","ΔTb = 0.52 × 2 = 1.04°C.","medium","solutions"),
    q("num-25","numerical","Mass of 0.2 mol NaCl (M=58.5)?",["5.85g","11.7g","29.25g","58.5g"],"11.7g","m = 0.2 × 58.5 = 11.7 g.","easy","mole-concept"),
    q("num-26","numerical","Specific heat: Q = mcΔT. m=100g, c=4.18 J/(g°C), ΔT=10°C, Q?",["418 J","41.8 J","4180 J","4.18 J"],"418 J","Q = 100 × 4.18 × 10 = 418 J = 4180... wait 418 J.","medium","thermochemistry"),
    q("num-27","numerical","Rate constant k=2×10-3 s-1. Order is first. t½?",["346.5 s","500 s","693 s","100 s"],"346.5 s","t½ = 0.693/0.002 = 346.5 s.","medium","kinetics"),
    q("num-28","numerical","ΔH by Hess: A→B ΔH=-300, B→C ΔH=+100. A→C?",["−200 kJ","−400 kJ","200 kJ","400 kJ"],"−200 kJ","ΔH(A→C) = -300 + 100 = -200 kJ.","medium","thermochemistry"),
    q("num-29","numerical","Empirical formula mass 14; molecular mass 28. Molecular formula?",["CH2","C2H4","C2H6","CH4"],"C2H4","Ratio 28/14=2; empirical CH2 × 2 = C2H4.","medium","mole-concept"),
    q("num-30","numerical","Cell EMF E°= +1.1 V, n=2, ΔG° = ?",["−nFE°","−212300 J","212300 J","21230 J"],"−212300 J","ΔG°= -nFE° = -2×96500×1.1 = -212300 J.","hard","electrochemistry"),
    q("num-31","numerical","Mass % of Na in NaCl (Na=23, Cl=35.5)?",["39.3%","60.7%","23%","50%"],"39.3%","(23/58.5)×100 = 39.3%.","medium","mole-concept"),
    q("num-32","numerical","Rate doubles when T rises 10K. At 40°C vs 20°C, rate factor?",["2","4","8","16"],"4","Two 10K rises → 2² = 4.","medium","kinetics"),
    q("num-33","numerical","Moles of electrons in 2F charge?",["1","2","0.5","4"],"2","F = 1 mol electrons; 2F = 2 mol.","medium","electrochemistry"),
    q("num-34","numerical","pH of 0.1M acetic acid (Ka=1.8×10-5)?",["2.87","3.87","4.87","1.87"],"2.87","[H+]=√(Ka×C)=√(1.8×10-6)=1.34×10-3; pH≈2.87.","hard","acids-bases"),
    q("num-35","numerical","Van't Hoff factor for NaCl in water?",["1","2","3","0.5"],"2","NaCl→Na++Cl-; i=2.","medium","solutions"),
    q("num-36","numerical","ΔTf = iKfm. NaCl, i=2, Kf=1.86, m=0.1. ΔTf?",["0.186°C","0.372°C","0.093°C","0.744°C"],"0.372°C","ΔTf = 2 × 1.86 × 0.1 = 0.372°C.","medium","solutions"),
    q("num-37","numerical","PV=nRT. P=2atm, V=5L, T=300K, R=0.0821 L·atm/mol·K, n?",["0.41 mol","0.41 mol","4.07 mol","0.407 mol"],"0.407 mol","n = PV/RT = 10/(0.0821×300) = 0.407 mol.","hard","gases"),
    q("num-38","numerical","Normality of 0.5M H2SO4?",["0.5 N","1 N","2 N","0.25 N"],"1 N","H2SO4 has n-factor 2; N = 2 × 0.5 = 1 N.","medium","mole-concept"),
    q("num-39","numerical","Activation energy Ea=50 kJ/mol, T=500K, R=8.314. Ea/RT ≈ ?",["12.0","6.0","24.0","3.0"],"12.0","Ea/RT = 50000/(8.314×500) ≈ 12.0.","hard","kinetics"),
    q("num-40","numerical","Moles of O2 from 2 mol KClO3 → 2KCl + 3O2?",["1 mol","2 mol","3 mol","1.5 mol"],"3 mol","2 mol KClO3 gives 3 mol O2.","medium","mole-concept"),

    // ── NEW Reaction Prediction (40 questions) ────────────────────────────────
    q("rxn-01","reaction_prediction","H2 + Cl2 → ?",["HCl","H2Cl2","H2Cl","HCl2"],"HCl","H2 + Cl2 → 2HCl (synthesis).","easy","reaction-prediction"),
    q("rxn-02","reaction_prediction","Na + O2 → ? (normal burning)?",["NaO","Na2O","Na2O2","NaO2"],"Na2O","4Na + O2 → 2Na2O.","medium","reaction-prediction"),
    q("rxn-03","reaction_prediction","2H2O2 → ? (decomposition with catalyst)?",["2H2O","2H2+O2","2H2O + O2","H2+H2O2"],"2H2O + O2","2H2O2 → 2H2O + O2 (MnO2 catalyst).","easy","reaction-prediction"),
    q("rxn-04","reaction_prediction","Fe + S → ? (on heating)?",["FeS2","FeS","Fe2S3","Fe2S"],"FeS","Fe + S → FeS.","easy","reaction-prediction"),
    q("rxn-05","reaction_prediction","Zn + dilute H2SO4 → ?",["ZnSO4 + H2","ZnS + H2O","Zn2SO4 + H","ZnSO4 + H2O"],"ZnSO4 + H2","Zn + H2SO4 → ZnSO4 + H2.","easy","reaction-prediction"),
    q("rxn-06","reaction_prediction","CH4 + Cl2 (UV light) → ?",["CH3Cl + HCl","CHCl3","CCl4","CH2Cl2"],"CH3Cl + HCl","Free radical substitution: CH4 + Cl2 → CH3Cl + HCl.","medium","reaction-prediction"),
    q("rxn-07","reaction_prediction","C2H4 + H2O (H+ catalyst) → ?",["C2H5OH","CH3OH","C2H6","CH3CHO"],"C2H5OH","Markovnikov hydration: C2H4 + H2O → C2H5OH.","medium","reaction-prediction"),
    q("rxn-08","reaction_prediction","CH3COOH + NaOH → ?",["CH3COONa + H2O","CH4 + Na2O","CH3OH + NaCl","CH3COONa + CO2"],"CH3COONa + H2O","Neutralisation of carboxylic acid.","easy","reaction-prediction"),
    q("rxn-09","reaction_prediction","CuO + H2 (heat) → ?",["Cu + H2O","CuH + O","Cu2O + H2O","CuH2 + O2"],"Cu + H2O","Reduction: CuO + H2 → Cu + H2O.","easy","reaction-prediction"),
    q("rxn-10","reaction_prediction","Mg + CO2 → ?",["MgO + C","MgCO3","MgC + O2","MgO + CO"],"MgO + C","2Mg + CO2 → 2MgO + C (vigorous).","hard","reaction-prediction"),
    q("rxn-11","reaction_prediction","N2 + 3H2 ⇌ ? (Haber process)?",["NH3","NH4OH","N2H4","HNO3"],"NH3","N2 + 3H2 → 2NH3 (Haber, Fe catalyst).","easy","reaction-prediction"),
    q("rxn-12","reaction_prediction","SO2 + H2O → ?",["H2SO4","H2SO3","SO3","H2S"],"H2SO3","SO2 + H2O → H2SO3 (sulphurous acid).","easy","reaction-prediction"),
    q("rxn-13","reaction_prediction","Ethanol + K2Cr2O7/H2SO4 (mild oxidation) → ?",["Ethene","Ethanoic acid","Ethanal","Ethane"],"Ethanal","Primary alcohol mild oxidation → aldehyde (ethanal).","medium","reaction-prediction"),
    q("rxn-14","reaction_prediction","Ethanol + K2Cr2O7/H2SO4 (excess) → ?",["Ethanal","Ethene","Ethanoic acid","CO2"],"Ethanoic acid","Strong oxidation: primary alcohol → carboxylic acid.","medium","reaction-prediction"),
    q("rxn-15","reaction_prediction","Benzene + Br2 (FeBr3 catalyst) → ?",["Bromobenzene + HBr","1,2-dibromobenzene","C6H6Br6","Cyclohexene + Br2"],"Bromobenzene + HBr","EAS: C6H6 + Br2 → C6H5Br + HBr.","medium","reaction-prediction"),
    q("rxn-16","reaction_prediction","CH3CHO + Tollens' reagent → ?",["No reaction","Silver mirror + CH3COOH","CH3CH2OH","CO2 + H2O"],"Silver mirror + CH3COOH","Aldehydes reduce Ag+ → Ag mirror.","medium","reaction-prediction"),
    q("rxn-17","reaction_prediction","PCl5 → ? (on heating)?",["PCl3 + Cl2","P + Cl5","PCl4 + Cl","P2Cl10"],"PCl3 + Cl2","Thermal decomposition: PCl5 → PCl3 + Cl2.","medium","reaction-prediction"),
    q("rxn-18","reaction_prediction","Na2CO3 + HCl → ?",["NaCl + H2O + CO2","Na2Cl + CO3","NaOH + CO2","NaHCO3"],"NaCl + H2O + CO2","Na2CO3 + 2HCl → 2NaCl + H2O + CO2.","easy","reaction-prediction"),
    q("rxn-19","reaction_prediction","Propene + HBr → ? (Markovnikov)?",["1-bromopropane","2-bromopropane","1,2-dibromopropane","3-bromopropane"],"2-bromopropane","H adds to CH2, Br to CH (more substituted).","hard","reaction-prediction"),
    q("rxn-20","reaction_prediction","CH3COOH + C2H5OH (H+ catalyst) → ?",["Ester + H2O","Alcohol + acid","Salt + H2","Aldehyde + H2O"],"Ester + H2O","Fischer esterification → ethyl ethanoate + H2O.","medium","reaction-prediction"),
    q("rxn-21","reaction_prediction","Cl2 + NaOH (cold, dilute) → ?",["NaCl + NaClO + H2O","NaClO3","Na2O + HCl","NaCl + O2"],"NaCl + NaClO + H2O","Cl2 + 2NaOH → NaCl + NaOCl + H2O.","medium","reaction-prediction"),
    q("rxn-22","reaction_prediction","Alkene + ozone then Zn/H2O (reductive workup) → ?",["Alkane","Carbonyl compounds","Epoxide","Alcohol"],"Carbonyl compounds","Ozonolysis: C=C cleaved to give aldehydes/ketones.","hard","reaction-prediction"),
    q("rxn-23","reaction_prediction","CaO + H2O → ?",["CaCO3","Ca(OH)2","CaH2 + O","CaO2"],"Ca(OH)2","CaO + H2O → Ca(OH)2 (slaked lime).","easy","reaction-prediction"),
    q("rxn-24","reaction_prediction","NH3 + O2 (Pt, Ostwald) → ?",["NO + H2O","N2 + H2O","NH4OH","NO2 + H2"],"NO + H2O","4NH3 + 5O2 → 4NO + 6H2O (Ostwald, first step).","hard","reaction-prediction"),
    q("rxn-25","reaction_prediction","AlCl3 + 3NaOH (excess) → ?",["Al(OH)3 + NaCl","NaAlO2 + H2O + NaCl","Al2O3 + NaCl + H2O","All above"],"NaAlO2 + H2O + NaCl","Excess NaOH dissolves amphoteric Al(OH)3: Al(OH)3 + NaOH → NaAlO2 + 2H2O.","hard","reaction-prediction"),
    q("rxn-26","reaction_prediction","Ethyne + H2O (H2SO4, HgSO4) → ?",["Ethanol","Ethanal","Ethene","Acetone"],"Ethanal","Wacker-like: HC≡CH + H2O → CH3CHO (Markovnikov).","hard","reaction-prediction"),
    q("rxn-27","reaction_prediction","Mg + N2 (on burning) → ?",["MgN","Mg3N2","MgN2","Mg2N"],"Mg3N2","3Mg + N2 → Mg3N2 (magnesium nitride).","medium","reaction-prediction"),
    q("rxn-28","reaction_prediction","Cu + dilute HCl → ?",["CuCl2 + H2","No reaction","CuO + HCl","CuH + Cl2"],"No reaction","Cu below H in reactivity series; no H2 from dilute HCl.","medium","reaction-prediction"),
    q("rxn-29","reaction_prediction","MnO2 + 4HCl (conc) → ?",["MnCl2 + Cl2 + 2H2O","MnO + HCl","Mn + Cl2","MnCl4"],"MnCl2 + Cl2 + 2H2O","Oxidation of HCl by MnO2 → Cl2 gas.","hard","reaction-prediction"),
    q("rxn-30","reaction_prediction","Acetone + 2,4-DNP → ?",["Orange precipitate","Silver mirror","Blue colour","Effervescence"],"Orange precipitate","Carbonyl compounds form coloured hydrazone with 2,4-DNPH.","medium","reaction-prediction"),
    q("rxn-31","reaction_prediction","Propan-2-ol + PCl5 → ?",["2-chloropropane + POCl3 + HCl","1-chloropropane","3-chloropropane","Propene"],"2-chloropropane + POCl3 + HCl","OH replaced by Cl, configuration inverted.","medium","reaction-prediction"),
    q("rxn-32","reaction_prediction","Ca(OH)2 + CO2 (excess) → ?",["CaCO3","Ca(HCO3)2","CaO + H2O","CaC2"],"Ca(HCO3)2","Excess CO2: CaCO3 + CO2 + H2O → Ca(HCO3)2 (soluble).","hard","reaction-prediction"),
    q("rxn-33","reaction_prediction","C + H2O (steam, high T) → ?",["CO + H2 (water gas)","CO2 + H2","CH4","C + H2O"],"CO + H2 (water gas)","C + H2O → CO + H2 (water gas reaction).","medium","reaction-prediction"),
    q("rxn-34","reaction_prediction","Aniline + NaNO2 + HCl (0-5°C) → ?",["Benzene diazonium chloride","Nitrobenzene","Phenol","Chlorobenzene"],"Benzene diazonium chloride","Diazotisation of aniline.","hard","reaction-prediction"),
    q("rxn-35","reaction_prediction","CH3MgBr + CO2, then H3O+ → ?",["CH3OH","CH3COOH","C2H5OH","HCOOH"],"CH3COOH","Grignard + CO2 → carboxylic acid after workup.","hard","reaction-prediction"),
    q("rxn-36","reaction_prediction","Alkane + excess Cl2 (UV) final product?",["Monochloro","Dichloro","CCl4 (fully substituted)","No product"],"CCl4 (fully substituted)","Excess Cl2 replaces all H atoms.","medium","reaction-prediction"),
    q("rxn-37","reaction_prediction","Ethene + Br2 (CCl4 solvent) → ?",["1,2-dibromoethane","Vinyl bromide","Bromoethane","Ethyne"],"1,2-dibromoethane","Addition: CH2=CH2 + Br2 → CH2BrCH2Br.","easy","reaction-prediction"),
    q("rxn-38","reaction_prediction","P4 + 3NaOH + 3H2O → ?",["PH3 + NaH2PO2","Na3PO4 + PH3","NaPH2 + H2O","P2O5 + NaH"],"PH3 + NaH2PO2","Disproportionation of P4 in base → PH3 + hypophosphite.","hard","reaction-prediction"),
    q("rxn-39","reaction_prediction","CHCl3 + NaOH (alc) → ?",["CCl4 + NaCl","CO + NaCl + HCl","CCl2 (carbene) → products","CHO + NaCl"],"CCl2 (carbene) → products","Dichlorocarbene formed; reacts further.","hard","reaction-prediction"),
    q("rxn-40","reaction_prediction","Benzene + CH3Cl (AlCl3) → ?",["Toluene + HCl","Chlorobenzene","Benzyl chloride","Cyclohexane"],"Toluene + HCl","Friedel-Crafts alkylation: benzene + CH3Cl → toluene + HCl.","medium","reaction-prediction"),

    // ── Extra MCQ to reach 300+ total ────────────────────────────────────────
    q("mcq-121","mcq","Which gas is produced in Haber process?",["H2","N2","NH3","NO"],"NH3","N2 + 3H2 → 2NH3.","easy","industrial"),
    q("mcq-122","mcq","Contact process produces?",["HNO3","H2SO4","HCl","H3PO4"],"H2SO4","SO2→SO3→H2SO4 (Contact process).","easy","industrial"),
    q("mcq-123","mcq","Electrolysis of brine gives?",["Cl2 + NaOH + H2","Na + Cl2","NaCl","Na2O"],"Cl2 + NaOH + H2","Chlor-alkali process.","medium","electrochemistry"),
    q("mcq-124","mcq","Which acid is known as oil of vitriol?",["HNO3","HCl","H2SO4","H3PO4"],"H2SO4","Concentrated H2SO4 = oil of vitriol.","easy","acids-bases"),
    q("mcq-125","mcq","Absolute zero in Celsius?",["0°C","-100°C","-273.15°C","-373.15°C"],"−273.15°C","0 K = -273.15°C.","easy","gases"),
    q("mcq-126","mcq","Which element has the electron config [Ar]3d104s1?",["Ca","Zn","Cu","Ag"],"Cu","Cu: anomalous config due to half-filled d stability.","hard","atomic-structure"),
    q("mcq-127","mcq","Reaction between acid and carbonate releases?",["H2","O2","CO2","SO2"],"CO2","HCl + Na2CO3 → NaCl + H2O + CO2.","easy","reaction-prediction"),
    q("mcq-128","mcq","Tyndall effect is shown by?",["True solutions","Colloids","Suspensions","Gases"],"Colloids","Colloidal particles scatter light (Tyndall effect).","medium","solutions"),
    q("mcq-129","mcq","VSEPR shape of NH3?",["Trigonal planar","Tetrahedral","Trigonal pyramidal","Linear"],"Trigonal pyramidal","3 bonds + 1 lone pair → pyramidal.","medium","bonding"),
    q("mcq-130","mcq","Catalyst used in catalytic converter?",["Fe","Pt / Pd / Rh","Ni","Mn"],"Pt / Pd / Rh","Platinum group metals catalyse exhaust gas conversion.","medium","industrial"),
    q("mcq-131","mcq","Law of conservation of mass states?",["Energy is conserved","Mass of reactants = mass of products","Atoms gain mass","Molecules split equally"],"Mass of reactants = mass of products","Matter is neither created nor destroyed.","easy","mole-concept"),
    q("mcq-132","mcq","Avogadro's hypothesis: equal volumes of gases at same T and P contain?",["Equal mass","Equal moles","Equal atoms","Equal density"],"Equal moles","Avogadro: same V → same n at same T, P.","easy","gases"),
    q("mcq-133","mcq","Which quantum number can have value +1/2 or -1/2?",["n","l","ml","ms"],"ms","Spin quantum number ms = ±½.","easy","atomic-structure"),
    q("mcq-134","mcq","In SN2, tertiary alkyl halide reacts?",["Faster than primary","Same as primary","Slower than primary","Only with strong Nu"],"Slower than primary","Steric hindrance slows SN2 for 3° substrates.","hard","organic"),
  ] };

  public func getAllQuestions() : [QuizQuestion] { allQuestions() };

  public func getQuestionById(id : Text) : ?QuizQuestion {
    allQuestions().find(func(q) { q.id == id })
  };

  public func getByDifficultyAndTopic(difficulty : Text, topic : Text) : [QuizQuestion] {
    let matchDiff = difficulty == "";
    let matchTopic = topic == "";
    allQuestions().filter(func(q) {
      (matchDiff or q.difficulty == difficulty) and
      (matchTopic or q.topic == topic)
    })
  };
};
