import Array "mo:core/Array";
import Types "../types/reactivity";

module {
  public type ReactivityMetal = Types.ReactivityMetal;
  public type ChemicalReaction = Types.ChemicalReaction;

  // ── helpers ────────────────────────────────────────────────────────────────
  func r(reactionType : Text, partner : Text, equation : Text, observation : Text) : Types.MetalReaction =
    { reactionType; partner; equation; observation };

  func m(symbol : Text, name : Text, rank : Nat, reactions : [Types.MetalReaction], interestingFacts : [Text]) : ReactivityMetal =
    { symbol; name; rank; reactions; interestingFacts };

  func reactant(symbol : Text, name : Text, coefficient : Nat) : Types.ChemicalReactant =
    { symbol; name; coefficient };

  func product(symbol : Text, name : Text, formula : Text, coefficient : Nat) : Types.ChemicalProduct =
    { symbol; name; formula; coefficient };

  func rxn(
    id : Text, name : Text,
    reactants : [Types.ChemicalReactant], products : [Types.ChemicalProduct],
    balancedEquation : Text, reactionType : Text, energyChange : Text,
    description : Text, observations : [Text],
    category : Text, namedReaction : Text
  ) : ChemicalReaction =
    { id; name; reactants; products; balancedEquation; reactionType; energyChange; description; observations; category; namedReaction };

  // ── reactivity series data ─────────────────────────────────────────────────
  func allMetals() : [ReactivityMetal] { [
    m("K",  "Potassium",  1,
      [r("metal+water","Water","2K + 2H₂O → 2KOH + H₂↑","Extremely violent; ignites spontaneously, lilac flame"),
       r("metal+acid","HCl","2K + 2HCl → 2KCl + H₂↑","Dangerously explosive, not performed in lab")],
      ["Most reactive common metal","Burns with lilac-purple flame","Stored under mineral oil","Ignites the H₂ produced in water"]),
    m("Na",  "Sodium",    2,
      [r("metal+water","Water","2Na + 2H₂O → 2NaOH + H₂↑","Vigorous; melts into ball, skips across water"),
       r("metal+acid","HCl","2Na + 2HCl → 2NaCl + H₂↑","Very vigorous, potentially explosive")],
      ["Burns with bright yellow flame","Stored under oil","Reacts violently with water","Used in nerve signal transmission"]),
    m("Li",  "Lithium",   3,
      [r("metal+water","Water","2Li + 2H₂O → 2LiOH + H₂↑","Steady effervescence, less violent than Na or K"),
       r("metal+acid","HCl","2Li + 2HCl → 2LiCl + H₂↑","Rapid, produces hydrogen gas")],
      ["Lightest metal","Burns crimson-red","Used in Li-ion batteries","Lithium carbonate treats bipolar disorder"]),
    m("Ca",  "Calcium",   4,
      [r("metal+water","Water","Ca + 2H₂O → Ca(OH)₂ + H₂↑","Steady bubbling, water turns milky"),
       r("metal+acid","HCl","Ca + 2HCl → CaCl₂ + H₂↑","Rapid effervescence")],
      ["Most abundant metal in human body","Reacts steadily with water","Burns brick-red","Essential for bones"]),
    m("Mg",  "Magnesium", 5,
      [r("metal+water","Water","Mg + 2H₂O → Mg(OH)₂ + H₂↑","Very slow cold water; vigorous with steam"),
       r("metal+acid","HCl","Mg + 2HCl → MgCl₂ + H₂↑","Rapid, vigorous effervescence")],
      ["Burns with blinding white flame","Reacts slowly with cold water","Lightest structural engineering metal","Essential for chlorophyll"]),
    m("Al",  "Aluminium", 6,
      [r("metal+water","Water","2Al + 6H₂O → 2Al(OH)₃ + 3H₂↑","Barely reacts due to oxide layer"),
       r("metal+acid","HCl","2Al + 6HCl → 2AlCl₃ + 3H₂↑","Rapid once surface oxide dissolves")],
      ["Protected by invisible oxide layer","3rd most abundant element in crust","Appears unreactive due to passivation","Used in Thermite reaction"]),
    m("Zn",  "Zinc",      7,
      [r("metal+water","Water","Zn + H₂O → ZnO + H₂↑","Reacts with steam; very slow with cold water"),
       r("metal+acid","HCl","Zn + 2HCl → ZnCl₂ + H₂↑","Moderate steady effervescence")],
      ["Used to galvanise iron","Burns blue-green","Essential trace element","Found in 300+ human enzymes"]),
    m("Fe",  "Iron",      8,
      [r("metal+water","Water","3Fe + 4H₂O → Fe₃O₄ + 4H₂↑","Only with steam; no cold water reaction"),
       r("metal+acid","HCl","Fe + 2HCl → FeCl₂ + H₂↑","Slow steady reaction")],
      ["Only reacts with steam, not liquid water","Rusting is slow electrochemical corrosion","Earth's inner core is solid iron","Haemoglobin uses iron to carry oxygen"]),
    m("Ni",  "Nickel",    9,
      [r("metal+water","Water","Ni + H₂O → No significant reaction","Does not react appreciably"),
       r("metal+acid","HCl","Ni + 2HCl → NiCl₂ + H₂↑","Slow, gradual dissolution")],
      ["Used in NiMH batteries","Highly corrosion-resistant","Named from German 'goblin copper'","Earth's core contains nickel"]),
    m("Sn",  "Tin",       10,
      [r("metal+water","Water","Sn + H₂O → No significant reaction","No reaction under standard conditions"),
       r("metal+acid","HCl","Sn + 2HCl → SnCl₂ + H₂↑","Slow dissolution in dilute acid")],
      ["First metals smelted by humans","Bronze = copper + tin","Below 13.2°C turns to brittle grey tin","Coats steel cans to prevent rust"]),
    m("Pb",  "Lead",      11,
      [r("metal+water","Water","Pb + H₂O → No significant reaction","Insoluble oxide coating prevents reaction"),
       r("metal+acid","HCl","Pb + 2HCl → PbCl₂ + H₂↑","Very slow, PbCl₂ forms protective layer")],
      ["Dense, soft, low melting point","Used in car batteries","Highly toxic, banned from paints","Roman pipes were lead (plumbum → Pb)"]),
    m("H",   "Hydrogen",  12,
      [r("non-metal+acid","HCl","H₂ + Cl₂ → 2HCl","Explosive in light or spark"),
       r("reference","","","Reference point in reactivity series")],
      ["Divides metals that displace H₂ from acid vs those that cannot","Most abundant element in universe","Burns with almost invisible pale blue flame","Powers the Sun via nuclear fusion"]),
    m("Cu",  "Copper",    13,
      [r("metal+water","Water","Cu + H₂O → No reaction","Does not react with water"),
       r("metal+acid","HCl","Cu + 2HCl → No significant reaction","Reacts only with oxidising acids like HNO₃")],
      ["Below hydrogen, cannot displace H₂ from acids","Used by humans for 10,000+ years","Natural antimicrobial properties","Turns green (verdigris) in air"]),
    m("Hg",  "Mercury",   14,
      [r("metal+water","Water","Hg + H₂O → No reaction","Does not react with water"),
       r("metal+acid","HNO₃","3Hg + 8HNO₃(dilute) → 3Hg(NO₃)₂ + 2NO + 4H₂O","Dissolves in oxidising acids")],
      ["Only liquid metal at room temperature","Used in old thermometers","Highly toxic to nervous system","Symbol Hg from Hydrargyrum (liquid silver)"]),
    m("Ag",  "Silver",    15,
      [r("metal+water","Water","Ag + H₂O → No reaction","Does not react with water"),
       r("metal+acid","HNO₃","3Ag + 4HNO₃(dilute) → 3AgNO₃ + NO + 2H₂O","Dissolves in nitric acid")],
      ["Best electrical conductor","Natural antimicrobial properties","Used in currency for millennia","Silver mirror reaction silvers glass"]),
    m("Au",  "Gold",      16,
      [r("metal+water","Water","Au + H₂O → No reaction","Does not react with water"),
       r("metal+acid","Aqua regia","Au + HNO₃ + 3HCl → AuCl₃ + NO + 2H₂O","Only dissolves in aqua regia")],
      ["Least reactive common metal","Does not corrode or tarnish","Only aqua regia dissolves it","Valued since earliest civilisations"]),
    m("Pt",  "Platinum",  17,
      [r("metal+water","Water","Pt + H₂O → No reaction","Does not react with water"),
       r("metal+acid","Aqua regia","Pt + 4HNO₃ + 6HCl → H₂[PtCl₆] + 4NO₂ + 4H₂O","Dissolves only in hot aqua regia")],
      ["Most corrosion-resistant metal","Vital catalyst in catalytic converters","Named from Spanish 'platina' (little silver)","Highest melting point of platinum group"]),
  ] };

  // ── chemical reactions data ────────────────────────────────────────────────
  func allReactions() : [ChemicalReaction] { [
    // ── Inorganic: Combustion ─────────────────────────────────────────────
    rxn("comb-h2-o2","Combustion of Hydrogen",
      [reactant("H₂","Hydrogen",2),reactant("O₂","Oxygen",1)],
      [product("H₂O","Water","H₂O",2)],
      "2H₂ + O₂ → 2H₂O","combustion","exothermic",
      "Hydrogen burns in oxygen to form water. Powers rocket engines and hydrogen fuel cells.",
      ["Pale blue invisible flame","Only water produced – no CO₂","Powers Space Shuttle engines"],
      "inorganic",""),
    rxn("comb-c-o2","Combustion of Carbon",
      [reactant("C","Carbon",1),reactant("O₂","Oxygen",1)],
      [product("CO₂","Carbon Dioxide","CO₂",1)],
      "C + O₂ → CO₂","combustion","exothermic",
      "Carbon burns in excess oxygen to produce CO₂. In limited oxygen, CO is produced instead.",
      ["Produces CO₂ in excess O₂","Incomplete combustion gives toxic CO","Burning coal is largely this reaction"],
      "inorganic",""),
    rxn("comb-ch4-o2","Combustion of Methane",
      [reactant("CH₄","Methane",1),reactant("O₂","Oxygen",2)],
      [product("CO₂","Carbon Dioxide","CO₂",1),product("H₂O","Water","H₂O",2)],
      "CH₄ + 2O₂ → CO₂ + 2H₂O","combustion","exothermic",
      "Methane (natural gas) burns producing CO₂ and water. Primary reaction in gas stoves.",
      ["Natural gas is mostly methane","Burns with blue flame","Releases ~890 kJ/mol"],
      "inorganic",""),
    rxn("comb-c3h8-o2","Combustion of Propane",
      [reactant("C₃H₈","Propane",1),reactant("O₂","Oxygen",5)],
      [product("CO₂","Carbon Dioxide","CO₂",3),product("H₂O","Water","H₂O",4)],
      "C₃H₈ + 5O₂ → 3CO₂ + 4H₂O","combustion","exothermic",
      "Propane (LPG) burns completely to produce CO₂ and water.",
      ["Used in gas grills and camping stoves","Stored as liquid under pressure","Burns cleanly with blue flame"],
      "inorganic",""),
    rxn("comb-mg-o2","Combustion of Magnesium",
      [reactant("Mg","Magnesium",2),reactant("O₂","Oxygen",1)],
      [product("MgO","Magnesium Oxide","MgO",2)],
      "2Mg + O₂ → 2MgO","combustion","exothermic",
      "Magnesium burns with an intensely bright white flame producing magnesium oxide.",
      ["Burns so brightly it can damage eyesight","Cannot be extinguished with water","Used in fireworks and flares"],
      "inorganic",""),
    rxn("comb-s-o2","Combustion of Sulfur",
      [reactant("S","Sulfur",1),reactant("O₂","Oxygen",1)],
      [product("SO₂","Sulfur Dioxide","SO₂",1)],
      "S + O₂ → SO₂","combustion","exothermic",
      "Sulfur burns in oxygen producing toxic SO₂. Key contributor to acid rain.",
      ["Blue flame","Choking pungent smell","SO₂ causes acid rain","Used in wine preservation"],
      "inorganic",""),
    rxn("comb-c2h5oh","Combustion of Ethanol",
      [reactant("C₂H₅OH","Ethanol",1),reactant("O₂","Oxygen",3)],
      [product("CO₂","Carbon Dioxide","CO₂",2),product("H₂O","Water","H₂O",3)],
      "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O","combustion","exothermic",
      "Ethanol burns completely in oxygen to form CO₂ and water. Used as biofuel.",
      ["Burns with pale blue flame","Biofuel application","~1370 kJ/mol energy"],
      "inorganic",""),
    rxn("comb-c4h10","Combustion of Butane",
      [reactant("C₄H₁₀","Butane",2),reactant("O₂","Oxygen",13)],
      [product("CO₂","Carbon Dioxide","CO₂",8),product("H₂O","Water","H₂O",10)],
      "2C₄H₁₀ + 13O₂ → 8CO₂ + 10H₂O","combustion","exothermic",
      "Butane burns completely. Used in lighters and portable stoves.",
      ["Used in cigarette lighters","Blue flame","~2878 kJ/mol"],
      "inorganic",""),
    // ── Inorganic: Acid-Base ──────────────────────────────────────────────
    rxn("acid-hcl-naoh","HCl + NaOH Neutralisation",
      [reactant("HCl","Hydrochloric Acid",1),reactant("NaOH","Sodium Hydroxide",1)],
      [product("NaCl","Sodium Chloride","NaCl",1),product("H₂O","Water","H₂O",1)],
      "HCl + NaOH → NaCl + H₂O","acid-base","exothermic",
      "Classic neutralisation of strong acid with strong base producing salt and water.",
      ["Exothermic, mixture warms up","Universal indicator turns green at pH 7","No gas produced"],
      "inorganic",""),
    rxn("acid-h2so4-naoh","H₂SO₄ + NaOH Neutralisation",
      [reactant("H₂SO₄","Sulfuric Acid",1),reactant("NaOH","Sodium Hydroxide",2)],
      [product("Na₂SO₄","Sodium Sulfate","Na₂SO₄",1),product("H₂O","Water","H₂O",2)],
      "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O","acid-base","exothermic",
      "Diprotic sulfuric acid requires two moles of NaOH. Very exothermic.",
      ["Two moles of NaOH per mole of H₂SO₄","Very exothermic, add acid to water","Product sodium sulfate used in detergents"],
      "inorganic",""),
    rxn("acid-hcl-caco3","HCl + Calcium Carbonate",
      [reactant("HCl","Hydrochloric Acid",2),reactant("CaCO₃","Calcium Carbonate",1)],
      [product("CaCl₂","Calcium Chloride","CaCl₂",1),product("H₂O","Water","H₂O",1),product("CO₂","Carbon Dioxide","CO₂",1)],
      "2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂↑","acid-base","exothermic",
      "Acid reacts with limestone/chalk producing CO₂ gas. Explains acid rain erosion.",
      ["CO₂ fizzing","CO₂ turns limewater milky","Acid rain dissolves limestone buildings"],
      "inorganic",""),
    rxn("acid-acetic-naoh","Acetic Acid + NaOH",
      [reactant("CH₃COOH","Acetic Acid",1),reactant("NaOH","Sodium Hydroxide",1)],
      [product("CH₃COONa","Sodium Acetate","CH₃COONa",1),product("H₂O","Water","H₂O",1)],
      "CH₃COOH + NaOH → CH₃COONa + H₂O","acid-base","exothermic",
      "Weak acid + strong base neutralisation. Product is a buffer salt.",
      ["Weak acid + strong base","Buffer salt formed","Vinegar contains acetic acid"],
      "inorganic",""),
    rxn("acid-hcl-nahco3","HCl + Sodium Bicarbonate",
      [reactant("HCl","Hydrochloric Acid",1),reactant("NaHCO₃","Sodium Bicarbonate",1)],
      [product("NaCl","Sodium Chloride","NaCl",1),product("H₂O","Water","H₂O",1),product("CO₂","Carbon Dioxide","CO₂",1)],
      "HCl + NaHCO₃ → NaCl + H₂O + CO₂↑","acid-base","exothermic",
      "Acid reacts with baking soda releasing CO₂. Basis of antacid action.",
      ["Immediate vigorous fizzing","Antacid tablets work by this reaction","CO₂ causes familiar fizz in baking"],
      "inorganic",""),
    rxn("acid-hno3-naoh","HNO₃ + NaOH",
      [reactant("HNO₃","Nitric Acid",1),reactant("NaOH","Sodium Hydroxide",1)],
      [product("NaNO₃","Sodium Nitrate","NaNO₃",1),product("H₂O","Water","H₂O",1)],
      "HNO₃ + NaOH → NaNO₃ + H₂O","acid-base","exothermic",
      "Strong acid-base neutralisation forming sodium nitrate (used in fertilisers).",
      ["Strong acid + strong base","Sodium nitrate used in fertilisers","Exothermic"],
      "inorganic",""),
    rxn("acid-h3po4-naoh","H₃PO₄ + NaOH",
      [reactant("H₃PO₄","Phosphoric Acid",1),reactant("NaOH","Sodium Hydroxide",3)],
      [product("Na₃PO₄","Sodium Phosphate","Na₃PO₄",1),product("H₂O","Water","H₂O",3)],
      "H₃PO₄ + 3NaOH → Na₃PO₄ + 3H₂O","acid-base","exothermic",
      "Triprotic phosphoric acid requires 3 moles NaOH per mole of acid.",
      ["Triprotic acid","Phosphate salts used in food additives","Stepwise neutralisation possible"],
      "inorganic",""),
    // ── Inorganic: Synthesis ──────────────────────────────────────────────
    rxn("synth-na-cl2","Synthesis of NaCl",
      [reactant("Na","Sodium",2),reactant("Cl₂","Chlorine",1)],
      [product("NaCl","Sodium Chloride","NaCl",2)],
      "2Na + Cl₂ → 2NaCl","synthesis","exothermic",
      "Sodium reacts vigorously with chlorine gas to form table salt (NaCl).",
      ["Brilliant orange-yellow flame","Dense white NaCl smoke","Example of ionic compound formation"],
      "inorganic",""),
    rxn("synth-fe-s","Iron + Sulfur",
      [reactant("Fe","Iron",1),reactant("S","Sulfur",1)],
      [product("FeS","Iron(II) Sulfide","FeS",1)],
      "Fe + S → FeS","synthesis","exothermic",
      "Iron and sulfur heated together form FeS. Classic mixture vs compound demo.",
      ["Requires heating to initiate","Product is non-magnetic unlike iron","FeS reacts with acid to give toxic H₂S"],
      "inorganic",""),
    rxn("synth-h2-cl2","H₂ + Cl₂",
      [reactant("H₂","Hydrogen",1),reactant("Cl₂","Chlorine",1)],
      [product("HCl","Hydrogen Chloride","HCl",2)],
      "H₂ + Cl₂ → 2HCl","synthesis","exothermic",
      "Hydrogen and chlorine react explosively in UV light to form HCl gas.",
      ["Explosive in sunlight","Triggered by UV light","HCl dissolves in water to form hydrochloric acid"],
      "inorganic",""),
    rxn("synth-cao-h2o","Quicklime + Water",
      [reactant("CaO","Calcium Oxide",1),reactant("H₂O","Water",1)],
      [product("Ca(OH)₂","Calcium Hydroxide","Ca(OH)₂",1)],
      "CaO + H₂O → Ca(OH)₂","synthesis","exothermic",
      "Quicklime reacts violently with water in a highly exothermic reaction forming slaked lime.",
      ["Extremely exothermic, reaches 150°C","Slaked lime used in building mortar","Forms limewater when dissolved"],
      "inorganic",""),
    rxn("synth-so3-h2o","SO₃ + H₂O",
      [reactant("SO₃","Sulfur Trioxide",1),reactant("H₂O","Water",1)],
      [product("H₂SO₄","Sulfuric Acid","H₂SO₄",1)],
      "SO₃ + H₂O → H₂SO₄","synthesis","exothermic",
      "SO₃ reacts with water to form sulfuric acid. Final step in Contact Process.",
      ["Extremely exothermic","SO₃ absorbed in H₂SO₄ not water directly in industry","Forms oleum (H₂S₂O₇)"],
      "inorganic",""),
    rxn("synth-no-o2","NO + O₂",
      [reactant("NO","Nitric Oxide",2),reactant("O₂","Oxygen",1)],
      [product("NO₂","Nitrogen Dioxide","NO₂",2)],
      "2NO + O₂ → 2NO₂","synthesis","exothermic",
      "Nitric oxide oxidises in air to form brown nitrogen dioxide. Part of Ostwald Process.",
      ["Brown NO₂ gas formed","Part of Ostwald Process for HNO₃","Contributes to smog formation"],
      "inorganic",""),
    // ── Inorganic: Decomposition ──────────────────────────────────────────
    rxn("decomp-h2o-electrolysis","Electrolysis of Water",
      [reactant("H₂O","Water",2)],
      [product("H₂","Hydrogen","H₂",2),product("O₂","Oxygen","O₂",1)],
      "2H₂O → 2H₂ + O₂","decomposition","endothermic",
      "Water splits into hydrogen and oxygen by electrical energy. Key for green hydrogen.",
      ["H₂ at cathode, O₂ at anode","H₂:O₂ ratio = 2:1 by volume","Used to produce green hydrogen fuel"],
      "inorganic",""),
    rxn("decomp-caco3","Thermal Decomposition of CaCO₃",
      [reactant("CaCO₃","Calcium Carbonate",1)],
      [product("CaO","Calcium Oxide","CaO",1),product("CO₂","Carbon Dioxide","CO₂",1)],
      "CaCO₃ → CaO + CO₂","decomposition","endothermic",
      "Limestone decomposes above 840°C to quicklime and CO₂. First step in cement making.",
      ["Requires >840°C","CO₂ turns limewater milky","Industrial basis of cement"],
      "inorganic",""),
    rxn("decomp-h2o2","Decomposition of H₂O₂",
      [reactant("H₂O₂","Hydrogen Peroxide",2)],
      [product("H₂O","Water","H₂O",2),product("O₂","Oxygen","O₂",1)],
      "2H₂O₂ → 2H₂O + O₂","decomposition","exothermic",
      "H₂O₂ decomposes into water and oxygen, catalysed by MnO₂ or catalase enzyme.",
      ["MnO₂ or catalase catalyses","Elephant toothpaste demo","Glowing splint reignites in O₂"],
      "inorganic",""),
    rxn("decomp-kclo3","Decomposition of KClO₃",
      [reactant("KClO₃","Potassium Chlorate",2)],
      [product("KCl","Potassium Chloride","KCl",2),product("O₂","Oxygen","O₂",3)],
      "2KClO₃ → 2KCl + 3O₂","decomposition","endothermic",
      "Potassium chlorate decomposes on heating, generating oxygen gas. Catalysed by MnO₂.",
      ["Requires >400°C","MnO₂ lowers required temperature","Explosion risk with reducing agents"],
      "inorganic",""),
    rxn("decomp-nahco3","Decomposition of Baking Soda",
      [reactant("NaHCO₃","Sodium Bicarbonate",2)],
      [product("Na₂CO₃","Sodium Carbonate","Na₂CO₃",1),product("H₂O","Water","H₂O",1),product("CO₂","Carbon Dioxide","CO₂",1)],
      "2NaHCO₃ → Na₂CO₃ + H₂O + CO₂","decomposition","endothermic",
      "Baking soda decomposes on heating releasing CO₂. Makes baked goods rise.",
      ["CO₂ makes cakes and bread rise","Starts at ~50°C","Also used in fire extinguishers"],
      "inorganic",""),
    rxn("decomp-pb-no3","Decomposition of Lead Nitrate",
      [reactant("Pb(NO₃)₂","Lead Nitrate",2)],
      [product("PbO","Lead Oxide","PbO",2),product("NO₂","Nitrogen Dioxide","NO₂",4),product("O₂","Oxygen","O₂",1)],
      "2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂","decomposition","endothermic",
      "Lead nitrate releases brown toxic NO₂ on strong heating.",
      ["Brown NO₂ fumes visible","Toxic – perform in fume hood","White solid turns yellow PbO"],
      "inorganic",""),
    // ── Inorganic: Displacement ───────────────────────────────────────────
    rxn("disp-fe-cuso4","Iron Displaces Copper",
      [reactant("Fe","Iron",1),reactant("CuSO₄","Copper Sulfate",1)],
      [product("FeSO₄","Iron(II) Sulfate","FeSO₄",1),product("Cu","Copper","Cu",1)],
      "Fe + CuSO₄ → FeSO₄ + Cu","displacement","exothermic",
      "Iron displaces copper from copper sulfate. Blue solution fades and copper deposits.",
      ["Blue fades to pale green FeSO₄","Copper coats the iron","Classic reactivity series demo"],
      "inorganic",""),
    rxn("disp-zn-cuso4","Zinc Displaces Copper",
      [reactant("Zn","Zinc",1),reactant("CuSO₄","Copper Sulfate",1)],
      [product("ZnSO₄","Zinc Sulfate","ZnSO₄",1),product("Cu","Copper","Cu",1)],
      "Zn + CuSO₄ → ZnSO₄ + Cu","displacement","exothermic",
      "Zinc displaces copper from copper sulfate solution.",
      ["Blue fades, zinc more reactive than copper","Copper deposits on zinc","ZnSO₄ solution is colourless"],
      "inorganic",""),
    rxn("disp-zn-hcl","Zinc + HCl",
      [reactant("Zn","Zinc",1),reactant("HCl","Hydrochloric Acid",2)],
      [product("ZnCl₂","Zinc Chloride","ZnCl₂",1),product("H₂","Hydrogen","H₂",1)],
      "Zn + 2HCl → ZnCl₂ + H₂","displacement","exothermic",
      "Zinc reacts with HCl producing zinc chloride and hydrogen gas.",
      ["Steady H₂ bubbles","Zinc above hydrogen in reactivity","Squeaky pop confirms hydrogen"],
      "inorganic",""),
    rxn("disp-mg-hcl","Magnesium + HCl",
      [reactant("Mg","Magnesium",1),reactant("HCl","Hydrochloric Acid",2)],
      [product("MgCl₂","Magnesium Chloride","MgCl₂",1),product("H₂","Hydrogen","H₂",1)],
      "Mg + 2HCl → MgCl₂ + H₂","displacement","exothermic",
      "Magnesium reacts vigorously with HCl, more reactive than zinc or iron.",
      ["Vigorous fizzing","Mg ribbon dissolves rapidly","Tube warms noticeably"],
      "inorganic",""),
    rxn("disp-fe-hcl","Iron + HCl",
      [reactant("Fe","Iron",1),reactant("HCl","Hydrochloric Acid",2)],
      [product("FeCl₂","Iron(II) Chloride","FeCl₂",1),product("H₂","Hydrogen","H₂",1)],
      "Fe + 2HCl → FeCl₂ + H₂","displacement","exothermic",
      "Iron reacts slowly with HCl producing pale green FeCl₂ solution and hydrogen.",
      ["Slower than Mg or Zn","Solution turns pale green","Demonstrates reactivity order"],
      "inorganic",""),
    rxn("disp-cu-agno3","Copper Displaces Silver",
      [reactant("Cu","Copper",1),reactant("AgNO₃","Silver Nitrate",2)],
      [product("Cu(NO₃)₂","Copper Nitrate","Cu(NO₃)₂",1),product("Ag","Silver","Ag",2)],
      "Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag","displacement","exothermic",
      "Copper displaces silver from silver nitrate; beautiful silver crystals form.",
      ["Silver crystals grow on copper wire","Solution turns blue (Cu²⁺)","Cu more reactive than Ag"],
      "inorganic",""),
    rxn("disp-al-fe2o3","Thermite Reaction",
      [reactant("Al","Aluminium",2),reactant("Fe₂O₃","Iron(III) Oxide",1)],
      [product("Al₂O₃","Aluminium Oxide","Al₂O₃",1),product("Fe","Iron","Fe",2)],
      "2Al + Fe₂O₃ → Al₂O₃ + 2Fe","displacement","exothermic",
      "Al displaces Fe from Fe₂O₃ at over 2500°C. Used to weld railway tracks.",
      ["Temperature exceeds 2500°C","Molten iron produced","Used to weld railway tracks"],
      "inorganic",""),
    rxn("disp-na-h2o","Sodium + Water",
      [reactant("Na","Sodium",2),reactant("H₂O","Water",2)],
      [product("NaOH","Sodium Hydroxide","NaOH",2),product("H₂","Hydrogen","H₂",1)],
      "2Na + 2H₂O → 2NaOH + H₂↑","displacement","exothermic",
      "Sodium reacts vigorously with water producing NaOH and H₂. Heat ignites the hydrogen.",
      ["Sodium skitters across water","Yellow sodium flame","Solution becomes strongly alkaline"],
      "inorganic",""),
    rxn("disp-ca-h2o","Calcium + Water",
      [reactant("Ca","Calcium",1),reactant("H₂O","Water",2)],
      [product("Ca(OH)₂","Calcium Hydroxide","Ca(OH)₂",1),product("H₂","Hydrogen","H₂",1)],
      "Ca + 2H₂O → Ca(OH)₂ + H₂↑","displacement","exothermic",
      "Calcium reacts steadily with water producing limewater and hydrogen.",
      ["Steady H₂ bubbles","Solution turns milky Ca(OH)₂","Less vigorous than sodium"],
      "inorganic",""),
    // ── Inorganic: Precipitation & Redox ─────────────────────────────────
    rxn("precip-agcl","Silver Chloride Precipitation",
      [reactant("AgNO₃","Silver Nitrate",1),reactant("NaCl","Sodium Chloride",1)],
      [product("AgCl","Silver Chloride","AgCl",1),product("NaNO₃","Sodium Nitrate","NaNO₃",1)],
      "AgNO₃ + NaCl → AgCl↓ + NaNO₃","precipitation","exothermic",
      "Insoluble AgCl precipitates. Used to test for chloride ions. Basis of photography.",
      ["Immediate white precipitate","Turns purple-grey in light","Halide ion test","Silver halide photography"],
      "inorganic",""),
    rxn("precip-baso4","Barium Sulfate Precipitation",
      [reactant("BaCl₂","Barium Chloride",1),reactant("H₂SO₄","Sulfuric Acid",1)],
      [product("BaSO₄","Barium Sulfate","BaSO₄",1),product("HCl","Hydrochloric Acid","HCl",2)],
      "BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl","precipitation","exothermic",
      "Dense white BaSO₄ precipitate identifies sulfate ions. Used as X-ray contrast agent.",
      ["Dense white precipitate","Insoluble in dilute acids, confirms sulfate","Used in barium meal X-rays"],
      "inorganic",""),
    rxn("redox-fe-rusting","Rusting of Iron",
      [reactant("Fe","Iron",4),reactant("O₂","Oxygen",3),reactant("H₂O","Water",2)],
      [product("Fe₂O₃·H₂O","Hydrated Iron Oxide (Rust)","Fe₂O₃·H₂O",2)],
      "4Fe + 3O₂ + 2H₂O → 2Fe₂O₃·H₂O","oxidation","exothermic",
      "Iron corrodes slowly in oxygen and water to form rust. Both are required.",
      ["Requires both O₂ AND water","Salt water speeds rusting","Costs billions annually"],
      "inorganic",""),
    rxn("redox-cl2-ki","Chlorine Displaces Iodide",
      [reactant("Cl₂","Chlorine",1),reactant("KI","Potassium Iodide",2)],
      [product("I₂","Iodine","I₂",1),product("KCl","Potassium Chloride","KCl",2)],
      "Cl₂ + 2KI → I₂ + 2KCl","redox","exothermic",
      "Cl₂ is a stronger oxidising agent than I₂, displacing iodide to form iodine.",
      ["Solution turns orange-brown","Deep blue-black with starch","Demonstrates halogen reactivity trend"],
      "inorganic",""),
    rxn("redox-mno2-hcl","MnO₂ + HCl → Cl₂",
      [reactant("MnO₂","Manganese Dioxide",1),reactant("HCl","Hydrochloric Acid",4)],
      [product("MnCl₂","Manganese Chloride","MnCl₂",1),product("Cl₂","Chlorine","Cl₂",1),product("H₂O","Water","H₂O",2)],
      "MnO₂ + 4HCl → MnCl₂ + Cl₂↑ + 2H₂O","redox","exothermic",
      "MnO₂ oxidises HCl to generate chlorine gas. Common lab method for Cl₂.",
      ["Pale yellow-green Cl₂ gas","Bleaches damp litmus white then red","Historic lab Cl₂ generation"],
      "inorganic",""),
    rxn("redox-kmno4-fe","KMnO₄ Titration with Fe²⁺",
      [reactant("KMnO₄","Potassium Permanganate",1),reactant("FeSO₄","Iron(II) Sulfate",5),reactant("H₂SO₄","Sulfuric Acid",4)],
      [product("MnSO₄","Manganese Sulfate","MnSO₄",1),product("Fe₂(SO₄)₃","Iron(III) Sulfate","Fe₂(SO₄)₃",1),product("K₂SO₄","Potassium Sulfate","K₂SO₄",1),product("H₂O","Water","H₂O",4)],
      "2KMnO₄ + 10FeSO₄ + 8H₂SO₄ → 2MnSO₄ + 5Fe₂(SO₄)₃ + K₂SO₄ + 8H₂O","redox","exothermic",
      "KMnO₄ oxidises Fe²⁺ to Fe³⁺. Purple KMnO₄ decolourises at endpoint. Analytical titration.",
      ["Purple turns colourless at endpoint","Self-indicating titration","Used to determine Fe²⁺ concentration"],
      "inorganic",""),
    // ── Industrial ────────────────────────────────────────────────────────
    rxn("ind-haber","Haber Process – Ammonia Synthesis",
      [reactant("N₂","Nitrogen",1),reactant("H₂","Hydrogen",3)],
      [product("NH₃","Ammonia","NH₃",2)],
      "N₂ + 3H₂ ⇌ 2NH₃","synthesis","exothermic",
      "The Haber process synthesises ammonia at 400-500°C, 150-300 atm over iron catalyst.",
      ["Feeds ~half world population via fertilisers","Iron catalyst with K₂O promoter","Reversible equilibrium – optimised conditions"],
      "industrial","Haber Process"),
    rxn("ind-contact","Contact Process – SO₃ Synthesis",
      [reactant("SO₂","Sulfur Dioxide",2),reactant("O₂","Oxygen",1)],
      [product("SO₃","Sulfur Trioxide","SO₃",2)],
      "2SO₂ + O₂ ⇌ 2SO₃","synthesis","exothermic",
      "V₂O₅ catalyst at ~450°C converts SO₂ to SO₃. Key step in H₂SO₄ manufacture.",
      ["V₂O₅ catalyst","450°C and 1-2 atm","SO₃ absorbed in H₂SO₄ to form oleum"],
      "industrial","Contact Process"),
    rxn("ind-solvay","Solvay Process – NaHCO₃ Formation",
      [reactant("NaCl","Sodium Chloride",1),reactant("NH₃","Ammonia",1),reactant("CO₂","Carbon Dioxide",1),reactant("H₂O","Water",1)],
      [product("NaHCO₃","Sodium Bicarbonate","NaHCO₃",1),product("NH₄Cl","Ammonium Chloride","NH₄Cl",1)],
      "NaCl + NH₃ + CO₂ + H₂O → NaHCO₃ + NH₄Cl","synthesis","exothermic",
      "The Solvay process produces soda ash (Na₂CO₃) from NaCl and CaCO₃ via NaHCO₃.",
      ["Ammonia recycled in the process","Na₂CO₃ made by heating NaHCO₃","Used in glass and soap manufacture"],
      "industrial","Solvay Process"),
    rxn("ind-ostwald","Ostwald Process – HNO₃ from NH₃",
      [reactant("NH₃","Ammonia",4),reactant("O₂","Oxygen",5)],
      [product("NO","Nitric Oxide","NO",4),product("H₂O","Water","H₂O",6)],
      "4NH₃ + 5O₂ → 4NO + 6H₂O","oxidation","exothermic",
      "NH₃ oxidised over Pt/Rh catalyst at 900°C to NO. First step in Ostwald Process for HNO₃.",
      ["Pt/Rh gauze catalyst at ~900°C","NO then oxidised to NO₂, then HNO₃","Industrial basis of fertilisers and explosives"],
      "industrial","Ostwald Process"),
    rxn("ind-blast-furnace","Blast Furnace – Iron Extraction",
      [reactant("Fe₂O₃","Iron(III) Oxide",1),reactant("CO","Carbon Monoxide",3)],
      [product("Fe","Iron","Fe",2),product("CO₂","Carbon Dioxide","CO₂",3)],
      "Fe₂O₃ + 3CO → 2Fe + 3CO₂","reduction","exothermic",
      "Iron ore reduced by CO in blast furnace to produce molten pig iron. CO is produced from coke.",
      ["CO is the reducing agent","Temperature >1000°C","Molten pig iron collected at base","Slag (CaSiO₃) also formed"],
      "industrial",""),
    rxn("ind-hall-heroult","Hall-Héroult – Aluminium Extraction",
      [reactant("Al₂O₃","Aluminium Oxide",2)],
      [product("Al","Aluminium","Al",4),product("O₂","Oxygen","O₂",3)],
      "2Al₂O₃ → 4Al + 3O₂","decomposition","endothermic",
      "Al₂O₃ dissolved in molten cryolite electrolysed at 950°C to extract aluminium.",
      ["Al deposited at cathode","O₂ at anode burns carbon electrodes","Very energy intensive","Cryolite lowers melting point"],
      "industrial","Hall-Héroult Process"),
    rxn("ind-chlor-alkali","Chlor-Alkali Electrolysis",
      [reactant("NaCl","Sodium Chloride (brine)",2),reactant("H₂O","Water",2)],
      [product("Cl₂","Chlorine","Cl₂",1),product("H₂","Hydrogen","H₂",1),product("NaOH","Sodium Hydroxide","NaOH",2)],
      "2NaCl + 2H₂O → Cl₂ + H₂ + 2NaOH","decomposition","endothermic",
      "Electrolysis of brine produces three essential industrial chemicals: Cl₂, H₂, and NaOH.",
      ["Cl₂ at anode, H₂ at cathode","NaOH in bulk solution","All three products have major industrial uses"],
      "industrial",""),
    rxn("ind-cracking","Catalytic Cracking of Alkanes",
      [reactant("C₁₀H₂₂","Decane (long-chain alkane)",1)],
      [product("C₅H₁₂","Pentane","C₅H₁₂",1),product("C₅H₁₀","Pentene","C₅H₁₀",1)],
      "C₁₀H₂₂ → C₅H₁₂ + C₅H₁₀","decomposition","endothermic",
      "Long-chain hydrocarbons cracked over zeolite catalyst at 500°C to produce useful shorter chains.",
      ["Zeolite catalyst","~500°C","Produces alkenes useful for plastics","Converts heavy oil fractions to petrol"],
      "industrial",""),
    rxn("ind-steam-methane","Steam Methane Reforming",
      [reactant("CH₄","Methane",1),reactant("H₂O","Steam",1)],
      [product("CO","Carbon Monoxide","CO",1),product("H₂","Hydrogen","H₂",3)],
      "CH₄ + H₂O → CO + 3H₂","synthesis","endothermic",
      "Main industrial method for hydrogen production from natural gas over Ni catalyst at 700-900°C.",
      ["Ni catalyst at 700-900°C","Primary H₂ production method","CO further converted to CO₂ + H₂ in water-gas shift"],
      "industrial",""),
    rxn("ind-water-gas-shift","Water-Gas Shift Reaction",
      [reactant("CO","Carbon Monoxide",1),reactant("H₂O","Steam",1)],
      [product("CO₂","Carbon Dioxide","CO₂",1),product("H₂","Hydrogen","H₂",1)],
      "CO + H₂O ⇌ CO₂ + H₂","synthesis","exothermic",
      "CO reacts with steam to produce additional H₂. Part of industrial hydrogen and ammonia synthesis.",
      ["Fe₃O₄ or Cu catalyst","Increases H₂ yield","Removes toxic CO"],
      "industrial",""),
    // ── Electrochemical ───────────────────────────────────────────────────
    rxn("electro-daniell","Daniell Cell (Cu-Zn)",
      [reactant("Zn","Zinc",1),reactant("Cu²⁺","Copper ions",1)],
      [product("Zn²⁺","Zinc ions","Zn²⁺",1),product("Cu","Copper","Cu",1)],
      "Zn + Cu²⁺ → Zn²⁺ + Cu","redox","exothermic",
      "Zn anode oxidised, Cu²⁺ reduced at cathode. Cell voltage ~1.1 V. First practical galvanic cell.",
      ["EMF ~1.1 V","Zn oxidised (anode), Cu deposited (cathode)","First practical battery"],
      "electrochemical",""),
    rxn("electro-h2o","Electrolysis of Water",
      [reactant("H₂O","Water",2)],
      [product("H₂","Hydrogen","H₂",2),product("O₂","Oxygen","O₂",1)],
      "2H₂O → 2H₂ + O₂","decomposition","endothermic",
      "H₂O splits into H₂ at cathode and O₂ at anode under electrical current.",
      ["Minimum voltage 1.23 V (theoretical)","H₂:O₂ = 2:1 by volume","Green hydrogen production"],
      "electrochemical",""),
    rxn("electro-brine","Electrolysis of Brine",
      [reactant("NaCl","Sodium Chloride",2),reactant("H₂O","Water",2)],
      [product("Cl₂","Chlorine","Cl₂",1),product("H₂","Hydrogen","H₂",1),product("NaOH","Sodium Hydroxide","NaOH",2)],
      "2NaCl + 2H₂O → Cl₂ + H₂ + 2NaOH","decomposition","endothermic",
      "Electrolysis of brine (NaCl solution) produces Cl₂, H₂, and NaOH industrially.",
      ["Cl₂ used in PVC and bleach","H₂ used as fuel","NaOH used in soap and paper"],
      "electrochemical",""),
    rxn("electro-cu-refining","Electrorefining of Copper",
      [reactant("Cu (impure)","Impure Copper",1)],
      [product("Cu (pure)","Pure Copper","Cu",1)],
      "Cu(anode) → Cu²⁺ + 2e⁻; Cu²⁺ + 2e⁻ → Cu(cathode)","redox","endothermic",
      "Impure copper dissolved at anode, pure copper deposited at cathode. ~99.99% purity achieved.",
      ["Anode mud contains precious metals","~99.99% pure copper","Used for electrical cables"],
      "electrochemical",""),
    rxn("electro-std-h2","Standard Hydrogen Electrode",
      [reactant("H⁺","Hydrogen ions",2),reactant("e⁻","Electrons",2)],
      [product("H₂","Hydrogen","H₂",1)],
      "2H⁺ + 2e⁻ → H₂ (E° = 0.00 V)","redox","neutral",
      "The standard hydrogen electrode (SHE) is the reference point for all electrode potential measurements.",
      ["E° = 0.00 V by definition","Pt electrode in 1M H⁺, H₂ at 1 atm","All other potentials measured relative to SHE"],
      "electrochemical",""),
    rxn("electro-zn-half","Zinc Half-Cell",
      [reactant("Zn²⁺","Zinc ions",1),reactant("e⁻","Electrons",2)],
      [product("Zn","Zinc","Zn",1)],
      "Zn²⁺ + 2e⁻ → Zn (E° = −0.76 V)","redox","neutral",
      "Zinc has a standard reduction potential of −0.76 V; it is a good reducing agent.",
      ["E° = −0.76 V","Negative: Zn prefers to be oxidised","Strong reducing agent in galvanic cells"],
      "electrochemical",""),
    rxn("electro-cu-half","Copper Half-Cell",
      [reactant("Cu²⁺","Copper ions",1),reactant("e⁻","Electrons",2)],
      [product("Cu","Copper","Cu",1)],
      "Cu²⁺ + 2e⁻ → Cu (E° = +0.34 V)","redox","neutral",
      "Copper has a standard reduction potential of +0.34 V; it is easily reduced.",
      ["E° = +0.34 V","Positive: Cu²⁺ prefers to be reduced","Acts as cathode in galvanic cells"],
      "electrochemical",""),
    rxn("electro-fe-half","Iron Half-Cell",
      [reactant("Fe²⁺","Iron(II) ions",1),reactant("e⁻","Electrons",2)],
      [product("Fe","Iron","Fe",1)],
      "Fe²⁺ + 2e⁻ → Fe (E° = −0.44 V)","redox","neutral",
      "Iron standard reduction potential −0.44 V. Iron is a moderate reducing agent.",
      ["E° = −0.44 V","Negative: Fe prefers to be oxidised","Relevant to rusting and galvanic corrosion"],
      "electrochemical",""),
    rxn("electro-mno4","Permanganate Reduction",
      [reactant("MnO₄⁻","Permanganate ion",1),reactant("H⁺","Hydrogen ions",8),reactant("e⁻","Electrons",5)],
      [product("Mn²⁺","Manganese(II) ion","Mn²⁺",1),product("H₂O","Water","H₂O",4)],
      "MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O (E° = +1.51 V)","redox","neutral",
      "Permanganate is a strong oxidising agent in acid. Used in redox titrations.",
      ["E° = +1.51 V, strong oxidiser","Purple MnO₄⁻ turns colourless Mn²⁺","Used in redox titrations"],
      "electrochemical",""),
    rxn("electro-cr2o7","Dichromate Reduction",
      [reactant("Cr₂O₇²⁻","Dichromate ion",1),reactant("H⁺","Hydrogen ions",14),reactant("e⁻","Electrons",6)],
      [product("Cr³⁺","Chromium(III) ion","Cr³⁺",2),product("H₂O","Water","H₂O",7)],
      "Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O (E° = +1.33 V)","redox","neutral",
      "Dichromate is a strong oxidising agent in acid solution. Orange Cr₂O₇²⁻ turns green Cr³⁺.",
      ["E° = +1.33 V","Orange dichromate → green chromium(III)","Used in breathalyser tests (historically)"],
      "electrochemical",""),
    // ── Organic: Alkanes ──────────────────────────────────────────────────
    rxn("org-ch4-cl2-sub","Free Radical Substitution of Methane",
      [reactant("CH₄","Methane",1),reactant("Cl₂","Chlorine",1)],
      [product("CH₃Cl","Chloromethane","CH₃Cl",1),product("HCl","Hydrogen Chloride","HCl",1)],
      "CH₄ + Cl₂ → CH₃Cl + HCl (UV light)","substitution","exothermic",
      "Free radical chain reaction: Cl• radicals replace H atoms. Initiation by UV light.",
      ["Requires UV light to initiate","Free radical chain mechanism","Multiple substitutions possible"],
      "organic","Free Radical Substitution"),
    rxn("org-ethane-br2","Bromination of Ethane",
      [reactant("C₂H₆","Ethane",1),reactant("Br₂","Bromine",1)],
      [product("C₂H₅Br","Bromoethane","C₂H₅Br",1),product("HBr","Hydrogen Bromide","HBr",1)],
      "C₂H₆ + Br₂ → C₂H₅Br + HBr (UV light)","substitution","exothermic",
      "Free radical substitution of ethane with bromine under UV light.",
      ["UV light required","Free radical mechanism","Less reactive than chlorination"],
      "organic",""),
    // ── Organic: Alkenes ──────────────────────────────────────────────────
    rxn("org-ethene-h2","Hydrogenation of Ethene",
      [reactant("C₂H₄","Ethene",1),reactant("H₂","Hydrogen",1)],
      [product("C₂H₆","Ethane","C₂H₆",1)],
      "C₂H₄ + H₂ → C₂H₆ (Ni catalyst, 150°C)","addition","exothermic",
      "Hydrogen adds across the double bond (electrophilic addition). Used in margarine hardening.",
      ["Ni catalyst at 150°C","Used to harden vegetable oils (margarine)","Decolourises bromine water"],
      "organic",""),
    rxn("org-ethene-br2","Bromination of Ethene",
      [reactant("C₂H₄","Ethene",1),reactant("Br₂","Bromine",1)],
      [product("C₂H₄Br₂","1,2-Dibromoethane","C₂H₄Br₂",1)],
      "C₂H₄ + Br₂ → CH₂BrCH₂Br","addition","exothermic",
      "Bromine adds across the C=C double bond. Orange/brown bromine water is decolourised.",
      ["Decolourises bromine water instantly","Test for C=C double bond","Electrophilic addition mechanism"],
      "organic",""),
    rxn("org-ethene-hbr","HBr Addition to Propene",
      [reactant("CH₃CH=CH₂","Propene",1),reactant("HBr","Hydrogen Bromide",1)],
      [product("CH₃CHBrCH₃","2-Bromopropane","CH₃CHBrCH₃",1)],
      "CH₃CH=CH₂ + HBr → CH₃CHBrCH₃ (major)","addition","exothermic",
      "Markovnikov addition: H adds to carbon with more H atoms (less substituted C).",
      ["Markovnikov's rule applies","Major product is 2-bromopropane","Carbocation intermediate stabilised"],
      "organic","Markovnikov Addition"),
    rxn("org-ethene-h2o","Hydration of Ethene",
      [reactant("C₂H₄","Ethene",1),reactant("H₂O","Steam",1)],
      [product("C₂H₅OH","Ethanol","C₂H₅OH",1)],
      "C₂H₄ + H₂O → C₂H₅OH (H₃PO₄, 300°C, 60 atm)","addition","exothermic",
      "Industrial production of ethanol. Ethene reacts with steam over H₃PO₄ catalyst.",
      ["H₃PO₄ catalyst","300°C and 60 atm","Industrial ethanol production","Addition of water across C=C"],
      "organic",""),
    rxn("org-ethene-poly","Polymerisation of Ethene",
      [reactant("nC₂H₄","Ethene (many units)",1)],
      [product("(-CH₂-CH₂-)ₙ","Polyethylene","(C₂H₄)ₙ",1)],
      "nCH₂=CH₂ → (-CH₂-CH₂-)ₙ","addition-polymerisation","exothermic",
      "Ethene monomers link up under high pressure and temperature to form polyethylene.",
      ["Addition polymerisation","High pressure and temperature","Produces HDPE or LDPE depending on conditions"],
      "organic",""),
    rxn("org-propene-poly","Polymerisation of Propene",
      [reactant("nC₃H₆","Propene",1)],
      [product("(-CH₂-CH(CH₃)-)ₙ","Polypropylene","(C₃H₆)ₙ",1)],
      "nCH₂=CHCH₃ → (-CH₂CH(CH₃)-)ₙ","addition-polymerisation","exothermic",
      "Propene polymerises to form polypropylene, used in packaging and fibres.",
      ["Addition polymerisation","Ziegler-Natta catalyst","Used in plastics and fibres"],
      "organic",""),
    // ── Organic: Alkynes ──────────────────────────────────────────────────
    rxn("org-ethyne-h2","Hydrogenation of Ethyne",
      [reactant("C₂H₂","Ethyne (Acetylene)",1),reactant("H₂","Hydrogen",2)],
      [product("C₂H₆","Ethane","C₂H₆",1)],
      "C₂H₂ + 2H₂ → C₂H₆","addition","exothermic",
      "Complete hydrogenation of acetylene to ethane. Partial hydrogenation gives ethene.",
      ["Pd or Pt catalyst","Partial hydrogenation (Lindlar) gives cis-alkene","Used in acetylene chemistry"],
      "organic",""),
    rxn("org-ethyne-br2","Bromination of Ethyne",
      [reactant("C₂H₂","Ethyne",1),reactant("Br₂","Bromine",2)],
      [product("C₂H₂Br₄","1,1,2,2-Tetrabromoethane","C₂H₂Br₄",1)],
      "C₂H₂ + 2Br₂ → CHBr₂CHBr₂","addition","exothermic",
      "Two moles of bromine add across the triple bond in two steps.",
      ["Decolourises bromine water (two equivalents)","Triple bond more reactive than double","Via vinyl dibromide intermediate"],
      "organic",""),
    rxn("org-ethyne-hcl","HCl Addition to Ethyne",
      [reactant("C₂H₂","Ethyne",1),reactant("HCl","Hydrogen Chloride",1)],
      [product("CH₂=CHCl","Vinyl Chloride (Chloroethene)","CH₂CHCl",1)],
      "C₂H₂ + HCl → CH₂=CHCl","addition","exothermic",
      "HgCl₂ catalyst adds HCl across the triple bond. Product is vinyl chloride (PVC monomer).",
      ["HgCl₂ catalyst","Product is PVC monomer","Industrial route to vinyl chloride"],
      "organic",""),
    // ── Organic: Aromatic ─────────────────────────────────────────────────
    rxn("org-benzene-br2","Bromination of Benzene",
      [reactant("C₆H₆","Benzene",1),reactant("Br₂","Bromine",1)],
      [product("C₆H₅Br","Bromobenzene","C₆H₅Br",1),product("HBr","Hydrogen Bromide","HBr",1)],
      "C₆H₆ + Br₂ → C₆H₅Br + HBr (FeBr₃)","substitution","exothermic",
      "Electrophilic aromatic substitution. FeBr₃ Lewis acid catalyst generates Br⁺ electrophile.",
      ["FeBr₃ catalyst","Electrophilic aromatic substitution (EAS)","Bromine water NOT decolourised (unlike alkenes)"],
      "organic",""),
    rxn("org-benzene-no2","Nitration of Benzene",
      [reactant("C₆H₆","Benzene",1),reactant("HNO₃","Nitric Acid",1)],
      [product("C₆H₅NO₂","Nitrobenzene","C₆H₅NO₂",1),product("H₂O","Water","H₂O",1)],
      "C₆H₆ + HNO₃ → C₆H₅NO₂ + H₂O (H₂SO₄, 50°C)","substitution","exothermic",
      "Nitration of benzene. H₂SO₄ generates the NO₂⁺ nitronium ion electrophile.",
      ["Conc. H₂SO₄ catalyst","NO₂⁺ (nitronium ion) electrophile","Kept below 50°C to prevent dinitration"],
      "organic",""),
    rxn("org-benzene-h2so4","Sulfonation of Benzene",
      [reactant("C₆H₆","Benzene",1),reactant("H₂SO₄","Sulfuric Acid",1)],
      [product("C₆H₅SO₃H","Benzenesulfonic Acid","C₆H₅SO₃H",1)],
      "C₆H₆ + H₂SO₄(fuming) → C₆H₅SO₃H + H₂O","substitution","exothermic",
      "Sulfonation of benzene using fuming sulfuric acid (oleum). Reversible at high temperature.",
      ["Fuming H₂SO₄ (oleum)","Reversible reaction","Used to make detergents and dyes"],
      "organic",""),
    rxn("org-friedel-crafts-alkyl","Friedel-Crafts Alkylation",
      [reactant("C₆H₆","Benzene",1),reactant("CH₃Cl","Chloromethane",1)],
      [product("C₆H₅CH₃","Toluene","C₆H₅CH₃",1),product("HCl","Hydrogen Chloride","HCl",1)],
      "C₆H₆ + CH₃Cl → C₆H₅CH₃ + HCl (AlCl₃)","substitution","exothermic",
      "AlCl₃ Lewis acid generates carbocation electrophile for EAS to give toluene.",
      ["AlCl₃ Lewis acid catalyst","Carbocation electrophile","Produces alkylbenzenes"],
      "organic","Friedel-Crafts Alkylation"),
    rxn("org-friedel-crafts-acyl","Friedel-Crafts Acylation",
      [reactant("C₆H₆","Benzene",1),reactant("CH₃COCl","Acetyl Chloride",1)],
      [product("C₆H₅COCH₃","Acetophenone","C₆H₅COCH₃",1),product("HCl","Hydrogen Chloride","HCl",1)],
      "C₆H₆ + CH₃COCl → C₆H₅COCH₃ + HCl (AlCl₃)","substitution","exothermic",
      "AlCl₃ generates acylium ion CH₃CO⁺. Gives ketone product (no rearrangement unlike alkylation).",
      ["AlCl₃ catalyst","Acylium ion electrophile","No carbocation rearrangement","Widely used in organic synthesis"],
      "organic","Friedel-Crafts Acylation"),
    rxn("org-diels-alder","Diels-Alder Reaction",
      [reactant("C₄H₆","1,3-Butadiene",1),reactant("C₂H₄","Ethene (dienophile)",1)],
      [product("C₆H₁₀","Cyclohexene","C₆H₁₀",1)],
      "CH₂=CH-CH=CH₂ + CH₂=CH₂ → cyclohexene","cycloaddition","exothermic",
      "Concerted [4+2] cycloaddition between a diene and dienophile. No catalyst needed. Stereospecific.",
      ["Concerted [4+2] cycloaddition","Stereospecific syn addition","Electron-poor dienophile reacts faster","Key in natural product synthesis"],
      "organic","Diels-Alder Reaction"),
    // ── Organic: Alcohols ─────────────────────────────────────────────────
    rxn("org-ethanol-oxidation","Oxidation of Ethanol",
      [reactant("C₂H₅OH","Ethanol",1),reactant("O","[O] (oxidant)",2)],
      [product("CH₃COOH","Acetic Acid","CH₃COOH",1)],
      "C₂H₅OH → CH₃CHO → CH₃COOH (K₂Cr₂O₇/H₂SO₄)","oxidation","exothermic",
      "Ethanol oxidised via acetaldehyde to acetic acid. Orange dichromate turns green.",
      ["Orange Cr₂O₇²⁻ turns green Cr³⁺","Via aldehyde intermediate","Breathalyser test based on this"],
      "organic",""),
    rxn("org-ethanol-dehydration","Dehydration of Ethanol",
      [reactant("C₂H₅OH","Ethanol",1)],
      [product("C₂H₄","Ethene","C₂H₄",1),product("H₂O","Water","H₂O",1)],
      "C₂H₅OH → C₂H₄ + H₂O (H₂SO₄, 170°C)","elimination","endothermic",
      "Conc. H₂SO₄ at 170°C eliminates water to form ethene. E2 mechanism at high temperature.",
      ["Conc. H₂SO₄ at 170°C","Elimination reaction","Reverse of hydration","Produces alkene (ethene)"],
      "organic",""),
    rxn("org-esterification","Fischer Esterification",
      [reactant("CH₃COOH","Acetic Acid",1),reactant("C₂H₅OH","Ethanol",1)],
      [product("CH₃COOC₂H₅","Ethyl Acetate","CH₃COOC₂H₅",1),product("H₂O","Water","H₂O",1)],
      "CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O (H⁺)","esterification","exothermic",
      "Reversible acid-catalysed reaction forming ester and water. Equilibrium driven right by excess alcohol or removing water.",
      ["H₂SO₄ catalyst","Reversible equilibrium","Fruity smell of ethyl acetate","Drive forward by excess alcohol or removing water"],
      "organic","Fischer Esterification"),
    rxn("org-saponification","Saponification (Soap Making)",
      [reactant("(RCOO)₃C₃H₅","Triglyceride (Fat/Oil)",1),reactant("NaOH","Sodium Hydroxide",3)],
      [product("3RCOONa","Soap (Sodium Carboxylate)","RCOONa",3),product("C₃H₈O₃","Glycerol","C₃H₅(OH)₃",1)],
      "(RCOO)₃C₃H₅ + 3NaOH → 3RCOONa + C₃H₅(OH)₃","hydrolysis","exothermic",
      "Base hydrolysis of triglyceride (fat) with NaOH produces soap and glycerol.",
      ["Hot NaOH with fat/oil","Soap is sodium carboxylate","Glycerol by-product used in cosmetics","Basis of soap making"],
      "organic","Saponification"),
    // ── Organic: Aldehydes & Ketones ──────────────────────────────────────
    rxn("org-aldol","Aldol Condensation",
      [reactant("CH₃CHO","Acetaldehyde",2)],
      [product("CH₃CH(OH)CH₂CHO","Aldol","CH₃CH(OH)CH₂CHO",1)],
      "2CH₃CHO → CH₃CH(OH)CH₂CHO (base)","condensation","exothermic",
      "Base-catalysed self-condensation of aldehydes. α-carbon attacked. Key C-C bond forming reaction.",
      ["Base catalyst (NaOH)","α-carbon acts as nucleophile","Enolate ion intermediate","Key C-C bond forming reaction in synthesis"],
      "organic","Aldol Condensation"),
    rxn("org-cannizzaro","Cannizzaro Reaction",
      [reactant("HCHO","Formaldehyde (non-α-H aldehyde)",2)],
      [product("CH₃OH","Methanol","CH₃OH",1),product("HCOONa","Sodium Formate","HCOONa",1)],
      "2HCHO + NaOH → CH₃OH + HCOONa","disproportionation","neutral",
      "Disproportionation of aldehyde with no α-hydrogen in conc. base: one molecule oxidised, one reduced.",
      ["Only occurs with no α-H (e.g. HCHO, PhCHO)","One molecule oxidised, one reduced","Hydride transfer mechanism","NaOH required"],
      "organic","Cannizzaro Reaction"),
    rxn("org-silver-mirror","Silver Mirror (Tollens') Test",
      [reactant("RCHO","Aldehyde",1),reactant("[Ag(NH₃)₂]⁺","Tollens Reagent",2)],
      [product("RCOOH","Carboxylic Acid","RCOOH",1),product("Ag","Silver (mirror)","Ag",2)],
      "RCHO + 2[Ag(NH₃)₂]⁺ + 2OH⁻ → RCOOH + 2Ag↓ + 4NH₃","oxidation","exothermic",
      "Aldehyde reduces silver(I) to silver metal, forming a mirror. Distinguishes aldehydes from ketones.",
      ["Silver mirror on glass wall","Ketones do NOT give positive test","Tollens reagent = [Ag(NH₃)₂]OH","Distinguishes aldehydes from ketones"],
      "organic","Tollens' Test"),
    rxn("org-fehling","Fehling's Test",
      [reactant("RCHO","Aldehyde",1),reactant("Cu²⁺","Copper(II) (Fehling solution)",2)],
      [product("RCOOH","Carboxylic Acid","RCOOH",1),product("Cu₂O","Copper(I) Oxide","Cu₂O",1)],
      "RCHO + 2Cu²⁺ + 4OH⁻ → RCOOH + Cu₂O↓ + 2H₂O","oxidation","exothermic",
      "Blue Fehling solution is reduced to brick-red Cu₂O by aldehydes. Negative for ketones.",
      ["Blue solution → brick-red Cu₂O precipitate","Positive for aldehydes, negative for ketones","Used to test for reducing sugars"],
      "organic","Fehling's Test"),
    // ── Named Reactions ───────────────────────────────────────────────────
    rxn("named-sn2","SN2 Reaction",
      [reactant("CH₃Br","Bromomethane",1),reactant("OH⁻","Hydroxide ion",1)],
      [product("CH₃OH","Methanol","CH₃OH",1),product("Br⁻","Bromide ion","Br⁻",1)],
      "CH₃Br + OH⁻ → CH₃OH + Br⁻","nucleophilic substitution","exothermic",
      "Bimolecular nucleophilic substitution. Back-side attack gives inversion of configuration (Walden inversion).",
      ["Backside attack by nucleophile","Complete inversion of configuration","Rate = k[substrate][nucleophile]","Favoured at primary carbons"],
      "organic","SN2"),
    rxn("named-sn1","SN1 Reaction",
      [reactant("(CH₃)₃CBr","tert-Butyl Bromide",1),reactant("H₂O","Water",1)],
      [product("(CH₃)₃COH","tert-Butanol","(CH₃)₃COH",1),product("HBr","Hydrogen Bromide","HBr",1)],
      "(CH₃)₃CBr + H₂O → (CH₃)₃COH + HBr","nucleophilic substitution","exothermic",
      "Unimolecular substitution via carbocation intermediate. Favoured at tertiary carbons.",
      ["Carbocation intermediate","Rate = k[substrate] only","Can give racemisation","Favoured at tertiary carbons"],
      "organic","SN1"),
    rxn("named-e2","E2 Elimination",
      [reactant("CH₃CH₂Br","Bromoethane",1),reactant("KOH","Potassium Hydroxide",1)],
      [product("CH₂=CH₂","Ethene","C₂H₄",1),product("KBr","Potassium Bromide","KBr",1),product("H₂O","Water","H₂O",1)],
      "CH₃CH₂Br + KOH(alc) → CH₂=CH₂ + KBr + H₂O","elimination","exothermic",
      "Bimolecular elimination. Alcoholic KOH removes H and Br simultaneously (anti-periplanar). Gives alkene.",
      ["Alcoholic KOH (not aqueous)","Anti-periplanar H and leaving group","Rate = k[substrate][base]","Zaitsev rule: more substituted alkene preferred"],
      "organic","E2 Elimination"),
    rxn("named-e1","E1 Elimination",
      [reactant("(CH₃)₃CBr","tert-Butyl Bromide",1)],
      [product("(CH₃)₂C=CH₂","2-Methylpropene","C₄H₈",1),product("HBr","Hydrogen Bromide","HBr",1)],
      "(CH₃)₃CBr → (CH₃)₂C=CH₂ + HBr","elimination","endothermic",
      "Unimolecular elimination via carbocation. Tertiary carbons favoured. Heat favours elimination over substitution.",
      ["Carbocation intermediate","Rate = k[substrate]","Competes with SN1","Higher temperature favours E1 over SN1"],
      "organic","E1 Elimination"),
    rxn("named-grignard","Grignard Reaction",
      [reactant("RMgX","Grignard Reagent",1),reactant("RCHO","Aldehyde",1)],
      [product("RCH(OH)R'","Secondary Alcohol","RCH(OH)R'",1)],
      "RMgBr + R'CHO → R'CH(OH)R (after hydrolysis)","addition","exothermic",
      "Grignard reagent (RMgX) acts as carbanion nucleophile. Adds to carbonyls. Versatile C-C bond forming reaction.",
      ["Anhydrous ether solvent required","Carbanion nucleophile","Forms new C-C bond","Aldehyde → secondary alcohol","Ketone → tertiary alcohol"],
      "organic","Grignard Reaction"),
    rxn("named-gabriel","Gabriel Synthesis",
      [reactant("C₈H₅KNO₂","Potassium Phthalimide",1),reactant("RX","Alkyl Halide",1)],
      [product("RNH₂","Primary Amine","RNH₂",1)],
      "Phthalimide + RX → N-alkylphthalimide → RNH₂ + phthalic acid","substitution","exothermic",
      "Synthesis of primary amines without over-alkylation. Phthalimide anion alkylated, then hydrolysed.",
      ["Gives pure primary amines","No secondary/tertiary amine contamination","Requires acidic or basic hydrolysis","Named after Siegmund Gabriel"],
      "organic","Gabriel Synthesis"),
    rxn("named-kolbe","Kolbe's Electrolytic Synthesis",
      [reactant("RCOONa","Sodium Carboxylate",2)],
      [product("R-R","Alkane (dimer)","R-R",1),product("CO₂","Carbon Dioxide","CO₂",2)],
      "2RCOONa → R-R + 2CO₂ + 2Na⁺ (electrolysis)","oxidation","exothermic",
      "Electrolysis of carboxylate salt at anode: decarboxylation produces radicals that couple.",
      ["Electrolysis at anode","Radical coupling mechanism","Forms symmetric alkane","Named after Hermann Kolbe"],
      "organic","Kolbe's Synthesis"),
    rxn("named-reimer-tiemann","Reimer-Tiemann Reaction",
      [reactant("C₆H₅OH","Phenol",1),reactant("CHCl₃","Chloroform",1),reactant("NaOH","NaOH",1)],
      [product("HOC₆H₄CHO","Salicylaldehyde (2-hydroxybenzaldehyde)","HOC₆H₄CHO",1)],
      "C₆H₅OH + CHCl₃ + NaOH → HOC₆H₄CHO + 3HCl","formylation","exothermic",
      "Formylation of phenol ortho to OH group using CHCl₃ and NaOH. Dichlorocarbene intermediate.",
      ["Dichlorocarbene intermediate","Formylation ortho to OH","Named after Reimer and Tiemann","Used to make salicylaldehyde (antiseptic)"],
      "organic","Reimer-Tiemann Reaction"),
    rxn("named-hofmann","Hofmann Bromamide Reaction",
      [reactant("RCONH₂","Amide",1),reactant("Br₂","Bromine",1),reactant("NaOH","Sodium Hydroxide",4)],
      [product("RNH₂","Primary Amine","RNH₂",1),product("Na₂CO₃","Sodium Carbonate","Na₂CO₃",1)],
      "RCONH₂ + Br₂ + 4NaOH → RNH₂ + Na₂CO₃ + 2NaBr + 2H₂O","rearrangement","exothermic",
      "Amide degradation rearrangement producing amine with one fewer carbon. Nitrene intermediate.",
      ["Amine has one fewer C than amide","Nitrene intermediate","Reaction discovers the Hofmann rearrangement","Good for making primary amines"],
      "organic","Hofmann Rearrangement"),
    rxn("named-sandmeyer","Sandmeyer Reaction",
      [reactant("ArN₂⁺Cl⁻","Aryl Diazonium Chloride",1),reactant("CuCl","Copper(I) Chloride",1)],
      [product("ArCl","Chlorobenzene","C₆H₅Cl",1),product("N₂","Nitrogen","N₂",1)],
      "ArN₂⁺Cl⁻ + CuCl → ArCl + N₂ + CuCl","substitution","exothermic",
      "Aryl diazonium salt converted to aryl halide using Cu(I) halide catalyst. Versatile aromatic substitution.",
      ["Cu(I) catalyst","Diazonium salt precursor from aniline","Can make ArCl, ArBr, ArCN","Named after Traugott Sandmeyer"],
      "organic","Sandmeyer Reaction"),
    rxn("named-aldol-knoevenagel","Knoevenagel Condensation",
      [reactant("RCHO","Aldehyde",1),reactant("CH₂(COOR)₂","Malonic Ester",1)],
      [product("RCH=C(COOR)₂","Alkylidene Malonate","RCH=C(COOR)₂",1),product("H₂O","Water","H₂O",1)],
      "RCHO + CH₂(COOR)₂ → RCH=C(COOR)₂ + H₂O","condensation","exothermic",
      "Variation of aldol condensation. Amine base catalyses condensation of active methylene compound with aldehyde.",
      ["Amine base catalyst","Active methylene compound required","Related to aldol condensation","Named after Emil Knoevenagel"],
      "organic","Knoevenagel Condensation"),
    rxn("named-wittig","Wittig Reaction",
      [reactant("RCHO","Aldehyde",1),reactant("Ph₃P=CHR'","Phosphorus Ylide",1)],
      [product("RCH=CHR'","Alkene","RCH=CHR'",1),product("Ph₃P=O","Triphenylphosphine Oxide","Ph₃PO",1)],
      "RCHO + Ph₃P=CHR' → RCH=CHR' + Ph₃P=O","olefination","exothermic",
      "Phosphorus ylide reacts with carbonyl to form alkene with controlled geometry. Very useful in synthesis.",
      ["Triphenylphosphine oxide by-product","Controls alkene geometry","Stable ylide → trans, unstable → cis","Nobel Prize 1979 (Georg Wittig)"],
      "organic","Wittig Reaction"),
    rxn("named-beckmann","Beckmann Rearrangement",
      [reactant("R₂C=NOH","Ketoxime",1)],
      [product("RNHCOR'","Amide (lactam if cyclic)","RNHCOR'",1)],
      "R₂C=NOH → RNHCOR' (H⁺ catalyst)","rearrangement","exothermic",
      "Acid-catalysed rearrangement of ketoximes to amides. Cyclohexanone oxime → caprolactam (nylon-6 precursor).",
      ["H₂SO₄ or PCl₅ catalyst","Anti group migrates","Cyclohexanone oxime → caprolactam → Nylon-6","Named after Ernst Otto Beckmann"],
      "organic","Beckmann Rearrangement"),
    rxn("named-schmidt","Schmidt Reaction",
      [reactant("RCOOH","Carboxylic Acid",1),reactant("HN₃","Hydrazoic Acid",1)],
      [product("RNH₂","Primary Amine","RNH₂",1),product("CO₂","Carbon Dioxide","CO₂",1)],
      "RCOOH + HN₃ → RNH₂ + CO₂ + N₂ (H₂SO₄)","rearrangement","exothermic",
      "Acid converts carboxylic acid to amine via nitrene with loss of CO₂. One fewer carbon.",
      ["H₂SO₄ catalyst","Nitrene intermediate","One carbon lost as CO₂","Named after Karl Friedrich Schmidt"],
      "organic","Schmidt Reaction"),
    rxn("named-wacker","Wacker Oxidation",
      [reactant("C₂H₄","Ethylene",1),reactant("O₂","Oxygen",1)],
      [product("CH₃CHO","Acetaldehyde","CH₃CHO",1)],
      "C₂H₄ + O₂ → CH₃CHO (PdCl₂/CuCl₂)","oxidation","exothermic",
      "Palladium-catalysed oxidation of ethylene to acetaldehyde. Industrial process using O₂.",
      ["PdCl₂/CuCl₂ catalyst","CuCl₂ reoxidises Pd(0) to Pd(II)","Industrial source of acetaldehyde","Named after Wacker Chemie process"],
      "organic","Wacker Oxidation"),
    rxn("named-baeyer-villiger","Baeyer-Villiger Oxidation",
      [reactant("RCOR'","Ketone",1),reactant("m-CPBA","Peracid",1)],
      [product("RCOOR'","Ester","RCOOR'",1)],
      "RCOR' + RCO₃H → RCOOR' + RCOOH","oxidation","exothermic",
      "Peracid converts ketone to ester (or cyclic ketone to lactone). Oxygen insertion into C-C bond.",
      ["Peracid (m-CPBA or H₂O₂/acid)","Criegee intermediate","Cyclic ketone → lactone","Named after Adolf von Baeyer and Victor Villiger"],
      "organic","Baeyer-Villiger Oxidation"),
    rxn("named-clemmensen","Clemmensen Reduction",
      [reactant("RCOR'","Ketone/Aldehyde",1)],
      [product("RCH₂R'","Alkane","RCH₂R'",1)],
      "RCOR' + 4[H] → RCH₂R' + H₂O (Zn/Hg, HCl)","reduction","exothermic",
      "Carbonyl group reduced to methylene using Zn amalgam in HCl. Used for acid-sensitive substrates.",
      ["Zn/Hg amalgam in conc. HCl","Reduces C=O to CH₂","Used for acid-stable substrates","Named after Erik Christian Clemmensen"],
      "organic","Clemmensen Reduction"),
    rxn("named-wolff-kishner","Wolff-Kishner Reduction",
      [reactant("RCOR'","Ketone/Aldehyde",1),reactant("NH₂NH₂","Hydrazine",1)],
      [product("RCH₂R'","Alkane","RCH₂R'",1),product("N₂","Nitrogen","N₂",1)],
      "RCOR' + NH₂NH₂ → hydrazone → RCH₂R' + N₂ (KOH, Δ)","reduction","exothermic",
      "Carbonyl reduced to methylene via hydrazone under strong base. Complement to Clemmensen (base-stable).",
      ["KOH in ethylene glycol, high temp","Hydrazone intermediate","For base-stable substrates","Named after Ludwig Wolff and Nikolai Kishner"],
      "organic","Wolff-Kishner Reduction"),
  ] };

  // ── public API ─────────────────────────────────────────────────────────────
  public func getAllMetals() : [ReactivityMetal] { allMetals() };

  public func getMetalBySymbol(symbol : Text) : ?ReactivityMetal {
    let metals = allMetals();
    metals.find(func(m) { m.symbol == symbol })
  };

  public func getAllReactions() : [ChemicalReaction] { allReactions() };

  public func getReactionById(id : Text) : ?ChemicalReaction {
    let reactions = allReactions();
    reactions.find(func(r) { r.id == id })
  };

  public func searchReactions(term : Text) : [ChemicalReaction] {
    let lower = term.toLower();
    let reactions = allReactions();
    reactions.filter(func(r) {
      r.name.toLower().contains(#text lower) or
      r.reactionType.toLower().contains(#text lower) or
      r.description.toLower().contains(#text lower) or
      r.balancedEquation.toLower().contains(#text lower) or
      r.category.toLower().contains(#text lower) or
      r.namedReaction.toLower().contains(#text lower)
    })
  };

  public func getReactionsByCategory(category : Text) : [ChemicalReaction] {
    let lower = category.toLower();
    let reactions = allReactions();
    reactions.filter(func(r) { r.category.toLower() == lower })
  };

  public func getReactionsByType(rtype : Text) : [ChemicalReaction] {
    let lower = rtype.toLower();
    let reactions = allReactions();
    reactions.filter(func(r) { r.reactionType.toLower() == lower })
  };
};
