/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Element = IDL.Record({
  'atomicMass' : IDL.Float64,
  'electronConfiguration' : IDL.Text,
  'ionizationEnergy' : IDL.Float64,
  'period' : IDL.Nat,
  'density' : IDL.Float64,
  'electronegativity' : IDL.Float64,
  'name' : IDL.Text,
  'uses' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'meltingPoint' : IDL.Float64,
  'state' : IDL.Text,
  'colorHex' : IDL.Text,
  'group' : IDL.Nat,
  'category' : IDL.Text,
  'block' : IDL.Text,
  'boilingPoint' : IDL.Float64,
  'atomicNumber' : IDL.Nat,
  'symbol' : IDL.Text,
  'atomicRadius' : IDL.Float64,
  'facts' : IDL.Vec(IDL.Text),
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'joinDate' : Timestamp,
  'userId' : UserId,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const UserStats = IDL.Record({
  'progressScore' : IDL.Nat,
  'savedItemsCount' : IDL.Nat,
  'activityCount' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ChemicalProduct = IDL.Record({
  'coefficient' : IDL.Nat,
  'name' : IDL.Text,
  'formula' : IDL.Text,
  'symbol' : IDL.Text,
});
export const ChemicalReactant = IDL.Record({
  'coefficient' : IDL.Nat,
  'name' : IDL.Text,
  'symbol' : IDL.Text,
});
export const ChemicalReaction = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'balancedEquation' : IDL.Text,
  'description' : IDL.Text,
  'reactionType' : IDL.Text,
  'category' : IDL.Text,
  'energyChange' : IDL.Text,
  'products' : IDL.Vec(ChemicalProduct),
  'namedReaction' : IDL.Text,
  'reactants' : IDL.Vec(ChemicalReactant),
  'observations' : IDL.Vec(IDL.Text),
});
export const MetalReaction = IDL.Record({
  'reactionType' : IDL.Text,
  'observation' : IDL.Text,
  'equation' : IDL.Text,
  'partner' : IDL.Text,
});
export const ReactivityMetal = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'interestingFacts' : IDL.Vec(IDL.Text),
  'reactions' : IDL.Vec(MetalReaction),
  'symbol' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllElements' : IDL.Func([], [IDL.Vec(Element)], ['query']),
  'getElement' : IDL.Func([IDL.Text], [IDL.Opt(Element)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getPublicProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getQuizQuestion' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], ['query']),
  'getQuizQuestions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getReaction' : IDL.Func([IDL.Text], [IDL.Opt(ChemicalReaction)], ['query']),
  'getReactions' : IDL.Func([], [IDL.Vec(ChemicalReaction)], ['query']),
  'getReactionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChemicalReaction)],
      ['query'],
    ),
  'getReactionsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChemicalReaction)],
      ['query'],
    ),
  'getReactivityMetal' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReactivityMetal)],
      ['query'],
    ),
  'getReactivitySeries' : IDL.Func([], [IDL.Vec(ReactivityMetal)], ['query']),
  'recordActivity' : IDL.Func([], [], []),
  'searchElements' : IDL.Func([IDL.Text], [IDL.Vec(Element)], ['query']),
  'searchReactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChemicalReaction)],
      ['query'],
    ),
  'toggleFavorite' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateProgress' : IDL.Func([IDL.Nat], [], []),
  'upsertMyProfile' : IDL.Func([ProfileInput], [Profile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Element = IDL.Record({
    'atomicMass' : IDL.Float64,
    'electronConfiguration' : IDL.Text,
    'ionizationEnergy' : IDL.Float64,
    'period' : IDL.Nat,
    'density' : IDL.Float64,
    'electronegativity' : IDL.Float64,
    'name' : IDL.Text,
    'uses' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'meltingPoint' : IDL.Float64,
    'state' : IDL.Text,
    'colorHex' : IDL.Text,
    'group' : IDL.Nat,
    'category' : IDL.Text,
    'block' : IDL.Text,
    'boilingPoint' : IDL.Float64,
    'atomicNumber' : IDL.Nat,
    'symbol' : IDL.Text,
    'atomicRadius' : IDL.Float64,
    'facts' : IDL.Vec(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'joinDate' : Timestamp,
    'userId' : UserId,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const UserStats = IDL.Record({
    'progressScore' : IDL.Nat,
    'savedItemsCount' : IDL.Nat,
    'activityCount' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ChemicalProduct = IDL.Record({
    'coefficient' : IDL.Nat,
    'name' : IDL.Text,
    'formula' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const ChemicalReactant = IDL.Record({
    'coefficient' : IDL.Nat,
    'name' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const ChemicalReaction = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'balancedEquation' : IDL.Text,
    'description' : IDL.Text,
    'reactionType' : IDL.Text,
    'category' : IDL.Text,
    'energyChange' : IDL.Text,
    'products' : IDL.Vec(ChemicalProduct),
    'namedReaction' : IDL.Text,
    'reactants' : IDL.Vec(ChemicalReactant),
    'observations' : IDL.Vec(IDL.Text),
  });
  const MetalReaction = IDL.Record({
    'reactionType' : IDL.Text,
    'observation' : IDL.Text,
    'equation' : IDL.Text,
    'partner' : IDL.Text,
  });
  const ReactivityMetal = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'interestingFacts' : IDL.Vec(IDL.Text),
    'reactions' : IDL.Vec(MetalReaction),
    'symbol' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllElements' : IDL.Func([], [IDL.Vec(Element)], ['query']),
    'getElement' : IDL.Func([IDL.Text], [IDL.Opt(Element)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Profile)],
        ['query'],
      ),
    'getQuizQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QuizQuestion)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getReaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ChemicalReaction)],
        ['query'],
      ),
    'getReactions' : IDL.Func([], [IDL.Vec(ChemicalReaction)], ['query']),
    'getReactionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChemicalReaction)],
        ['query'],
      ),
    'getReactionsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChemicalReaction)],
        ['query'],
      ),
    'getReactivityMetal' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReactivityMetal)],
        ['query'],
      ),
    'getReactivitySeries' : IDL.Func([], [IDL.Vec(ReactivityMetal)], ['query']),
    'recordActivity' : IDL.Func([], [], []),
    'searchElements' : IDL.Func([IDL.Text], [IDL.Vec(Element)], ['query']),
    'searchReactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChemicalReaction)],
        ['query'],
      ),
    'toggleFavorite' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateProgress' : IDL.Func([IDL.Nat], [], []),
    'upsertMyProfile' : IDL.Func([ProfileInput], [Profile], []),
  });
};

export const init = ({ IDL }) => { return []; };