/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChemicalProduct {
  'coefficient' : bigint,
  'name' : string,
  'formula' : string,
  'symbol' : string,
}
export interface ChemicalReactant {
  'coefficient' : bigint,
  'name' : string,
  'symbol' : string,
}
export interface ChemicalReaction {
  'id' : string,
  'name' : string,
  'balancedEquation' : string,
  'description' : string,
  'reactionType' : string,
  'category' : string,
  'energyChange' : string,
  'products' : Array<ChemicalProduct>,
  'namedReaction' : string,
  'reactants' : Array<ChemicalReactant>,
  'observations' : Array<string>,
}
export interface Element {
  'atomicMass' : number,
  'electronConfiguration' : string,
  'ionizationEnergy' : number,
  'period' : bigint,
  'density' : number,
  'electronegativity' : number,
  'name' : string,
  'uses' : Array<string>,
  'description' : string,
  'meltingPoint' : number,
  'state' : string,
  'colorHex' : string,
  'group' : bigint,
  'category' : string,
  'block' : string,
  'boilingPoint' : number,
  'atomicNumber' : bigint,
  'symbol' : string,
  'atomicRadius' : number,
  'facts' : Array<string>,
}
export interface MetalReaction {
  'reactionType' : string,
  'observation' : string,
  'equation' : string,
  'partner' : string,
}
export interface Profile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'joinDate' : Timestamp,
  'userId' : UserId,
  'avatarUrl' : [] | [string],
}
export interface ProfileInput {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
}
export interface QuizQuestion {
  'id' : string,
  'topic' : string,
  'question' : string,
  'difficulty' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'questionType' : string,
  'options' : Array<string>,
}
export interface ReactivityMetal {
  'name' : string,
  'rank' : bigint,
  'interestingFacts' : Array<string>,
  'reactions' : Array<MetalReaction>,
  'symbol' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserStats {
  'progressScore' : bigint,
  'savedItemsCount' : bigint,
  'activityCount' : bigint,
}
export interface _SERVICE {
  'getAllElements' : ActorMethod<[], Array<Element>>,
  'getElement' : ActorMethod<[string], [] | [Element]>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getQuizQuestion' : ActorMethod<[string], [] | [QuizQuestion]>,
  'getQuizQuestions' : ActorMethod<[string, string], Array<QuizQuestion>>,
  'getReaction' : ActorMethod<[string], [] | [ChemicalReaction]>,
  'getReactions' : ActorMethod<[], Array<ChemicalReaction>>,
  'getReactionsByCategory' : ActorMethod<[string], Array<ChemicalReaction>>,
  'getReactionsByType' : ActorMethod<[string], Array<ChemicalReaction>>,
  'getReactivityMetal' : ActorMethod<[string], [] | [ReactivityMetal]>,
  'getReactivitySeries' : ActorMethod<[], Array<ReactivityMetal>>,
  'recordActivity' : ActorMethod<[], undefined>,
  'searchElements' : ActorMethod<[string], Array<Element>>,
  'searchReactions' : ActorMethod<[string], Array<ChemicalReaction>>,
  'toggleFavorite' : ActorMethod<[string], boolean>,
  'updateProgress' : ActorMethod<[bigint], undefined>,
  'upsertMyProfile' : ActorMethod<[ProfileInput], Profile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];