/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface ChemicalReaction {
    id: string;
    name: string;
    balancedEquation: string;
    description: string;
    reactionType: string;
    category: string;
    energyChange: string;
    products: Array<ChemicalProduct>;
    namedReaction: string;
    reactants: Array<ChemicalReactant>;
    observations: Array<string>;
}
export interface MetalReaction {
    reactionType: string;
    observation: string;
    equation: string;
    partner: string;
}
export interface ChemicalProduct {
    coefficient: bigint;
    name: string;
    formula: string;
    symbol: string;
}
export interface QuizQuestion {
    id: string;
    topic: string;
    question: string;
    difficulty: string;
    explanation: string;
    correctAnswer: string;
    questionType: string;
    options: Array<string>;
}
export interface ReactivityMetal {
    name: string;
    rank: bigint;
    interestingFacts: Array<string>;
    reactions: Array<MetalReaction>;
    symbol: string;
}
export interface ChemicalReactant {
    coefficient: bigint;
    name: string;
    symbol: string;
}
export interface Profile {
    bio: string;
    username: string;
    displayName: string;
    joinDate: Timestamp;
    userId: UserId;
    avatarUrl?: string;
}
export interface Element {
    atomicMass: number;
    electronConfiguration: string;
    ionizationEnergy: number;
    period: bigint;
    density: number;
    electronegativity: number;
    name: string;
    uses: Array<string>;
    description: string;
    meltingPoint: number;
    state: string;
    colorHex: string;
    group: bigint;
    category: string;
    block: string;
    boilingPoint: number;
    atomicNumber: bigint;
    symbol: string;
    atomicRadius: number;
    facts: Array<string>;
}
export interface ProfileInput {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl?: string;
}
export interface UserStats {
    progressScore: bigint;
    savedItemsCount: bigint;
    activityCount: bigint;
}
export interface backendInterface {
    getAllElements(): Promise<Array<Element>>;
    getElement(symbol: string): Promise<Element | null>;
    getFavorites(): Promise<Array<string>>;
    getMyProfile(): Promise<Profile | null>;
    getMyStats(): Promise<UserStats>;
    getPublicProfile(userId: Principal): Promise<Profile | null>;
    getQuizQuestion(id: string): Promise<QuizQuestion | null>;
    getQuizQuestions(difficulty: string, topic: string): Promise<Array<QuizQuestion>>;
    getReaction(id: string): Promise<ChemicalReaction | null>;
    getReactions(): Promise<Array<ChemicalReaction>>;
    getReactionsByCategory(category: string): Promise<Array<ChemicalReaction>>;
    getReactionsByType(rtype: string): Promise<Array<ChemicalReaction>>;
    getReactivityMetal(symbol: string): Promise<ReactivityMetal | null>;
    getReactivitySeries(): Promise<Array<ReactivityMetal>>;
    recordActivity(): Promise<void>;
    searchElements(searchTerm: string): Promise<Array<Element>>;
    searchReactions(term: string): Promise<Array<ChemicalReaction>>;
    toggleFavorite(symbol: string): Promise<boolean>;
    updateProgress(score: bigint): Promise<void>;
    upsertMyProfile(input: ProfileInput): Promise<Profile>;
}
import type { ChemicalReaction as _ChemicalReaction, Element as _Element, Profile as _Profile, ProfileInput as _ProfileInput, QuizQuestion as _QuizQuestion, ReactivityMetal as _ReactivityMetal, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllElements(): Promise<Array<Element>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllElements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllElements();
            return result;
        }
    }
    async getElement(arg0: string): Promise<Element | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getElement(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElement(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getMyProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return result;
        }
    }
    async getPublicProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestion(arg0: string): Promise<QuizQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestion(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestion(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(arg0: string, arg1: string): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0, arg1);
            return result;
        }
    }
    async getReaction(arg0: string): Promise<ChemicalReaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReaction(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReaction(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(): Promise<Array<ChemicalReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions();
            return result;
        }
    }
    async getReactionsByCategory(arg0: string): Promise<Array<ChemicalReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactionsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactionsByCategory(arg0);
            return result;
        }
    }
    async getReactionsByType(arg0: string): Promise<Array<ChemicalReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactionsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactionsByType(arg0);
            return result;
        }
    }
    async getReactivityMetal(arg0: string): Promise<ReactivityMetal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactivityMetal(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactivityMetal(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactivitySeries(): Promise<Array<ReactivityMetal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactivitySeries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactivitySeries();
            return result;
        }
    }
    async recordActivity(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordActivity();
            return result;
        }
    }
    async searchElements(arg0: string): Promise<Array<Element>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchElements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchElements(arg0);
            return result;
        }
    }
    async searchReactions(arg0: string): Promise<Array<ChemicalReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchReactions(arg0);
            return result;
        }
    }
    async toggleFavorite(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFavorite(arg0);
            return result;
        }
    }
    async updateProgress(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgress(arg0);
            return result;
        }
    }
    async upsertMyProfile(arg0: ProfileInput): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(to_candid_ProfileInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Profile_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(to_candid_ProfileInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Profile_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Profile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Element]): Element | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizQuestion]): QuizQuestion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChemicalReaction]): ChemicalReaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReactivityMetal]): ReactivityMetal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    joinDate: _Timestamp;
    userId: _UserId;
    avatarUrl: [] | [string];
}): {
    bio: string;
    username: string;
    displayName: string;
    joinDate: Timestamp;
    userId: UserId;
    avatarUrl?: string;
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        joinDate: value.joinDate,
        userId: value.userId,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function to_candid_ProfileInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileInput): _ProfileInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl?: string;
}): {
    bio: string;
    username: string;
    displayName: string;
    avatarUrl: [] | [string];
} {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
